# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/core/data.proto

require 'google/protobuf'


require 'internal/types/order_pb'
require 'internal/types/strade_pb'
require 'internal/types/account_pb'
require 'internal/types/position_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/core/data.proto", :syntax => :proto3) do
    add_message "CoreConfig" do
      optional :BlockChainIsBusy, :bool, 1
    end
    add_message "SerializableCoreTradingData" do
      optional :processedSequencesMap, :message, 1, "SerializableCoreTradingData.ProcessedSequencesMap"
      optional :accountMarketTradesMap, :message, 2, "SerializableCoreTradingData.AccountMarketTradesMap"
      optional :accountMarketOrdersMap, :message, 3, "SerializableCoreTradingData.AccountMarketOrdersMap"
      optional :accountBlockchainStatesMap, :message, 4, "SerializableCoreTradingData.AccountBlockchainStatesMap"
      optional :accountMarketPositionsMap, :message, 5, "SerializableCoreTradingData.AccountMarketPositionsMap"
      optional :gTTOrdersMap, :message, 6, "SerializableCoreTradingData.GTTOrdersMap"
      optional :settingMap, :message, 7, "SerializableCoreTradingData.SettingMap"
      optional :engineProcessResultOffsetMap, :message, 8, "SerializableCoreTradingData.EngineProcessResultOffsetMap"
      optional :coreConfig, :message, 9, "CoreConfig"
    end
    add_message "SerializableCoreTradingData.TradesMap" do
      map :TradesMap, :int64, :message, 1, "Trade"
    end
    add_message "SerializableCoreTradingData.MarketTradesMap" do
      map :MarketTradesMap, :string, :message, 1, "SerializableCoreTradingData.TradesMap"
    end
    add_message "SerializableCoreTradingData.AccountMarketTradesMap" do
      map :AccountMarketTradesMap, :string, :message, 1, "SerializableCoreTradingData.MarketTradesMap"
    end
    add_message "SerializableCoreTradingData.OrdersMap" do
      map :OrdersMap, :int64, :message, 1, "Order"
    end
    add_message "SerializableCoreTradingData.MarketOrdersMap" do
      map :MarketOrdersMap, :string, :message, 1, "SerializableCoreTradingData.OrdersMap"
    end
    add_message "SerializableCoreTradingData.AccountMarketOrdersMap" do
      map :AccountMarketOrdersMap, :string, :message, 1, "SerializableCoreTradingData.MarketOrdersMap"
    end
    add_message "SerializableCoreTradingData.MarketPositionsMap" do
      map :MarketPositionsMap, :string, :message, 1, "Position"
    end
    add_message "SerializableCoreTradingData.AccountMarketPositionsMap" do
      map :AccountMarketPositionsMap, :string, :message, 2, "SerializableCoreTradingData.MarketPositionsMap"
    end
    add_message "SerializableCoreTradingData.AccountBlockchainStatesMap" do
      map :AccountBlockchainStatesMap, :string, :message, 1, "AccountBlockchainState"
    end
    add_message "SerializableCoreTradingData.GTTOrdersMap" do
      map :GTTOrdersMap, :int64, :message, 1, "SerializableCoreTradingData.OrdersMap"
    end
    add_message "SerializableCoreTradingData.SettingMap" do
      map :SettingMap, :string, :string, 1
    end
    add_message "SerializableCoreTradingData.ProcessedSequencesMap" do
      map :ProcessedSequencesMap, :string, :uint64, 1
    end
    add_message "SerializableCoreTradingData.EngineProcessResultOffsetMap" do
      map :EngineProcessResultOffsetMap, :string, :int64, 1
    end
  end
end

module Internal
  module Core
    CoreConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreConfig").msgclass
    SerializableCoreTradingData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData").msgclass
    SerializableCoreTradingData::TradesMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.TradesMap").msgclass
    SerializableCoreTradingData::MarketTradesMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.MarketTradesMap").msgclass
    SerializableCoreTradingData::AccountMarketTradesMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.AccountMarketTradesMap").msgclass
    SerializableCoreTradingData::OrdersMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.OrdersMap").msgclass
    SerializableCoreTradingData::MarketOrdersMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.MarketOrdersMap").msgclass
    SerializableCoreTradingData::AccountMarketOrdersMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.AccountMarketOrdersMap").msgclass
    SerializableCoreTradingData::MarketPositionsMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.MarketPositionsMap").msgclass
    SerializableCoreTradingData::AccountMarketPositionsMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.AccountMarketPositionsMap").msgclass
    SerializableCoreTradingData::AccountBlockchainStatesMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.AccountBlockchainStatesMap").msgclass
    SerializableCoreTradingData::GTTOrdersMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.GTTOrdersMap").msgclass
    SerializableCoreTradingData::SettingMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.SettingMap").msgclass
    SerializableCoreTradingData::ProcessedSequencesMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.ProcessedSequencesMap").msgclass
    SerializableCoreTradingData::EngineProcessResultOffsetMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SerializableCoreTradingData.EngineProcessResultOffsetMap").msgclass
  end
end
