# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/core/output.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/types/order_pb'
require 'internal/types/account_pb'
require 'internal/types/tx_pb'
require 'internal/types/strade_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/core/output.proto", :syntax => :proto3) do
    add_message "CoreFSMOutput" do
      optional :ID, :string, 1
      optional :Time, :message, 2, "google.protobuf.Timestamp"
      optional :LogIndex, :uint64, 3
      optional :ClusterID, :uint32, 4
      oneof :Persistence do
        optional :OrderToSave, :message, 5, "Order"
        optional :TradeToSave, :message, 6, "Trade"
        optional :BlockchainSettlementComponent, :message, 7, "BlockchainSettlementComponent"
      end
      oneof :Notify do
        optional :ChangedOrder, :message, 8, "Order"
        optional :ChangedTrade, :message, 9, "Trade"
        optional :ChangedAccountState, :message, 10, "AccountState"
      end
    end
  end
end

module Internal
  module Core
    CoreFSMOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMOutput").msgclass
  end
end
