# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/core/raft.proto

require 'google/protobuf'


require 'internal/types/order_pb'
require 'internal/types/trade_pb'
require 'internal/types/strade_pb'
require 'internal/types/account_pb'
require 'internal/types/position_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/core/raft.proto", :syntax => :proto3) do
    add_message "CreateOrderMarketParams" do
      optional :MarkPrice, :message, 1, "DecimalMessage"
      optional :InitialLeverage, :message, 2, "DecimalMessage"
      optional :AccountMaxExposure, :message, 3, "DecimalMessage"
      optional :OffchainMarkPrice, :message, 4, "DecimalMessage"
    end
    add_message "CoreFSMCreateOrderCommand" do
      optional :Order, :message, 1, "Order"
      map :MarketsParams, :string, :message, 2, "CreateOrderMarketParams"
      optional :SkipMarginCheck, :bool, 3
    end
    add_message "CoreFSMModifyOrderAmountCommand" do
      optional :ModifyType, :enum, 1, "CoreFSMModifyOrderCommandType"
      optional :OrderID, :int64, 2
      optional :MarketID, :string, 3
      optional :Account, :message, 4, "AddressMessage"
      optional :Amount, :message, 5, "DecimalMessage"
      optional :FinalReason, :string, 6
      optional :InsiderTradingOrder, :message, 7, "Order"
      optional :InsiderTradingLeverage, :message, 8, "DecimalMessage"
    end
    add_message "CoreFSMNewTradeCommand" do
      optional :Sequence, :uint64, 1
      optional :Trade, :message, 2, "Trade"
      optional :InsiderTradingOrder, :message, 3, "Order"
      optional :InsiderTradingLeverage, :message, 4, "DecimalMessage"
    end
    add_message "CoreFSMUpdateTradeStatusCommand" do
      optional :TradeID, :int64, 1
      optional :MarketID, :string, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :Status, :enum, 4, "TX_STATUS"
    end
    add_message "CoreFSWUpdateAccountBlockStateCommand" do
      optional :State, :message, 1, "AccountBlockchainState"
    end
    add_message "CoreFSWUpdateAccountPositionCommand" do
      optional :Position, :message, 1, "Position"
    end
    add_message "CoreFSWUpdateAccountTradesAndPositionCommand" do
      optional :Position, :message, 1, "Position"
      repeated :UpdateTradeStatusCommands, :message, 2, "CoreFSMUpdateTradeStatusCommand"
    end
    add_message "CoreFSWUpdateSettingsCommand" do
      optional :Key, :string, 1
      optional :Value, :string, 2
    end
    add_message "CoreFSMClearProcessedOrderMessageIDsCommand" do
    end
    add_message "CoreFSMFlushAllCommand" do
    end
    add_message "CoreFSMMatchSubCommand" do
      oneof :Command do
        optional :ModifyOrder, :message, 1, "CoreFSMModifyOrderAmountCommand"
        optional :NewTrade, :message, 2, "CoreFSMNewTradeCommand"
      end
    end
    add_message "CoreFSMSystemCommand" do
      oneof :Command do
        optional :FlushAll, :message, 1, "CoreFSMFlushAllCommand"
        optional :UpdateSettings, :message, 2, "CoreFSWUpdateSettingsCommand"
        optional :SetCoreConfig, :message, 3, "CoreFSWUpdateSettingsCommand"
      end
    end
    add_message "CoreFSMRepeatableCommand" do
      optional :ID, :string, 1
      oneof :Command do
        optional :UpdateTradeStatus, :message, 3, "CoreFSMUpdateTradeStatusCommand"
        optional :UpdateAccountBlockState, :message, 4, "CoreFSWUpdateAccountBlockStateCommand"
        optional :UpdateAccountPosition, :message, 5, "CoreFSWUpdateAccountPositionCommand"
        optional :CreateOrder, :message, 6, "CoreFSMCreateOrderCommand"
        optional :UpdateAccountTradesAndPosition, :message, 7, "CoreFSWUpdateAccountTradesAndPositionCommand"
      end
    end
    add_message "CoreFSMMatchCommand" do
      optional :MarketID, :string, 1
      optional :Sequence, :uint64, 2
      optional :ClusterID, :uint64, 3
      repeated :SubCommands, :message, 4, "CoreFSMMatchSubCommand"
    end
    add_message "CoreFSMMatchCommands" do
      optional :EngineProcessResultOffset, :int64, 1
      repeated :MatchCommand, :message, 2, "CoreFSMMatchCommand"
    end
    add_message "CoreFSMBatchCreateOrderCommand" do
      repeated :CreateOrderCommands, :message, 1, "CoreFSMCreateOrderCommand"
    end
    add_message "CoreFSMCommandResponse" do
      optional :ResponseCode, :int32, 1
    end
    add_message "CoreFSMBatchCommandResponse" do
      repeated :ResponseCodes, :int32, 1
    end
    add_message "CoreFSMCommand" do
      oneof :Command do
        optional :SystemCommand, :message, 1, "CoreFSMSystemCommand"
        optional :RepeatableCommand, :message, 2, "CoreFSMRepeatableCommand"
        optional :MatchCommands, :message, 3, "CoreFSMMatchCommands"
        optional :BatchCreateOrderCommand, :message, 5, "CoreFSMBatchCreateOrderCommand"
      end
    end
    add_enum "CoreFSMModifyOrderCommandType" do
      value :NEW_ORDER_AMOUNT, 0
      value :CANCEL_ORDER_AMOUNT, 1
      value :EXPIRE_ORDER_AMOUNT, 2
    end
  end
end

module Internal
  module Core
    CreateOrderMarketParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateOrderMarketParams").msgclass
    CoreFSMCreateOrderCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMCreateOrderCommand").msgclass
    CoreFSMModifyOrderAmountCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMModifyOrderAmountCommand").msgclass
    CoreFSMNewTradeCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMNewTradeCommand").msgclass
    CoreFSMUpdateTradeStatusCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMUpdateTradeStatusCommand").msgclass
    CoreFSWUpdateAccountBlockStateCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSWUpdateAccountBlockStateCommand").msgclass
    CoreFSWUpdateAccountPositionCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSWUpdateAccountPositionCommand").msgclass
    CoreFSWUpdateAccountTradesAndPositionCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSWUpdateAccountTradesAndPositionCommand").msgclass
    CoreFSWUpdateSettingsCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSWUpdateSettingsCommand").msgclass
    CoreFSMClearProcessedOrderMessageIDsCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMClearProcessedOrderMessageIDsCommand").msgclass
    CoreFSMFlushAllCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMFlushAllCommand").msgclass
    CoreFSMMatchSubCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMMatchSubCommand").msgclass
    CoreFSMSystemCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMSystemCommand").msgclass
    CoreFSMRepeatableCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMRepeatableCommand").msgclass
    CoreFSMMatchCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMMatchCommand").msgclass
    CoreFSMMatchCommands = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMMatchCommands").msgclass
    CoreFSMBatchCreateOrderCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMBatchCreateOrderCommand").msgclass
    CoreFSMCommandResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMCommandResponse").msgclass
    CoreFSMBatchCommandResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMBatchCommandResponse").msgclass
    CoreFSMCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMCommand").msgclass
    CoreFSMModifyOrderCommandType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CoreFSMModifyOrderCommandType").enummodule
  end
end
