# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/core/server.proto for package 'Internal.Core'

require 'grpc'
require 'internal/core/server_pb'

module Internal
  module Core
    module CoreTradingService
      # The external services of the core cluster should only be called by the
      # Gateway
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'CoreTradingService'

        rpc :CreateOrder, ::Internal::Core::CreateOrderRequest, ::Internal::Core::CreateOrderResponse
        rpc :AsyncCreateOrder, ::Internal::Core::CreateOrderRequest, ::Internal::Core::CreateOrderResponse
        rpc :CancelOrder, ::Internal::Core::CancelOrderRequest, ::Internal::Core::CancelOrderResponse
        rpc :CancelAllOrders, ::Internal::Core::CancelAllOrdersRequest, ::Internal::Core::CancelAllOrdersResponse
        rpc :GetAccountOrders, ::Internal::Core::AccountOrdersRequest, ::Internal::Core::AccountOrdersResponse
        rpc :GetAccountOrdersAndTrades, ::Internal::Core::AccountOrdersRequest, ::Internal::Core::AccountOrdersResponse
        rpc :GetAccountState, ::Internal::Core::AccountStateRequest, ::Internal::Types::AccountState
        rpc :GetAccountStates, ::Internal::Core::AccountStatesRequest, ::Internal::Types::AccountStates
        rpc :GetAccountStatesWithPosition, ::Google::Protobuf::Empty, ::Internal::Types::AccountStates
        rpc :GetAccountPositions, ::Internal::Core::AccountPositionsRequest, ::Internal::Core::AccountPositionsResponse
        # rpc GetMarketStatus(SingleMarketStatusRequest)
        # returns (SingleMarketStatus) {}
        # rpc GetAllMarketStatus(AllMarketStatusRequest)
        # returns (AllMarketStatusResponse) {}
        rpc :GetAvailableCredit, ::Internal::Core::GetAvailableCreditRequest, ::Internal::Core::GetAvailableCreditResponse
        # market level risk state
        rpc :GetPlatformRisks, ::Google::Protobuf::Empty, ::Internal::Core::GetPlatformRisksResponse
        # account level risk
        rpc :GetAllAccountStates, ::Google::Protobuf::Empty, ::Internal::Core::GetAllAccountsStatesResponse
        # cancel signature free order
        rpc :CancelSignatureFreeOrder, ::Internal::Core::CancelSignatureFreeOrderRequest, ::Internal::Core::CancelSignatureFreeOrderResponse
        rpc :VerifyAccountMarketLeverage, ::Internal::Core::VerifyAccountMarketLeverageRequest, ::Internal::Core::VerifyAccountMarketLeverageResponse
        rpc :GetBlockchainAccountStates, ::Internal::Core::GetBlockchainAccountStatesRequest, ::Internal::Core::GetBlockchainAccountStatesResponse
        rpc :GetRawPositions, ::Internal::Core::GetRawPositionsRequest, ::Internal::Core::GetRawPositionsResponse
        rpc :GetPendingTrades, ::Internal::Core::GetPendingTradesRequest, ::Internal::Core::GetPendingTradesResponse
        rpc :GetAccountListWithAssets, ::Internal::Types::GetAccountListRequest, ::Internal::Types::GetAccountListResponse
        rpc :GetAccountListWithPosition, ::Internal::Types::GetAccountListRequest, ::Internal::Types::GetAccountListResponse
      end

      Stub = Service.rpc_stub_class
    end
    module CoreAdminService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'CoreAdminService'

        rpc :CancelOrder, ::Internal::Core::CancelOrderRequest, ::Internal::Core::CancelOrderResponse
        rpc :CancelMarketOrders, ::Google::Protobuf::StringValue, ::Google::Protobuf::BoolValue
        # suspend orders are those orders that are not in the engine
        rpc :SetTradeFailed, ::Internal::Core::SetTradeFailedRequest, ::Internal::Core::SetTradeFailedResponse
        rpc :GetAccountOrders, ::Internal::Core::AccountOrdersRequest, ::Internal::Core::AccountOrdersResponse
        rpc :UpdateSettings, ::Internal::Core::UpdateSettingsRequest, ::Google::Protobuf::Empty
        rpc :FlushAll, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :GetDataSnapshot, ::Google::Protobuf::Empty, ::Internal::Core::SerializableCoreTradingData
        rpc :GetCoreConfig, ::Google::Protobuf::Empty, ::Internal::Core::CoreConfig
        rpc :SetCoreConfigBlockChainIsBusy, ::Google::Protobuf::BoolValue, ::Google::Protobuf::Empty
      end

      Stub = Service.rpc_stub_class
    end
    module GatewayService
      # A stateless service that hides the details of grouping users into different
      # core clusters. This is the service that should be used by components that
      # rely on core data.
      #
      # Watch events will obtain data from the queue, and will not directly access
      # the upstream core clusters.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'GatewayService'

        rpc :CreateOrder, ::Internal::Core::CreateOrderRequest, ::Internal::Core::CreateOrderResponse
        rpc :AsyncCreateOrder, ::Internal::Core::CreateOrderRequest, ::Internal::Core::CreateOrderResponse
        rpc :CancelOrder, ::Internal::Core::CancelOrderRequest, ::Internal::Core::CancelOrderResponse
        rpc :CancelAllOrders, ::Internal::Core::CancelAllOrdersRequest, ::Internal::Core::CancelAllOrdersResponse
        rpc :GetAccountOrders, ::Internal::Core::AccountOrdersRequest, ::Internal::Core::AccountOrdersResponse
        rpc :GetAccountOrdersAndTrades, ::Internal::Core::AccountOrdersRequest, ::Internal::Core::AccountOrdersResponse
        rpc :GetAccountState, ::Internal::Core::AccountStateRequest, ::Internal::Types::AccountState
        rpc :GetAccountStates, ::Internal::Core::AccountStatesRequest, ::Internal::Types::AccountStates
        rpc :GetAccountStatesWithPosition, ::Google::Protobuf::Empty, ::Internal::Types::AccountStates
        # rpc WatchAccountState(AccountStateRequest) returns (stream AccountState)
        # {}
        #
        rpc :GetAccountPositions, ::Internal::Core::AccountPositionsRequest, ::Internal::Core::AccountPositionsResponse
        rpc :GetAvailableCredit, ::Internal::Core::GetAvailableCreditRequest, ::Internal::Core::GetAvailableCreditResponse
        # market level risk state
        rpc :GetPlatformRisks, ::Google::Protobuf::Empty, ::Internal::Core::GetPlatformRisksResponse
        rpc :GetAllAccountStates, ::Google::Protobuf::Empty, ::Internal::Core::GetAllAccountsStatesResponse
        # cancel signature free order
        rpc :CancelSignatureFreeOrder, ::Internal::Core::CancelSignatureFreeOrderRequest, ::Internal::Core::CancelSignatureFreeOrderResponse
        rpc :VerifyAccountMarketLeverage, ::Internal::Core::VerifyAccountMarketLeverageRequest, ::Internal::Core::VerifyAccountMarketLeverageResponse
        rpc :GetBlockchainAccountStates, ::Internal::Core::GetBlockchainAccountStatesRequest, ::Internal::Core::GetBlockchainAccountStatesResponse
        rpc :GetRawPositions, ::Internal::Core::GetRawPositionsRequest, ::Internal::Core::GetRawPositionsResponse
        rpc :GetPendingTrades, ::Internal::Core::GetPendingTradesRequest, ::Internal::Core::GetPendingTradesResponse
        rpc :GetAccountListWithAssets, ::Internal::Types::GetAccountListRequest, ::Internal::Types::GetAccountListResponse
        rpc :GetAccountListWithPosition, ::Internal::Types::GetAccountListRequest, ::Internal::Types::GetAccountListResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
