# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/core/server.proto

require 'google/protobuf'


require 'internal/types/position_pb'
require 'internal/types/order_pb'
require 'internal/types/market_pb'
require 'internal/errors/order_pb'
require 'internal/types/strade_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'
require 'google/protobuf/empty_pb'
require 'internal/types/account_pb'
require 'internal/types/types_pb'
require 'internal/core/data_pb'
require 'google/protobuf/wrappers_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/core/server.proto", :syntax => :proto3) do
    add_message "CreateOrderRequest" do
      optional :Order, :message, 1, "Order"
      optional :OperationType, :string, 2
    end
    add_message "CreateOrderResponse" do
      optional :OrderID, :int64, 2
      optional :Order, :message, 3, "Order"
      optional :OrderError, :message, 4, "OrderError"
    end
    add_message "AccountOrdersRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :MarketID, :string, 2
      optional :OrderID, :int64, 3
    end
    add_message "AccountOrdersResponse" do
      repeated :Orders, :message, 1, "Order"
      repeated :Trades, :message, 2, "Trade"
    end
    add_message "AccountStateRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "AccountStatesRequest" do
      repeated :Account, :message, 1, "AddressMessage"
    end
    add_message "AccountPositionsRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "AccountPositionsResponse" do
      repeated :Positions, :message, 1, "Position"
    end
    add_message "AccountMarketDataRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "AccountsMarketDataRequest" do
      repeated :Accounts, :message, 1, "AddressMessage"
    end
    add_message "AllMarketStatusRequest" do
    end
    add_message "SingleMarketStatusRequest" do
      optional :MarketID, :string, 1
    end
    add_message "AllMarketStatusResponse" do
      repeated :Markets, :message, 1, "SingleMarketStatus"
    end
    add_message "GetAvailableCreditRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :MarketID, :string, 2
      optional :Side, :enum, 3, "SIDE"
    end
    add_message "GetAvailableCreditResponse" do
      optional :Amount, :message, 1, "DecimalMessage"
    end
    add_message "GetAllAccountsStatesRequest" do
      repeated :Accounts, :message, 1, "AccountState"
    end
    add_message "GetAllAccountsStatesResponse" do
      repeated :Accounts, :message, 1, "AccountState"
    end
    add_message "GetPlatformRisksResponse" do
      repeated :Markets, :message, 1, "MarketRiskState"
    end
    add_message "CancelOrderRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :OrderID, :int64, 2
      optional :MarketID, :string, 3
      optional :FinalReason, :string, 4
      optional :RequestFrom, :string, 5
    end
    add_message "CancelOrderResponse" do
      optional :NotFoundInCore, :bool, 1
      optional :ErrorMessage, :string, 2
    end
    add_message "CancelAllOrdersRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :MarketID, :string, 2
      optional :FinalReason, :string, 3
      optional :RequestFrom, :string, 5
    end
    add_message "CancelAllOrdersResponse" do
      optional :Success, :bool, 1
    end
    add_message "CancelSignatureFreeOrderRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :FinalReason, :string, 2
    end
    add_message "CancelSignatureFreeOrderResponse" do
      optional :Success, :bool, 1
    end
    add_message "UpdateSettingsRequest" do
      optional :Key, :string, 1
      optional :Value, :string, 2
    end
    add_message "RemoveAccountMarketSuspendedOrdersRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :MarketID, :string, 3
    end
    add_message "RemoveAccountMarketSuspendedOrdersResponse" do
      repeated :OrderIDs, :int64, 1
    end
    add_message "SetTradeFailedRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :TradeID, :int64, 2
      optional :MarketID, :string, 3
    end
    add_message "SetTradeFailedResponse" do
      optional :NotFoundInCore, :bool, 1
      optional :SetFailed, :bool, 2
    end
    add_message "VerifyAccountMarketLeverageRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :MarketID, :string, 2
      optional :Leverage, :message, 3, "DecimalMessage"
    end
    add_message "VerifyAccountMarketLeverageResponse" do
      optional :Result, :bool, 1
      optional :ErrorCode, :int32, 2
      optional :ErrorMsg, :string, 3
    end
    add_message "GetBlockchainAccountStatesRequest" do
      repeated :Accounts, :message, 1, "AddressMessage"
    end
    add_message "GetBlockchainAccountStatesResponse" do
      repeated :BlockchainStates, :message, 1, "AccountBlockchainState"
    end
    add_message "GetRawPositionsRequest" do
      repeated :Accounts, :message, 1, "AddressMessage"
    end
    add_message "RawPosition" do
      optional :Account, :message, 1, "AddressMessage"
      repeated :Positions, :message, 2, "Position"
    end
    add_message "GetRawPositionsResponse" do
      repeated :RawPositions, :message, 1, "RawPosition"
    end
    add_message "GetPendingTradesRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :MarketID, :string, 2
    end
    add_message "GetPendingTradesResponse" do
      repeated :Trades, :message, 1, "Trade"
    end
  end
end

module Internal
  module Core
    CreateOrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateOrderRequest").msgclass
    CreateOrderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateOrderResponse").msgclass
    AccountOrdersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountOrdersRequest").msgclass
    AccountOrdersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountOrdersResponse").msgclass
    AccountStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountStateRequest").msgclass
    AccountStatesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountStatesRequest").msgclass
    AccountPositionsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountPositionsRequest").msgclass
    AccountPositionsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountPositionsResponse").msgclass
    AccountMarketDataRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountMarketDataRequest").msgclass
    AccountsMarketDataRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountsMarketDataRequest").msgclass
    AllMarketStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AllMarketStatusRequest").msgclass
    SingleMarketStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SingleMarketStatusRequest").msgclass
    AllMarketStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AllMarketStatusResponse").msgclass
    GetAvailableCreditRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAvailableCreditRequest").msgclass
    GetAvailableCreditResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAvailableCreditResponse").msgclass
    GetAllAccountsStatesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAllAccountsStatesRequest").msgclass
    GetAllAccountsStatesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAllAccountsStatesResponse").msgclass
    GetPlatformRisksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPlatformRisksResponse").msgclass
    CancelOrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelOrderRequest").msgclass
    CancelOrderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelOrderResponse").msgclass
    CancelAllOrdersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelAllOrdersRequest").msgclass
    CancelAllOrdersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelAllOrdersResponse").msgclass
    CancelSignatureFreeOrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelSignatureFreeOrderRequest").msgclass
    CancelSignatureFreeOrderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelSignatureFreeOrderResponse").msgclass
    UpdateSettingsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UpdateSettingsRequest").msgclass
    RemoveAccountMarketSuspendedOrdersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RemoveAccountMarketSuspendedOrdersRequest").msgclass
    RemoveAccountMarketSuspendedOrdersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RemoveAccountMarketSuspendedOrdersResponse").msgclass
    SetTradeFailedRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SetTradeFailedRequest").msgclass
    SetTradeFailedResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SetTradeFailedResponse").msgclass
    VerifyAccountMarketLeverageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VerifyAccountMarketLeverageRequest").msgclass
    VerifyAccountMarketLeverageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VerifyAccountMarketLeverageResponse").msgclass
    GetBlockchainAccountStatesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetBlockchainAccountStatesRequest").msgclass
    GetBlockchainAccountStatesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetBlockchainAccountStatesResponse").msgclass
    GetRawPositionsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetRawPositionsRequest").msgclass
    RawPosition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RawPosition").msgclass
    GetRawPositionsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetRawPositionsResponse").msgclass
    GetPendingTradesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPendingTradesRequest").msgclass
    GetPendingTradesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPendingTradesResponse").msgclass
  end
end
