# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/trigger/server.proto for package 'Internal.Trigger'

require 'grpc'
require 'internal/trigger/server_pb'

module Internal
  module Trigger
    module TriggerService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'TriggerService'

        rpc :AddTpslOrder, ::Internal::Trigger::AddTpslOrderReq, ::Google::Protobuf::Empty
        rpc :DeleteTpslOrder, ::Internal::Trigger::DeleteTpslOrderReq, ::Internal::Types::TpslOrder
        rpc :DeleteAllTpslOrders, ::Internal::Trigger::DeleteAllTpslOrderReq, ::Internal::Trigger::DeleteAllTpslOrderResp
        rpc :GetPositionTpslOrders, ::Internal::Trigger::GetPositionTpslOrderReq, ::Internal::Trigger::GetPositionTpslOrderResp
        rpc :GetTpslOrders, ::Internal::Trigger::GetAllTpslOrderReq, ::Internal::Trigger::GetAllTpslOrderResp
        # Grid Order
        rpc :CancelGridOrder, ::Internal::Trigger::CancelGridOrderReq, ::Internal::Trigger::CancelGridOrderResp
        rpc :CancelAllGridOrders, ::Internal::Trigger::CancelAllGridOrdersReq, ::Internal::Trigger::CancelAllGridOrdersResp
        rpc :UpdateGridOrderStopPrice, ::Internal::Trigger::UpdateGridOrderStopPriceReq, ::Internal::Trigger::UpdateGridOrderResp
        rpc :UpdateGridOrderStopProfit, ::Internal::Trigger::UpdateGridOrderStopProfitReq, ::Internal::Trigger::UpdateGridOrderResp
        rpc :WatchAccountsWithGridOrder, ::Google::Protobuf::Empty, stream(::Internal::Trigger::WatchAccountsWithGridOrderResp)
        rpc :WithdrawIdleGridAmount, ::Internal::Trigger::WithdrawIdleGridAmountRequest, ::Internal::Trigger::WithdrawIdleGridAmountResponse
        rpc :GetEnabledCreateGridOrderAccounts, ::Internal::Trigger::GetEnabledCreateGridOrderAccountsRequest, ::Internal::Trigger::GetEnabledCreateGridOrderAccountsResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
