# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/trigger/server.proto

require 'google/protobuf'


require 'google/protobuf/empty_pb'
require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'
require 'internal/types/tpsl_order_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/trigger/server.proto", :syntax => :proto3) do
    add_message "AddTpslOrderReq" do
      optional :MarketID, :string, 1
      repeated :tpslOrders, :message, 2, "TpslOrder"
    end
    add_message "DeleteTpslOrderReq" do
      optional :MarketID, :string, 1
      optional :ID, :int64, 2
      optional :Account, :message, 3, "AddressMessage"
    end
    add_message "DeleteAllTpslOrderReq" do
      optional :MarketID, :string, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TpslOrderType, :string, 3
    end
    add_message "DeleteAllTpslOrderResp" do
      repeated :tpslOrders, :message, 1, "TpslOrder"
    end
    add_message "GetPositionTpslOrderReq" do
      optional :MarketID, :string, 1
      optional :Account, :message, 2, "AddressMessage"
    end
    add_message "GetPositionTpslOrderResp" do
      repeated :tpOrders, :message, 1, "TpslOrder"
      repeated :slOrders, :message, 2, "TpslOrder"
    end
    add_message "GetAllTpslOrderReq" do
      optional :MarketID, :string, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TpslOrderType, :string, 3
    end
    add_message "GetAllTpslOrderResp" do
      repeated :tpslOrders, :message, 1, "TpslOrder"
    end
    add_message "CancelGridOrderReq" do
      optional :GridOrderID, :int64, 1
    end
    add_message "CancelGridOrderResp" do
      optional :Success, :bool, 1
    end
    add_message "CancelAllGridOrdersReq" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "CancelAllGridOrdersResp" do
      optional :Success, :bool, 1
    end
    add_message "AccountWithGridOrder" do
      optional :MarketID, :string, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Owner, :message, 3, "AddressMessage"
      optional :GridOrderStatus, :string, 4
      optional :HasPosition, :bool, 5
      optional :HasTransferBackAssets, :bool, 6
      optional :GridOrderID, :int64, 7
      optional :SettledAt, :message, 8, "google.protobuf.Timestamp"
    end
    add_message "UpdateGridOrderStopPriceReq" do
      optional :GridOrderID, :int64, 1
      optional :StopLowerPrice, :message, 2, "DecimalMessage"
      optional :StopUpperPrice, :message, 3, "DecimalMessage"
      optional :StopPriceType, :string, 4
    end
    add_message "UpdateGridOrderResp" do
      optional :Success, :bool, 1
    end
    add_message "UpdateGridOrderStopProfitReq" do
      optional :GridOrderID, :int64, 1
      optional :TakeProfitPnl, :message, 2, "DecimalMessage"
      optional :StopLossPnl, :message, 3, "DecimalMessage"
    end
    add_message "WatchAccountsWithGridOrderResp" do
      repeated :AccountsWithGridOrders, :message, 1, "AccountWithGridOrder"
    end
    add_message "WithdrawIdleGridAmountRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "WithdrawIdleGridAmountResponse" do
      optional :Success, :bool, 1
    end
    add_message "GetEnabledCreateGridOrderAccountsRequest" do
      repeated :Accounts, :message, 1, "AddressMessage"
    end
    add_message "GetEnabledCreateGridOrderAccountsResponse" do
      repeated :Accounts, :message, 1, "AddressMessage"
    end
  end
end

module Internal
  module Trigger
    AddTpslOrderReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AddTpslOrderReq").msgclass
    DeleteTpslOrderReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DeleteTpslOrderReq").msgclass
    DeleteAllTpslOrderReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DeleteAllTpslOrderReq").msgclass
    DeleteAllTpslOrderResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DeleteAllTpslOrderResp").msgclass
    GetPositionTpslOrderReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPositionTpslOrderReq").msgclass
    GetPositionTpslOrderResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPositionTpslOrderResp").msgclass
    GetAllTpslOrderReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAllTpslOrderReq").msgclass
    GetAllTpslOrderResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAllTpslOrderResp").msgclass
    CancelGridOrderReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelGridOrderReq").msgclass
    CancelGridOrderResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelGridOrderResp").msgclass
    CancelAllGridOrdersReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelAllGridOrdersReq").msgclass
    CancelAllGridOrdersResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelAllGridOrdersResp").msgclass
    AccountWithGridOrder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountWithGridOrder").msgclass
    UpdateGridOrderStopPriceReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UpdateGridOrderStopPriceReq").msgclass
    UpdateGridOrderResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UpdateGridOrderResp").msgclass
    UpdateGridOrderStopProfitReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UpdateGridOrderStopProfitReq").msgclass
    WatchAccountsWithGridOrderResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WatchAccountsWithGridOrderResp").msgclass
    WithdrawIdleGridAmountRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WithdrawIdleGridAmountRequest").msgclass
    WithdrawIdleGridAmountResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WithdrawIdleGridAmountResponse").msgclass
    GetEnabledCreateGridOrderAccountsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetEnabledCreateGridOrderAccountsRequest").msgclass
    GetEnabledCreateGridOrderAccountsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetEnabledCreateGridOrderAccountsResponse").msgclass
  end
end
