# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/jusd_collateral_calculation/server.proto

require 'google/protobuf'


require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/types/jusd_collateral_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/jusd_collateral_calculation/server.proto", :syntax => :proto3) do
    add_message "GetRiskyAccountsRequest" do
      optional :RiskThreshold, :message, 1, "DecimalMessage"
    end
    add_message "GetRiskyAccountsResponse" do
      repeated :RiskAccountsSates, :message, 1, "AccountCollateralState"
    end
    add_message "GetAccountCollateralStateRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
  end
end

module Internal
  module JusdCollateral_calculation
    GetRiskyAccountsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetRiskyAccountsRequest").msgclass
    GetRiskyAccountsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetRiskyAccountsResponse").msgclass
    GetAccountCollateralStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountCollateralStateRequest").msgclass
  end
end
