# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/jusd_collateral_calculation/server.proto for package 'Internal.JusdCollateral_calculation'

require 'grpc'
require 'internal/jusd_collateral_calculation/server_pb'

module Internal
  module JusdCollateralCalculation
    module JusdCollateralCalculationService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'JusdCollateralCalculationService'

        rpc :GetRiskyAccounts, ::Internal::JusdCollateralCalculation::GetRiskyAccountsRequest, ::Internal::JusdCollateralCalculation::GetRiskyAccountsResponse
        rpc :GetAccountCollateralState, ::Internal::JusdCollateralCalculation::GetAccountCollateralStateRequest, ::Internal::Types::AccountCollateralState
      end

      Stub = Service.rpc_stub_class
    end
  end
end
