# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/orderbook/server.proto

require 'google/protobuf'


require 'internal/types/engine_pb'
require 'internal/engine/types_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/orderbook/server.proto", :syntax => :proto3) do
    add_message "GetSnapshotRequest" do
      optional :MarketID, :string, 1
      optional :Limit, :int32, 2
    end
    add_message "GetSnapshotResponse" do
      optional :MarketID, :string, 1
      optional :Snapshot, :bytes, 2
    end
    add_message "WatchLastMatchEventRequest" do
      optional :MarketID, :string, 1
    end
    add_message "DepthRequest" do
      optional :MarketID, :string, 1
      optional :DepthType, :enum, 2, "DepthType"
    end
  end
end

module Internal
  module Orderbook
    GetSnapshotRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSnapshotRequest").msgclass
    GetSnapshotResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSnapshotResponse").msgclass
    WatchLastMatchEventRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WatchLastMatchEventRequest").msgclass
    DepthRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DepthRequest").msgclass
  end
end
