# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/orderbook/server.proto for package 'Internal.Orderbook'

require 'grpc'
require 'internal/orderbook/server_pb'

module Internal
  module Orderbook
    module OrderbookService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'OrderbookService'

        rpc :GetOrderbookSnapshot, ::Internal::Orderbook::GetSnapshotRequest, ::Internal::Orderbook::GetSnapshotResponse
        rpc :WatchLastMatchEvent, ::Internal::Orderbook::WatchLastMatchEventRequest, stream(::Internal::Types::OrderbookProcessResult)
        rpc :GetDepth, ::Internal::Orderbook::DepthRequest, ::Internal::Engine::Depth
        rpc :WatchDepth, ::Internal::Orderbook::DepthRequest, stream(::Internal::Engine::Depth)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
