# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/message/message.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'
require 'internal/types/account_pb'
require 'internal/types/position_pb'
require 'internal/types/trade_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/message/message.proto", :syntax => :proto3) do
    add_message "AccountOrdersCancellationCausedByLiquidation" do
      optional :Account, :message, 1, "AddressMessage"
      optional :MarketID, :string, 2
    end
    add_message "UpdateTradeStatus" do
      optional :TradeID, :int64, 1
      optional :MarketID, :string, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :Status, :enum, 4, "TX_STATUS"
    end
    add_message "TradesWithPosition" do
      optional :Position, :message, 1, "Position"
      repeated :UpdateTrades, :message, 2, "UpdateTradeStatus"
    end
    add_message "CalculationAccountOutput" do
      optional :BlockNumber, :message, 3, "DecimalMessage"
      optional :ID, :string, 4
      oneof :Output do
        optional :AccountBlockchainState, :message, 1, "AccountBlockchainState"
        optional :Position, :message, 2, "Position"
        optional :TradesWithPosition, :message, 5, "TradesWithPosition"
      end
    end
  end
end

module Internal
  module Message
    AccountOrdersCancellationCausedByLiquidation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountOrdersCancellationCausedByLiquidation").msgclass
    UpdateTradeStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UpdateTradeStatus").msgclass
    TradesWithPosition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TradesWithPosition").msgclass
    CalculationAccountOutput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CalculationAccountOutput").msgclass
  end
end
