# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/degen/degen_lucky_draw/server.proto for package 'Internal.DegenLuckyDraw'

require 'grpc'
require 'internal/degen/degen_lucky_draw/server_pb'

module Internal
  module DegenLuckyDraw
    module DegenLuckyDrawService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'DegenLuckyDrawService'

        rpc :ReloadLatestLuckyDrawInfo, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :TryCreateLuckyDrawInfo, ::Internal::DegenLuckyDraw::CreateLuckyDrawInfoRequest, ::Internal::DegenLuckyDraw::CreateLuckyDrawInfoResponse
        rpc :CreateLuckyDrawInfo, ::Internal::DegenLuckyDraw::CreateLuckyDrawInfoRequest, ::Internal::DegenLuckyDraw::CreateLuckyDrawInfoResponse
        rpc :TryForceCreateLuckyDrawInfo, ::Internal::DegenLuckyDraw::ForceCreateLuckyDrawInfoRequest, ::Internal::DegenLuckyDraw::ForceCreateLuckyDrawInfoResponse
        rpc :ForceCreateLuckyDrawInfo, ::Internal::DegenLuckyDraw::ForceCreateLuckyDrawInfoRequest, ::Internal::DegenLuckyDraw::ForceCreateLuckyDrawInfoResponse
        rpc :GetActiveLuckyDrawPublicInfo, ::Internal::DegenLuckyDraw::GetLuckyDrawPublicInfoRequest, ::Internal::DegenLuckyDraw::GetLuckyDrawPublicInfoResponse
        rpc :GetActiveLuckyDrawPrivateInfo, ::Internal::DegenLuckyDraw::GetLuckyDrawPrivateInfoRequest, ::Internal::DegenLuckyDraw::GetLuckyDrawPrivateInfoResponse
        rpc :PostLuckyDrawRecord, ::Internal::DegenLuckyDraw::PostLuckyDrawRecordRequest, ::Internal::DegenLuckyDraw::PostLuckyDrawRecordResponse
        rpc :PostLuckyDrawRecords, ::Internal::DegenLuckyDraw::PostLuckyDrawRecordsRequest, ::Internal::DegenLuckyDraw::PostLuckyDrawRecordsResponse
        rpc :GetNextEpochLuckyDrawInfo, ::Internal::DegenLuckyDraw::GetNextEpochLuckyDrawInfoRequest, ::Internal::DegenLuckyDraw::GetNextEpochLuckyDrawInfoResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
