# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/degen/degen_lucky_draw/server.proto

require 'google/protobuf'


require 'google/protobuf/empty_pb'
require 'internal/ext/address_pb'
require 'internal/types/degen_lucky_draw_pb'
require 'internal/decimal/decimal_pb'
require 'internal/types/error_code_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/degen/degen_lucky_draw/server.proto", :syntax => :proto3) do
    add_message "CreateLuckyDrawInfoRequest" do
      optional :EpochID, :int64, 1
      optional :StartCountingTime, :int64, 2
      optional :EndCountingTime, :int64, 3
      optional :StartLotteryTime, :int64, 4
      optional :EndLotteryTime, :int64, 5
      optional :PrizeRate, :int32, 6
      optional :PreChanceAmount, :message, 7, "DecimalMessage"
    end
    add_message "CreateLuckyDrawInfoResponse" do
      optional :Info, :message, 1, "DegenLuckyDrawInfo"
    end
    add_message "ForceCreateLuckyDrawInfoRequest" do
      optional :CreateLuckyDrawInfoRequest, :message, 1, "CreateLuckyDrawInfoRequest"
      optional :TransferTradingFee, :message, 2, "DecimalMessage"
      optional :TransferLiquidationFee, :message, 3, "DecimalMessage"
      optional :TransferSystemPNL, :message, 4, "DecimalMessage"
      optional :F1, :int32, 5
      optional :F2, :int32, 6
      optional :F3, :int32, 7
      optional :F4, :int32, 8
    end
    add_message "ForceCreateLuckyDrawInfoResponse" do
      optional :Info, :message, 1, "DegenLuckyDrawInfo"
    end
    add_message "GetLuckyDrawPublicInfoRequest" do
    end
    add_message "GetLuckyDrawPublicInfoResponse" do
      optional :Info, :message, 1, "DegenLuckyDrawInfo"
    end
    add_message "GetLuckyDrawPrivateInfoRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "GetLuckyDrawPrivateInfoResponse" do
      optional :PrivateInfo, :message, 1, "DegenLuckyDrawPrivateInfo"
    end
    add_message "PostLuckyDrawRecordRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "PostLuckyDrawRecordResponse" do
      optional :LuckyDrawLotteryRecord, :message, 1, "DegenLuckyDrawLotteryRecord"
      optional :ErrorCode, :enum, 2, "ERROR_CODE"
    end
    add_message "PostLuckyDrawRecordsRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Count, :int32, 2
    end
    add_message "PostLuckyDrawRecordsResponse" do
      repeated :LuckyDrawLotteryRecords, :message, 1, "DegenLuckyDrawLotteryRecord"
      optional :ErrorCode, :enum, 2, "ERROR_CODE"
    end
    add_message "GetNextEpochLuckyDrawInfoRequest" do
    end
    add_message "GetNextEpochLuckyDrawInfoResponse" do
      optional :Info, :message, 1, "DegenLuckyDrawInfo"
    end
  end
end

module Internal
  module DegenLuckyDraw
    CreateLuckyDrawInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateLuckyDrawInfoRequest").msgclass
    CreateLuckyDrawInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateLuckyDrawInfoResponse").msgclass
    ForceCreateLuckyDrawInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ForceCreateLuckyDrawInfoRequest").msgclass
    ForceCreateLuckyDrawInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ForceCreateLuckyDrawInfoResponse").msgclass
    GetLuckyDrawPublicInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetLuckyDrawPublicInfoRequest").msgclass
    GetLuckyDrawPublicInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetLuckyDrawPublicInfoResponse").msgclass
    GetLuckyDrawPrivateInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetLuckyDrawPrivateInfoRequest").msgclass
    GetLuckyDrawPrivateInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetLuckyDrawPrivateInfoResponse").msgclass
    PostLuckyDrawRecordRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PostLuckyDrawRecordRequest").msgclass
    PostLuckyDrawRecordResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PostLuckyDrawRecordResponse").msgclass
    PostLuckyDrawRecordsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PostLuckyDrawRecordsRequest").msgclass
    PostLuckyDrawRecordsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PostLuckyDrawRecordsResponse").msgclass
    GetNextEpochLuckyDrawInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetNextEpochLuckyDrawInfoRequest").msgclass
    GetNextEpochLuckyDrawInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetNextEpochLuckyDrawInfoResponse").msgclass
  end
end
