# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/fundingrate_arbitrage/server.proto

require 'google/protobuf'


require 'internal/order/constructor_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'
require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/fundingrate_arbitrage/server.proto", :syntax => :proto3) do
    add_message "CollateralState" do
      optional :Token, :message, 1, "AddressMessage"
      optional :Balance, :message, 2, "DecimalMessage"
      optional :Price, :message, 3, "DecimalMessage"
      optional :TokenName, :string, 4
    end
    add_message "GetBaseInfoRequest" do
      optional :Source, :string, 1
    end
    add_message "FundingRateArbitrageBaseInfoMessage" do
      optional :Contract, :message, 1, "AddressMessage"
      optional :USDCWalletBalance, :message, 2, "DecimalMessage"
      optional :USDCPerpBalance, :message, 3, "DecimalMessage"
      optional :JUSDPerpBalance, :message, 4, "DecimalMessage"
      optional :PositionPerpAmount, :message, 8, "DecimalMessage"
      optional :PositionCreditAmount, :message, 9, "DecimalMessage"
      optional :EarnUSDCRate, :message, 10, "DecimalMessage"
      optional :EarnUSDCTotalSupply, :message, 11, "DecimalMessage"
      optional :TotalWithdrawUSDCAmount, :message, 15, "DecimalMessage"
      optional :TotalWithdrawUSDCAmountToBeExpiredIn6Hours, :message, 16, "DecimalMessage"
      optional :TotalWithdrawUSDCAmountToBeExpiredIn12Hours, :message, 17, "DecimalMessage"
      optional :PerpNetValue, :message, 19, "DecimalMessage"
      repeated :CollateralStates, :message, 20, "CollateralState"
      optional :OperatorJusdBalance, :message, 21, "DecimalMessage"
      optional :EquivalentWETHBalance, :message, 22, "DecimalMessage"
      optional :LatestAverageEarnUSDCRate, :message, 23, "DecimalMessage"
    end
    add_message "TradeRequest" do
      optional :NewOrderRequest, :message, 1, "NewOrderRequest"
      optional :Memo, :string, 2
      optional :Operator, :string, 3
      optional :BatchNumber, :string, 4
    end
    add_message "SwapRequest" do
      optional :Memo, :string, 1
      optional :Operator, :string, 2
      optional :Amount, :message, 3, "DecimalMessage"
      optional :Side, :string, 4
      optional :MinReceivedAmount, :message, 5, "DecimalMessage"
      optional :BatchNumber, :string, 6
      optional :TokenName, :string, 7
    end
    add_message "TradeResponse" do
      optional :OrderID, :int64, 1
      optional :Operator, :string, 3
    end
    add_message "MovePrimaryAssetRequest" do
      optional :PrimaryAmount, :message, 1, "DecimalMessage"
      optional :Memo, :string, 2
      optional :Operator, :string, 3
      optional :BatchNumber, :string, 4
    end
    add_message "DepositJusdRequest" do
      optional :Amount, :message, 1, "DecimalMessage"
      optional :Memo, :string, 2
      optional :Operator, :string, 3
      optional :BatchNumber, :string, 4
    end
    add_message "WithdrawJusdRequest" do
      optional :Amount, :message, 1, "DecimalMessage"
      optional :Memo, :string, 2
      optional :Operator, :string, 3
      optional :BatchNumber, :string, 4
    end
    add_message "ExecuteWithdrawalsRequest" do
      repeated :IDs, :uint64, 1
      optional :Operator, :string, 3
    end
    add_message "GetSwapQuotationRequest" do
      optional :Amount, :message, 1, "DecimalMessage"
      optional :Side, :string, 2
      optional :TokenName, :string, 3
    end
    add_message "GetSwapQuotationResponse" do
      optional :Brand, :string, 1
      optional :Amount, :message, 2, "DecimalMessage"
      optional :Price, :message, 3, "DecimalMessage"
      optional :Side, :string, 4
      optional :Slippage, :message, 5, "DecimalMessage"
    end
    add_message "GetCollateralTokenNamesResponse" do
      repeated :TokenNames, :string, 1
    end
  end
end

module Internal
  module FundingRateArbitrage
    CollateralState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CollateralState").msgclass
    GetBaseInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetBaseInfoRequest").msgclass
    FundingRateArbitrageBaseInfoMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageBaseInfoMessage").msgclass
    TradeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TradeRequest").msgclass
    SwapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SwapRequest").msgclass
    TradeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TradeResponse").msgclass
    MovePrimaryAssetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MovePrimaryAssetRequest").msgclass
    DepositJusdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DepositJusdRequest").msgclass
    WithdrawJusdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WithdrawJusdRequest").msgclass
    ExecuteWithdrawalsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ExecuteWithdrawalsRequest").msgclass
    GetSwapQuotationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSwapQuotationRequest").msgclass
    GetSwapQuotationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSwapQuotationResponse").msgclass
    GetCollateralTokenNamesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetCollateralTokenNamesResponse").msgclass
  end
end
