# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/fundingrate_arbitrage/server.proto for package 'Internal.FundingRateArbitrage'

require 'grpc'
require 'internal/fundingrate_arbitrage/server_pb'

module Internal
  module FundingRateArbitrage
    module FundingRateArbitrageService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'FundingRateArbitrageService'

        rpc :GetBaseInfo, ::Internal::FundingRateArbitrage::GetBaseInfoRequest, ::Internal::FundingRateArbitrage::FundingRateArbitrageBaseInfoMessage
        rpc :GetSwapQuotation, ::Internal::FundingRateArbitrage::GetSwapQuotationRequest, ::Internal::FundingRateArbitrage::GetSwapQuotationResponse
        # Perp这边的单独操作，单独的加减仓位
        rpc :PerpTrade, ::Internal::FundingRateArbitrage::TradeRequest, ::Internal::FundingRateArbitrage::TradeResponse
        # Bank这边单独的操作，wETH和USDC的兑换
        rpc :SpotSwap, ::Internal::FundingRateArbitrage::SwapRequest, ::Google::Protobuf::Empty
        # 提取USDC，例如提取做空的利润
        rpc :WithdrawUSDC, ::Internal::FundingRateArbitrage::MovePrimaryAssetRequest, ::Google::Protobuf::Empty
        # 充值USDC，例如支付空单的损失
        rpc :DepositUSDC, ::Internal::FundingRateArbitrage::MovePrimaryAssetRequest, ::Google::Protobuf::Empty
        # 充JUSD
        rpc :DepositJUSD, ::Internal::FundingRateArbitrage::DepositJusdRequest, ::Google::Protobuf::Empty
        # 提JUSD
        rpc :WithdrawJUSD, ::Internal::FundingRateArbitrage::WithdrawJusdRequest, ::Google::Protobuf::Empty
        # 批准提款
        rpc :ExecuteWithdrawals, ::Internal::FundingRateArbitrage::ExecuteWithdrawalsRequest, ::Google::Protobuf::Empty
        rpc :GetCollateralTokenNames, ::Google::Protobuf::Empty, ::Internal::FundingRateArbitrage::GetCollateralTokenNamesResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
