# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/decimal/decimal.proto

require 'google/protobuf'



Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/decimal/decimal.proto", :syntax => :proto3) do
    add_message "DecimalMessage" do
      optional :Value, :string, 1
    end
  end
end

module Internal
  module Decimal
    DecimalMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DecimalMessage").msgclass
  end
end
