# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/jojo_trader/server.proto for package 'jojo_trader'

require 'grpc'
require 'internal/jojo_trader/server_pb'

module JojoTrader
  module JOJOTraderService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'jojo_trader.JOJOTraderService'

      rpc :SwapTrade, ::JojoTrader::SwapRequest, ::JojoTrader::SwapResponse
    end

    Stub = Service.rpc_stub_class
  end
end
