# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/jojo_trader/server.proto

require 'google/protobuf'


require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/jojo_trader/server.proto", :syntax => :proto3) do
    add_message "jojo_trader.SwapRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Amount, :message, 2, "DecimalMessage"
      optional :TradeType, :string, 3
    end
    add_message "jojo_trader.SwapResponse" do
      optional :Success, :bool, 1
      optional :Error, :string, 2
      optional :TxHash, :string, 3
    end
  end
end

module JojoTrader
  SwapRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jojo_trader.SwapRequest").msgclass
  SwapResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("jojo_trader.SwapResponse").msgclass
end
