# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/operator/server.proto

require 'google/protobuf'


require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/operator/server.proto", :syntax => :proto3) do
    add_message "SignOrderHashReq" do
      optional :OrderHash, :message, 1, "HashMessage"
    end
    add_message "SignOrderHashRes" do
      optional :Signature, :bytes, 1
    end
  end
end

module Internal
  module Operator
    SignOrderHashReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SignOrderHashReq").msgclass
    SignOrderHashRes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SignOrderHashRes").msgclass
  end
end
