# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/operator/server.proto for package 'Internal.Operator'

require 'grpc'
require 'internal/operator/server_pb'

module Internal
  module Operator
    module GlobalOperatorSignService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'GlobalOperatorSignService'

        rpc :SignOrderHash, ::Internal::Operator::SignOrderHashReq, ::Internal::Operator::SignOrderHashRes
      end

      Stub = Service.rpc_stub_class
    end
  end
end
