# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/account_operator/server.proto for package 'Internal.Account_operator'

require 'grpc'
require 'internal/account_operator/server_pb'

module Internal
  module AccountOperator
    module AccountOperatorService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'AccountOperatorService'

        # global operator related
        rpc :IsAccountGlobalOperatorEnabled, ::Internal::AccountOperator::IsAccountGlobalOperatorEnabledRequest, ::Internal::AccountOperator::IsAccountGlobalOperatorEnabledResponse
        rpc :WatchGlobalOperatorEnabledStatus, ::Google::Protobuf::Empty, stream(::Internal::AccountOperator::AccountGlobalOperatorEnabledChangeResponse)
        rpc :IsAccountHasOperator, ::Internal::AccountOperator::IsAccountHasOperatorRequest, ::Internal::AccountOperator::IsAccountHasOperatorResponse
        # subaccount related
        rpc :GetAccountAuthorizedOperators, ::Internal::AccountOperator::GetAccountAuthorizedOperatorsRequest, ::Internal::AccountOperator::GetAccountAuthorizedOperatorsResponse
        rpc :IsAccountAuthorizedOperator, ::Internal::AccountOperator::IsAccountAuthorizedOperatorRequest, ::Internal::AccountOperator::IsAccountAuthorizedOperatorResponse
        rpc :IsSubaccountOwner, ::Internal::AccountOperator::IsSubaccountOwnerRequest, ::Internal::AccountOperator::IsSubaccountOwnerResponse
        rpc :GetAccountOwner, ::Internal::AccountOperator::GetAccountOwnerRequest, ::Internal::AccountOperator::GetAccountOwnerResponse
        rpc :GetMainAccountOwnerOfAccount, ::Internal::AccountOperator::GetMainAccountOwnerOfAccountRequest, ::Internal::AccountOperator::GetMainAccountOwnerOfAccountResponse
        rpc :IsBotSubaccountOwner, ::Internal::AccountOperator::IsBotSubaccountOwnerRequest, ::Internal::AccountOperator::IsBotSubaccountOwnerResponse
        rpc :IsBotSubaccount, ::Internal::AccountOperator::IsBotSubaccountRequest, ::Internal::AccountOperator::IsBotSubaccountResponse
        rpc :GetBotSubaccounts, ::Internal::AccountOperator::GetBotSubaccountsRequest, ::Internal::AccountOperator::GetBotSubaccountsResponse
        rpc :GetSubaccounts, ::Internal::AccountOperator::GetSubaccountsRequest, ::Internal::AccountOperator::GetSubaccountsResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
