# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/account_operator/server.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/account_operator/server.proto", :syntax => :proto3) do
    add_message "IsAccountGlobalOperatorEnabledRequest" do
      optional :Address, :message, 1, "AddressMessage"
    end
    add_message "IsAccountGlobalOperatorEnabledResponse" do
      optional :Enabled, :bool, 1
    end
    add_message "AccountGlobalOperatorEnabledChangeResponse" do
      optional :Address, :message, 1, "AddressMessage"
      optional :Enabled, :bool, 2
    end
    add_message "IsAccountHasOperatorRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Operator, :message, 2, "AddressMessage"
    end
    add_message "GetAccountAuthorizedOperatorsRequest" do
      optional :Address, :message, 1, "AddressMessage"
    end
    add_message "GetAccountAuthorizedOperatorsResponse" do
      repeated :AuthorizedOperators, :message, 1, "AddressMessage"
    end
    add_message "IsAccountHasOperatorResponse" do
      optional :HasOperator, :bool, 1
    end
    add_message "IsAccountAuthorizedOperatorRequest" do
      optional :Address, :message, 1, "AddressMessage"
      optional :AuthorizedOperator, :message, 2, "AddressMessage"
      optional :RequestFrom, :string, 3
    end
    add_message "IsAccountAuthorizedOperatorResponse" do
      optional :OK, :bool, 1
    end
    add_message "IsSubaccountOwnerRequest" do
      optional :Address, :message, 1, "AddressMessage"
      optional :Owner, :message, 2, "AddressMessage"
    end
    add_message "IsSubaccountOwnerResponse" do
      optional :OK, :bool, 1
    end
    add_message "GetAccountOwnerRequest" do
      optional :Address, :message, 1, "AddressMessage"
    end
    add_message "GetAccountOwnerResponse" do
      optional :Owner, :message, 1, "AddressMessage"
    end
    add_message "IsBotSubaccountOwnerRequest" do
      optional :Address, :message, 1, "AddressMessage"
      optional :Owner, :message, 2, "AddressMessage"
      optional :BotType, :string, 3
    end
    add_message "GetBotSubaccountsRequest" do
      optional :Address, :message, 1, "AddressMessage"
      optional :BotAccountType, :string, 2
    end
    add_message "GetBotSubaccountsResponse" do
      repeated :BotSubaccounts, :message, 1, "AddressMessage"
    end
    add_message "GetSubaccountsRequest" do
      optional :Address, :message, 1, "AddressMessage"
    end
    add_message "GetSubaccountsResponse" do
      repeated :Subaccounts, :message, 1, "AddressMessage"
    end
    add_message "IsBotSubaccountOwnerResponse" do
      optional :OK, :bool, 1
    end
    add_message "IsBotSubaccountRequest" do
      optional :Address, :message, 1, "AddressMessage"
      optional :BotAccountType, :string, 2
    end
    add_message "GetMainAccountOwnerOfAccountRequest" do
      optional :Address, :message, 1, "AddressMessage"
    end
    add_message "IsBotSubaccountResponse" do
      optional :IsBotSubaccount, :bool, 1
      optional :SubaccountType, :string, 2
    end
    add_message "GetMainAccountOwnerOfAccountResponse" do
      optional :Owner, :message, 1, "AddressMessage"
    end
  end
end

module Internal
  module Account_operator
    IsAccountGlobalOperatorEnabledRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsAccountGlobalOperatorEnabledRequest").msgclass
    IsAccountGlobalOperatorEnabledResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsAccountGlobalOperatorEnabledResponse").msgclass
    AccountGlobalOperatorEnabledChangeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountGlobalOperatorEnabledChangeResponse").msgclass
    IsAccountHasOperatorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsAccountHasOperatorRequest").msgclass
    GetAccountAuthorizedOperatorsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountAuthorizedOperatorsRequest").msgclass
    GetAccountAuthorizedOperatorsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountAuthorizedOperatorsResponse").msgclass
    IsAccountHasOperatorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsAccountHasOperatorResponse").msgclass
    IsAccountAuthorizedOperatorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsAccountAuthorizedOperatorRequest").msgclass
    IsAccountAuthorizedOperatorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsAccountAuthorizedOperatorResponse").msgclass
    IsSubaccountOwnerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsSubaccountOwnerRequest").msgclass
    IsSubaccountOwnerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsSubaccountOwnerResponse").msgclass
    GetAccountOwnerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountOwnerRequest").msgclass
    GetAccountOwnerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountOwnerResponse").msgclass
    IsBotSubaccountOwnerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsBotSubaccountOwnerRequest").msgclass
    GetBotSubaccountsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetBotSubaccountsRequest").msgclass
    GetBotSubaccountsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetBotSubaccountsResponse").msgclass
    GetSubaccountsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSubaccountsRequest").msgclass
    GetSubaccountsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSubaccountsResponse").msgclass
    IsBotSubaccountOwnerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsBotSubaccountOwnerResponse").msgclass
    IsBotSubaccountRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsBotSubaccountRequest").msgclass
    GetMainAccountOwnerOfAccountRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMainAccountOwnerOfAccountRequest").msgclass
    IsBotSubaccountResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsBotSubaccountResponse").msgclass
    GetMainAccountOwnerOfAccountResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMainAccountOwnerOfAccountResponse").msgclass
  end
end
