# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/slot_machine_draw/server.proto for package 'Internal.SlotMachineDrawActivityProcessor'

require 'grpc'
require 'internal/slot_machine_draw/server_pb'

module Internal
  module SlotMachineDrawActivityProcessor
    module SlotMachineDraw
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'SlotMachineDraw'

        rpc :GetSlotMachineDrawBrief, ::Internal::SlotMachineDrawActivityProcessor::GetSlotMachineDrawBriefRequest, ::Internal::SlotMachineDrawActivityProcessor::GetSlotMachineDrawBriefResponse
        rpc :StartLuckLottery, ::Internal::SlotMachineDrawActivityProcessor::StartLuckLotteryRequest, ::Internal::SlotMachineDrawActivityProcessor::StartLuckLotteryResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
