# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/slot_machine_draw/server.proto

require 'google/protobuf'


require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/slot_machine_draw/server.proto", :syntax => :proto3) do
    add_message "GetSlotMachineDrawBriefRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "LuckLotteryPrize" do
      optional :MaskedAccount, :string, 1
      repeated :LotteryTokens, :string, 2
      optional :LotteryPrize, :int64, 3
    end
    add_message "GetSlotMachineDrawBriefResponse" do
      optional :StartAt, :int64, 1
      optional :EndAt, :int64, 2
      optional :LotteryEndAt, :int64, 3
      optional :AvailableTicketsCount, :int64, 4
      repeated :LuckLotteryPrizes, :message, 5, "LuckLotteryPrize"
    end
    add_message "StartLuckLotteryRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "StartLuckLotteryResponse" do
      optional :ErrorCode, :string, 1
      repeated :LotteryTokens, :string, 2
      optional :LotteryPrize, :int64, 3
      optional :AvailableTicketsCount, :int64, 4
    end
    add_enum "SLOT_MACHINE_DRAW_ERROR_CODE" do
      value :NO_ERROR, 0
      value :NO_ACTIVITY_ERROR, 1
      value :ACTIVITY_END_ERROR, 2
      value :ACTIVITY_NO_TICKETS_ERROR, 3
    end
  end
end

module Internal
  module SlotMachineDrawActivityProcessor
    GetSlotMachineDrawBriefRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSlotMachineDrawBriefRequest").msgclass
    LuckLotteryPrize = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LuckLotteryPrize").msgclass
    GetSlotMachineDrawBriefResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetSlotMachineDrawBriefResponse").msgclass
    StartLuckLotteryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StartLuckLotteryRequest").msgclass
    StartLuckLotteryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StartLuckLotteryResponse").msgclass
    SLOT_MACHINE_DRAW_ERROR_CODE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SLOT_MACHINE_DRAW_ERROR_CODE").enummodule
  end
end
