# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/price/server.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/price/server.proto", :syntax => :proto3) do
    add_message "MarketPrices" do
      optional :MarketID, :string, 1
      optional :LastTradePrice, :message, 2, "DecimalMessage"
      optional :LastTradePriceUpdatedAt, :message, 3, "google.protobuf.Timestamp"
      optional :MarkPrice, :message, 6, "DecimalMessage"
      optional :MarkPriceUpdatedAt, :message, 7, "google.protobuf.Timestamp"
      optional :OffchainMarkPrice, :message, 8, "DecimalMessage"
      optional :OffchainMarkPriceUpdatedAt, :message, 9, "google.protobuf.Timestamp"
    end
    add_message "GetMarketPricesRequest" do
      optional :MarketID, :string, 1
    end
    add_message "GetMarketOrderbookRequest" do
      optional :MarketID, :string, 1
      optional :Limit, :int32, 2
    end
    add_message "OrderbookPriceLevel" do
      optional :Price, :message, 1, "DecimalMessage"
      optional :Amount, :message, 2, "DecimalMessage"
    end
    add_message "MarketOrderbookResponse" do
      repeated :Asks, :message, 1, "OrderbookPriceLevel"
      repeated :Bids, :message, 2, "OrderbookPriceLevel"
    end
  end
end

module Internal
  module Price
    MarketPrices = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MarketPrices").msgclass
    GetMarketPricesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMarketPricesRequest").msgclass
    GetMarketOrderbookRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMarketOrderbookRequest").msgclass
    OrderbookPriceLevel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderbookPriceLevel").msgclass
    MarketOrderbookResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MarketOrderbookResponse").msgclass
  end
end
