# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/price/server.proto for package 'Internal.Price'

require 'grpc'
require 'internal/price/server_pb'

module Internal
  module Price
    module PriceService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'PriceService'

        rpc :GetMarketPrices, ::Internal::Price::GetMarketPricesRequest, ::Internal::Price::MarketPrices
        rpc :WatchMarketPrices, ::Internal::Price::GetMarketPricesRequest, stream(::Internal::Price::MarketPrices)
        rpc :GetMarketOrderbook, ::Internal::Price::GetMarketOrderbookRequest, ::Internal::Price::MarketOrderbookResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
