# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/pre_launch_activity_processor/server.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/pre_launch_activity_processor/server.proto", :syntax => :proto3) do
    add_message "GetActivityBriefRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :RequestFrom, :string, 2
      optional :EpochNumber, :int64, 3
    end
    add_message "EpochActivity" do
      optional :StartAt, :int64, 1
      optional :EndAt, :int64, 2
      optional :TotalTokenCount, :int64, 3
      optional :TradeVolume, :message, 4, "DecimalMessage"
      optional :DailyAverageTVL, :message, 5, "DecimalMessage"
      optional :InviteeAccountCount, :int64, 6
      optional :RewardPoints, :message, 7, "DecimalMessage"
      optional :EpochNumber, :int64, 8
      optional :ActivityStatus, :string, 9
      optional :EventPoints, :message, 10, "DecimalMessage"
      optional :AssetsSnapshotExecuteCount, :int64, 11
      optional :RewardTokenRatio, :string, 12
      optional :AccountRole, :string, 13
      optional :Account, :message, 14, "AddressMessage"
      optional :TotalPoints, :message, 15, "DecimalMessage"
      optional :TotalTradeVolume, :message, 16, "DecimalMessage"
      optional :TotalDailyAverageTVL, :message, 17, "DecimalMessage"
      optional :PerpNetValue, :message, 18, "DecimalMessage"
      optional :DegenNetValue, :message, 19, "DecimalMessage"
    end
    add_message "GetActivityBriefResponse" do
      optional :StartAt, :int64, 1
      optional :EndAt, :int64, 2
      optional :CurrentEpochNumber, :int64, 3
      repeated :EpochActivities, :message, 4, "EpochActivity"
      optional :TotalRewardPoints, :message, 5, "DecimalMessage"
      optional :MerkleIndex, :int64, 6
      repeated :MerkleProof, :string, 7
      optional :IsClaimed, :bool, 8
    end
    add_message "ActivityStatus" do
      optional :AccountRole, :string, 2
      optional :TradeVolume, :message, 3, "DecimalMessage"
      optional :DailyAverageTVL, :message, 4, "DecimalMessage"
      optional :RewardPoints, :message, 5, "DecimalMessage"
      optional :RewardTokenRatio, :string, 6
      optional :EventPoints, :message, 7, "DecimalMessage"
    end
    add_message "EpochActivityStatus" do
      optional :EpochNumber, :int64, 1
      repeated :Activities, :message, 2, "ActivityStatus"
    end
    add_message "GetActivitySummaryStatsResponse" do
      repeated :EpochActivities, :message, 1, "EpochActivityStatus"
      optional :CurrentEpochNumber, :int64, 2
    end
    add_message "GetPreLaunchRanklingListRequest" do
      optional :AccountRole, :string, 1
      optional :AccountCount, :int64, 2
      optional :EpochNumber, :int64, 3
      optional :Account, :message, 4, "AddressMessage"
    end
    add_message "GetActivitySummaryStatsRequest" do
      optional :EpochNumber, :int64, 1
    end
    add_message "GetPreLaunchRanklingListResponse" do
      repeated :EpochActivities, :message, 1, "EpochActivity"
      optional :CurrentEpochNumber, :int64, 2
    end
  end
end

module Internal
  module PreLaunchActivityProcessor
    GetActivityBriefRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetActivityBriefRequest").msgclass
    EpochActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EpochActivity").msgclass
    GetActivityBriefResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetActivityBriefResponse").msgclass
    ActivityStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ActivityStatus").msgclass
    EpochActivityStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EpochActivityStatus").msgclass
    GetActivitySummaryStatsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetActivitySummaryStatsResponse").msgclass
    GetPreLaunchRanklingListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPreLaunchRanklingListRequest").msgclass
    GetActivitySummaryStatsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetActivitySummaryStatsRequest").msgclass
    GetPreLaunchRanklingListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPreLaunchRanklingListResponse").msgclass
  end
end
