# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/pre_launch_activity_processor/server.proto for package 'Internal.PreLaunchActivityProcessor'

require 'grpc'
require 'internal/pre_launch_activity_processor/server_pb'

module Internal
  module PreLaunchActivityProcessor
    module PreLaunchActivity
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'PreLaunchActivity'

        rpc :GetActivityBrief, ::Internal::PreLaunchActivityProcessor::GetActivityBriefRequest, ::Internal::PreLaunchActivityProcessor::GetActivityBriefResponse
        rpc :GetActivitySummaryStats, ::Internal::PreLaunchActivityProcessor::GetActivitySummaryStatsRequest, ::Internal::PreLaunchActivityProcessor::GetActivitySummaryStatsResponse
        rpc :GetPreLaunchRanklingList, ::Internal::PreLaunchActivityProcessor::GetPreLaunchRanklingListRequest, ::Internal::PreLaunchActivityProcessor::GetPreLaunchRanklingListResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
