# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/liquidation/server.proto for package 'Internal.Liquidation'

require 'grpc'
require 'internal/liquidation/server_pb'

module Internal
  module Liquidation
    module JusdLiquidationService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'JusdLiquidationService'

        rpc :ManuallyLiquidationPosition, ::Internal::Liquidation::ManuallyLiquidationPositionRequest, ::Internal::Liquidation::ManuallyLiquidationPositionResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
