# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/engine/server.proto for package 'Internal.Engine'

require 'grpc'
require 'internal/engine/server_pb'

module Internal
  module Engine
    module EngineService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'EngineService'

        rpc :Enqueue, ::Internal::Engine::OrderMessage, ::Internal::Types::OrderbookProcessResult
        rpc :QueryOrder, ::Internal::Engine::QueryOrderRequest, ::Internal::Engine::QueryOrderResponse
        rpc :GetSnapshot, ::Internal::Engine::GetOrderbookSnapshotRequest, ::Internal::Engine::GetOrderbookSnapshotResponse
        rpc :FlushAll, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :GetEngineState, ::Google::Protobuf::Empty, ::Internal::Engine::EngineStateResponse
        rpc :InsiderTrading, ::Internal::Engine::InsiderTradingRequest, ::Internal::Engine::InsiderTradingResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
