# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/engine/server.proto

require 'google/protobuf'


require 'internal/engine/types_pb'
require 'internal/types/engine_pb'
require 'internal/types/types_pb'
require 'internal/decimal/decimal_pb'
require 'google/protobuf/empty_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/engine/server.proto", :syntax => :proto3) do
    add_message "GetOrderbookSnapshotRequest" do
      optional :MarketID, :string, 1
    end
    add_message "GetOrderbookSnapshotResponse" do
      optional :Snapshot, :bytes, 1
    end
    add_message "QueryOrderRequest" do
      optional :MarketID, :string, 1
      optional :OrderID, :int64, 2
      optional :Side, :enum, 3, "SIDE"
      optional :Price, :message, 4, "DecimalMessage"
    end
    add_message "QueryOrderResponse" do
      optional :Order, :message, 1, "OrderInBook"
    end
    add_message "FlushAllCommand" do
    end
    add_message "SetMarketIndexCommand" do
      optional :MarketID, :string, 1
      optional :Index, :int64, 2
    end
    add_message "EngineFSMCommand" do
      oneof :Command do
        optional :OrderCommand, :message, 1, "OrderMessage"
        optional :FlushAllCommand, :message, 2, "FlushAllCommand"
        optional :SetMarketIndexCommand, :message, 3, "SetMarketIndexCommand"
      end
    end
    add_message "EngineStateResponse" do
      optional :Host, :string, 1
      optional :IsLeader, :bool, 2
      repeated :MarketID, :string, 3
      repeated :EpochID, :int64, 4
    end
    add_message "InsiderTradingRequest" do
      optional :MarketID, :string, 1
      optional :Volume, :message, 2, "DecimalMessage"
      optional :MakerSide, :enum, 3, "SIDE"
      optional :MakerAccount, :message, 4, "AddressMessage"
      optional :TakerAccount, :message, 5, "AddressMessage"
      optional :TickSize, :message, 6, "DecimalMessage"
      optional :StepSize, :message, 7, "DecimalMessage"
      optional :MaxSpreadRate, :message, 9, "DecimalMessage"
      optional :MinVolumeByPriceRange, :message, 11, "DecimalMessage"
      optional :MinMinuteOrderCount, :int32, 12
      optional :Leverage, :message, 13, "AddressMessage"
      optional :Amount, :message, 14, "AddressMessage"
    end
    add_message "InsiderTradingResponse" do
      optional :Ok, :bool, 1
      optional :ErrorInfo, :string, 2
    end
  end
end

module Internal
  module Engine
    GetOrderbookSnapshotRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetOrderbookSnapshotRequest").msgclass
    GetOrderbookSnapshotResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetOrderbookSnapshotResponse").msgclass
    QueryOrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QueryOrderRequest").msgclass
    QueryOrderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QueryOrderResponse").msgclass
    FlushAllCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FlushAllCommand").msgclass
    SetMarketIndexCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SetMarketIndexCommand").msgclass
    EngineFSMCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EngineFSMCommand").msgclass
    EngineStateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EngineStateResponse").msgclass
    InsiderTradingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InsiderTradingRequest").msgclass
    InsiderTradingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InsiderTradingResponse").msgclass
  end
end
