# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/engine/types.proto

require 'google/protobuf'


require 'internal/types/engine_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/engine/types.proto", :syntax => :proto3) do
    add_message "OrderbookMap" do
      map :Orderbooks, :string, :message, 1, "Orderbook"
    end
    add_message "BranchMessage" do
      optional :Data, :string, 1
    end
    add_message "Orderbook" do
      optional :Sequence, :uint64, 1
      optional :BidBranch, :message, 2, "BranchMessage"
      optional :AskBranch, :message, 3, "BranchMessage"
      optional :MarketIndex, :int64, 4
      optional :OrderEnqueueTs, :int64, 5
    end
    add_message "OrderMessage" do
      optional :Type, :enum, 1, "EnqueueType"
      optional :MarketID, :string, 2
      optional :Order, :message, 3, "EngineOrder"
    end
    add_message "PriceAndAmount" do
      optional :Price, :message, 1, "DecimalMessage"
      optional :Amount, :message, 2, "DecimalMessage"
    end
    add_message "Depth" do
      optional :MarketID, :string, 1
      optional :Sequence, :uint64, 2
      optional :DepthType, :enum, 3, "DepthType"
      repeated :Bids, :message, 4, "PriceAndAmount"
      repeated :Asks, :message, 5, "PriceAndAmount"
      optional :OrderEnqueueTs, :int64, 6
    end
    add_enum "DepthType" do
      value :FULL, 0
      value :WEB200, 1
      value :API50, 2
      value :API200, 3
    end
  end
end

module Internal
  module Engine
    OrderbookMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderbookMap").msgclass
    BranchMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BranchMessage").msgclass
    Orderbook = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Orderbook").msgclass
    OrderMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderMessage").msgclass
    PriceAndAmount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PriceAndAmount").msgclass
    Depth = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Depth").msgclass
    DepthType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DepthType").enummodule
  end
end
