# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/united_market_cacher/server.proto for package 'Internal.UnitedMarketCacheService'

require 'grpc'
require 'internal/united_market_cacher/server_pb'

module Internal
  module UnitedMarketCacheService
    module UnitedMarketCacheService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'UnitedMarketCacheService'

        rpc :GetMarketStatus, ::Internal::UnitedMarketCacheService::GetMarketStatusRequest, ::Internal::Types::UnitedMarket
        rpc :GetAllMarketStatus, ::Internal::UnitedMarketCacheService::GetAllMarketStatusRequest, ::Internal::UnitedMarketCacheService::GetAllMarketStatusResponse
        rpc :WatchAllMarketStatus, ::Internal::UnitedMarketCacheService::GetAllMarketStatusRequest, stream(::Internal::Types::UnitedMarket)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
