# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/liquidity_bot/server.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/liquidity_bot/server.proto", :syntax => :proto3) do
    add_message "PlaceBinanceRevertOrderRequest" do
      optional :JoJoTradeID, :int64, 1
    end
    add_message "PlaceBinanceRevertOrderResponse" do
      optional :OK, :bool, 1
      optional :ErrorMsg, :string, 2
    end
  end
end

module Internal
  module LiquidityBot
    PlaceBinanceRevertOrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PlaceBinanceRevertOrderRequest").msgclass
    PlaceBinanceRevertOrderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PlaceBinanceRevertOrderResponse").msgclass
  end
end
