# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/liquidity_bot/server.proto for package 'Internal.LiquidityBot'

require 'grpc'
require 'internal/liquidity_bot/server_pb'

module Internal
  module LiquidityBot
    module LiquidityBotService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'LiquidityBotService'

        rpc :PlaceBinanceRevertOrder, ::Internal::LiquidityBot::PlaceBinanceRevertOrderRequest, ::Internal::LiquidityBot::PlaceBinanceRevertOrderResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
