# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/slack_integrations/incoming_webhook.proto for package 'Internal.SlackIntegrations'

require 'grpc'
require 'internal/slack_integrations/incoming_webhook_pb'

module Internal
  module SlackIntegrations
    module IncomingWebhookService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'IncomingWebhookService'

        rpc :SendMessage, ::Internal::SlackIntegrations::SendMessageRequest, ::Internal::SlackIntegrations::SendMessageResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
