# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/slack_integrations/incoming_webhook.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/slack_integrations/incoming_webhook.proto", :syntax => :proto3) do
    add_message "SendMessageRequest" do
      optional :Name, :string, 1
      optional :Body, :string, 2
    end
    add_message "SendMessageResponse" do
    end
  end
end

module Internal
  module SlackIntegrations
    SendMessageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendMessageRequest").msgclass
    SendMessageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendMessageResponse").msgclass
  end
end
