# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/kline/server.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/kline/server.proto", :syntax => :proto3) do
    add_message "QueryRequest" do
      optional :MarketID, :string, 1
      optional :Interval, :enum, 2, "Interval"
      optional :StartTime, :message, 3, "google.protobuf.Timestamp"
      optional :EndTime, :message, 4, "google.protobuf.Timestamp"
      optional :Limit, :int32, 5
      optional :PriceType, :enum, 6, "PriceType"
    end
    add_message "Candle" do
      optional :StartTime, :message, 1, "google.protobuf.Timestamp"
      optional :Open, :message, 2, "DecimalMessage"
      optional :Close, :message, 3, "DecimalMessage"
      optional :High, :message, 4, "DecimalMessage"
      optional :Low, :message, 5, "DecimalMessage"
      optional :Volume, :message, 6, "DecimalMessage"
    end
    add_message "QueryResponse" do
      optional :MarketID, :string, 1
      optional :Interval, :enum, 2, "Interval"
      repeated :Candles, :message, 3, "Candle"
    end
    add_message "WatchRequest" do
      optional :MarketID, :string, 1
      optional :Interval, :enum, 2, "Interval"
    end
    add_message "WatchResponse" do
      optional :MarketID, :string, 1
      optional :Interval, :enum, 2, "Interval"
      repeated :Candles, :message, 3, "Candle"
    end
    add_message "GetKlineMarketStatusRequest" do
      optional :MarketID, :string, 1
    end
    add_message "GetMarketStatusResponse" do
      optional :Volume24h, :message, 1, "DecimalMessage"
      optional :QuoteVolume24h, :message, 2, "DecimalMessage"
      optional :Price24hAgo, :message, 3, "DecimalMessage"
      optional :TotalHistoricalQuoteVolume, :message, 4, "DecimalMessage"
    end
    add_enum "Interval" do
      value :I1M, 0
      value :I5M, 1
      value :I15M, 2
      value :I30M, 3
      value :I1H, 4
      value :I2H, 5
      value :I4H, 6
      value :I6H, 7
      value :I1D, 8
      value :I1W, 9
      value :I1MO, 10
    end
    add_enum "PriceType" do
      value :TradePrice, 0
      value :MarkPrice, 1
      value :IndexPrice, 2
    end
  end
end

module Internal
  module Kline
    QueryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QueryRequest").msgclass
    Candle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Candle").msgclass
    QueryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QueryResponse").msgclass
    WatchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WatchRequest").msgclass
    WatchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WatchResponse").msgclass
    GetKlineMarketStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetKlineMarketStatusRequest").msgclass
    GetMarketStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMarketStatusResponse").msgclass
    Interval = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Interval").enummodule
    PriceType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PriceType").enummodule
  end
end
