# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/kline/server.proto for package 'Internal.Kline'

require 'grpc'
require 'internal/kline/server_pb'

module Internal
  module Kline
    module KLindeService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'KLindeService'

        rpc :Query, ::Internal::Kline::QueryRequest, ::Internal::Kline::QueryResponse
        # Return most recend 10 candles every 10s
        rpc :Watch, ::Internal::Kline::WatchRequest, stream(::Internal::Kline::WatchResponse)
        rpc :GetMarketStatus, ::Internal::Kline::GetKlineMarketStatusRequest, ::Internal::Kline::GetMarketStatusResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
