# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/isolated_margin_bot_assets_manager/server.proto for package 'Internal.IsolatedMarginBotAssetsManager'

require 'grpc'
require 'internal/isolated_margin_bot_assets_manager/server_pb'

module Internal
  module IsolatedMarginBotAssetsManager
    module IsolatedMarginBotService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'IsolatedMarginBotService'

        rpc :GetBotAccounts, ::Internal::IsolatedMarginBotAssetsManager::GetBotAccountsRequest, ::Internal::IsolatedMarginBotAssetsManager::GetBotAccountsResponse
        rpc :TransferBackAssets, ::Internal::IsolatedMarginBotAssetsManager::TransferBackAssetsRequest, ::Internal::IsolatedMarginBotAssetsManager::TransferBackAssetsResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
