# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/isolated_margin_bot_assets_manager/server.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/isolated_margin_bot_assets_manager/server.proto", :syntax => :proto3) do
    add_message "GetBotAccountsRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "BotAccount" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Status, :string, 2
    end
    add_message "GetBotAccountsResponse" do
      repeated :BotAccounts, :message, 1, "BotAccount"
    end
    add_message "TransferBackAssetsRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :BotAccount, :message, 2, "AddressMessage"
      optional :PrimaryCreditAmount, :message, 3, "DecimalMessage"
      optional :SecondaryCreditAmount, :message, 4, "DecimalMessage"
    end
    add_message "TransferBackAssetsResponse" do
      optional :ErrorMessage, :string, 1
    end
  end
end

module Internal
  module IsolatedMarginBotAssetsManager
    GetBotAccountsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetBotAccountsRequest").msgclass
    BotAccount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BotAccount").msgclass
    GetBotAccountsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetBotAccountsResponse").msgclass
    TransferBackAssetsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TransferBackAssetsRequest").msgclass
    TransferBackAssetsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TransferBackAssetsResponse").msgclass
  end
end
