# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/account_profile.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/ext/null_string_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/json_message_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/account_profile.proto", :syntax => :proto3) do
    add_message "RiskNotificationGears" do
      repeated :Gears, :int64, 1
    end
    add_message "AccountProfileExtraInfo" do
      optional :OrderRequestLimit, :int64, 1
      optional :Role, :string, 2
      optional :IsCustomizedMakerAndTakerFee, :bool, 3
      optional :MakerFeeRate, :message, 4, "DecimalMessage"
      optional :TakerFeeRate, :message, 5, "DecimalMessage"
      optional :InitialLeverageRate, :message, 6, "DecimalMessage"
      optional :IsGasFeeWaived, :bool, 7
    end
    add_message "AccountProfile" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Avatar, :string, 3
      optional :Nickname, :message, 4, "NullString"
      optional :Email, :string, 5
      optional :EmailVerifiedAt, :message, 6, "google.protobuf.Timestamp"
      optional :RiskNotificationGears, :message, 7, "RiskNotificationGears"
      optional :LiquidationNotificationEnable, :bool, 8
      optional :TpslOrderNotificationEnable, :bool, 9
      optional :GTTOrderExpiredNotificationEnable, :bool, 10
      optional :CollateralRiskNotificationGears, :message, 11, "RiskNotificationGears"
      optional :InitialLeverageRates, :message, 12, "JsonMessage"
      optional :GridOrderTerminationNotificationEnable, :bool, 13
      optional :FundingRateArbitrageNotificationEnable, :bool, 14
      optional :PerpOrderNotificationEnable, :bool, 15
      optional :DegenOrderNotificationEnable, :bool, 16
      optional :NewFeatureAndTerminologyNotificationEnable, :bool, 17
      optional :OrderFilledSoundNotificationEnable, :bool, 18
      optional :ExtraInfo, :message, 19, "AccountProfileExtraInfo"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
      optional :DiscardButtonDisable, :bool, 22
      optional :DefaultSlippage, :message, 23, "DecimalMessage"
      optional :StopLimitOrderNotificationEnable, :bool, 24
      optional :PriceAlertEmailNotificationEnable, :bool, 25
      optional :PriceAlertInAppNotificationEnable, :bool, 26
      optional :HasTrade, :bool, 27
      optional :AiChatShortcut, :string, 28
    end
  end
end

module Internal
  module Types
    RiskNotificationGears = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RiskNotificationGears").msgclass
    AccountProfileExtraInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountProfileExtraInfo").msgclass
    AccountProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountProfile").msgclass
  end
end
