# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/account.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/types/position_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/account.proto", :syntax => :proto3) do
    add_message "GetAccountListRequest" do
    end
    add_message "GetAccountListResponse" do
      repeated :Accounts, :message, 1, "AddressMessage"
    end
    add_message "AccountExtraInfo" do
      optional :InviterRebateRatio, :int64, 1
      optional :InviteeRebateRatio, :int64, 2
    end
    add_message "Account" do
      optional :ID, :int64, 1
      optional :Address, :message, 2, "AddressMessage"
      optional :InviterAddress, :message, 3, "AddressMessage"
      optional :AgreeAgreementAt, :message, 4, "google.protobuf.Timestamp"
      optional :Role, :string, 5
      optional :VipLevel, :int64, 6
      optional :ExtraInfo, :message, 19, "AccountExtraInfo"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "AccountMarketBalancesInContract" do
      optional :MarketID, :string, 1
      optional :PaperAmount, :message, 2, "DecimalMessage"
      optional :CreditAmount, :message, 3, "DecimalMessage"
      optional :LiquidatePrice, :message, 4, "DecimalMessage"
    end
    add_message "AccountMarketAvailableCreditAmounts" do
      optional :MarketID, :string, 1
      optional :BuyAvailable, :message, 2, "DecimalMessage"
      optional :SellAvailable, :message, 3, "DecimalMessage"
    end
    add_message "AccountBlockchainState" do
      optional :PrimaryCreditAmount, :message, 1, "DecimalMessage"
      optional :SecondaryCreditAmount, :message, 2, "DecimalMessage"
      optional :PendingWithdrawPrimaryAmount, :message, 3, "DecimalMessage"
      optional :PendingWithdrawSecondaryAmount, :message, 4, "DecimalMessage"
      optional :Account, :message, 5, "AddressMessage"
      repeated :Perpetuals, :message, 8, "AccountMarketBalancesInContract"
      optional :MaintenanceMarginAmount, :message, 11, "DecimalMessage"
      optional :Exposure, :message, 12, "DecimalMessage"
      optional :NetValue, :message, 13, "DecimalMessage"
      optional :IsSafe, :bool, 16
      optional :LastUpdatedBlockNumber, :int64, 17
      optional :LastUpdatedTime, :int64, 18
    end
    add_message "AccountState" do
      optional :BlockchainState, :message, 1, "AccountBlockchainState"
      repeated :availableCreditAmounts, :message, 2, "AccountMarketAvailableCreditAmounts"
      optional :FrozenMarginAmount, :message, 3, "DecimalMessage"
      optional :AvailableMarginAmount, :message, 5, "DecimalMessage"
      optional :PositionMarginAmount, :message, 6, "DecimalMessage"
      optional :Leverage, :message, 7, "DecimalMessage"
      optional :MarginRate, :message, 8, "DecimalMessage"
      repeated :Positions, :message, 9, "Position"
      optional :AvailableWithdrawAmount, :message, 12, "DecimalMessage"
    end
    add_message "AccountStates" do
      repeated :AccountStates, :message, 1, "AccountState"
    end
    add_message "AccountVisitRecord" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :VisitAirdropFarmAt, :message, 19, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    GetAccountListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountListRequest").msgclass
    GetAccountListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountListResponse").msgclass
    AccountExtraInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountExtraInfo").msgclass
    Account = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Account").msgclass
    AccountMarketBalancesInContract = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountMarketBalancesInContract").msgclass
    AccountMarketAvailableCreditAmounts = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountMarketAvailableCreditAmounts").msgclass
    AccountBlockchainState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountBlockchainState").msgclass
    AccountState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountState").msgclass
    AccountStates = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountStates").msgclass
    AccountVisitRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountVisitRecord").msgclass
  end
end
