# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/aggregate_trading_fee.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/aggregate_trading_fee.proto", :syntax => :proto3) do
    add_message "AggregateTradingFee" do
      optional :ID, :int64, 1
      optional :RecordAt, :message, 2, "google.protobuf.Timestamp"
      optional :TradeVolumeAnalysisLogID, :int64, 3
      optional :PerpTradingFee, :message, 4, "DecimalMessage"
      optional :DegenTradingFee, :message, 5, "DecimalMessage"
      optional :TotalTradingFee, :message, 6, "DecimalMessage"
    end
  end
end

module Internal
  module Types
    AggregateTradingFee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AggregateTradingFee").msgclass
  end
end
