# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/ai_chat_key.proto

require 'google/protobuf'


require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/ai_chat_key.proto", :syntax => :proto3) do
    add_message "AiChatKey" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :AiChatKey, :string, 3
    end
  end
end

module Internal
  module Types
    AiChatKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AiChatKey").msgclass
  end
end
