# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/airdrop_farm_activity.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/airdrop_farm_activity.proto", :syntax => :proto3) do
    add_message "AirdropFarmActivityConfig" do
      optional :ID, :int64, 1
      optional :TotalTokenCount, :message, 2, "DecimalMessage"
      optional :EpochTotalTokenCount, :message, 3, "DecimalMessage"
      optional :EachEpochDays, :int64, 4
      optional :TotalEpochNumber, :int64, 5
      optional :StartAt, :message, 6, "google.protobuf.Timestamp"
      optional :EndAt, :message, 7, "google.protobuf.Timestamp"
    end
    add_message "AirdropFarmActivity" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TaskName, :string, 3
      optional :Amount, :message, 4, "DecimalMessage"
      optional :EventPoints, :message, 5, "DecimalMessage"
      optional :EpochNumber, :int64, 6
      optional :LpUSDCAmount, :message, 7, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "AirdropFarmActivityAssociation" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TaskName, :string, 3
      optional :SourceID, :int64, 4
      optional :SourceType, :string, 5
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "AirdropFarmActivityAssetsSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :NetValue, :message, 3, "DecimalMessage"
      optional :RecordAt, :message, 8, "google.protobuf.Timestamp"
    end
    add_message "AirdropFarmActivityEpochPoints" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :EventPoints, :message, 3, "DecimalMessage"
      optional :Tokens, :message, 4, "DecimalMessage"
      optional :EpochNumber, :int64, 5
      optional :InviteeAccountCount, :int64, 6
      optional :VipLevel, :int64, 7
      optional :TradeVolume, :message, 8, "DecimalMessage"
      optional :DailyAverageTVL, :message, 9, "DecimalMessage"
      optional :DailyCommittedLP, :message, 10, "DecimalMessage"
      optional :RecordAt, :message, 19, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "AirdropFarmTeam" do
      optional :ID, :int64, 1
      optional :Captain, :message, 2, "AddressMessage"
      optional :TeamType, :string, 3
      optional :Name, :string, 4
      optional :Code, :string, 5
      optional :Link, :string, 6
      optional :TradersCount, :int64, 7
      optional :TeamPoints, :message, 8, "DecimalMessage"
      optional :Ranking, :int64, 9
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "AirdropFarmTeamMember" do
      optional :ID, :int64, 1
      optional :AirdropFarmTeamID, :int64, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :PointsIncreaseRatio, :message, 8, "DecimalMessage"
      optional :Status, :string, 9
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "AirdropFarmCommittedLPSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :CommittedLPAmount, :message, 3, "DecimalMessage"
      optional :StakeLPAmount, :message, 4, "DecimalMessage"
      optional :RecordAt, :message, 19, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "JOJOPriceSnapshot" do
      optional :ID, :int64, 1
      optional :Price, :message, 2, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "AirdropFarmActivityClaimLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Amount, :message, 3, "DecimalMessage"
      optional :MerkleTreeIndex, :int64, 4
      optional :MerkleTreeProof, :string, 5
      optional :ClaimedAt, :message, 6, "google.protobuf.Timestamp"
      optional :TxHash, :message, 7, "HashMessage"
      optional :BlockHash, :message, 8, "HashMessage"
      optional :BlockNumber, :int64, 9
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    AirdropFarmActivityConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AirdropFarmActivityConfig").msgclass
    AirdropFarmActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AirdropFarmActivity").msgclass
    AirdropFarmActivityAssociation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AirdropFarmActivityAssociation").msgclass
    AirdropFarmActivityAssetsSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AirdropFarmActivityAssetsSnapshot").msgclass
    AirdropFarmActivityEpochPoints = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AirdropFarmActivityEpochPoints").msgclass
    AirdropFarmTeam = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AirdropFarmTeam").msgclass
    AirdropFarmTeamMember = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AirdropFarmTeamMember").msgclass
    AirdropFarmCommittedLPSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AirdropFarmCommittedLPSnapshot").msgclass
    JOJOPriceSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JOJOPriceSnapshot").msgclass
    AirdropFarmActivityClaimLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AirdropFarmActivityClaimLog").msgclass
  end
end
