# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/app_version.proto

require 'google/protobuf'



Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/app_version.proto", :syntax => :proto3) do
    add_message "AppVersion" do
      optional :ID, :int64, 1
      optional :VersionNumber, :string, 2
      optional :VersionDesc, :string, 3
      optional :ForceRefresh, :bool, 4
    end
  end
end

module Internal
  module Types
    AppVersion = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AppVersion").msgclass
  end
end
