# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/arb_activity.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/json_message_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/arb_activity.proto", :syntax => :proto3) do
    add_message "ArbActivityConfig" do
      optional :ID, :int64, 1
      optional :ActivityName, :string, 2
      optional :TotalArbCount, :message, 3, "DecimalMessage"
      optional :RemainingArbCount, :message, 4, "DecimalMessage"
      optional :EpochTotalArbCount, :message, 5, "DecimalMessage"
      optional :EachEpochDays, :int64, 6
      optional :MarketsEpochArbCount, :message, 7, "JsonMessage"
      optional :TotalEpochNumber, :int64, 8
      optional :StartAt, :message, 19, "google.protobuf.Timestamp"
      optional :EndAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "ArbActivity" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TaskName, :string, 3
      optional :Amount, :message, 4, "DecimalMessage"
      optional :EstimatedPoints, :message, 5, "DecimalMessage"
      optional :WaitingToClaimedPoints, :message, 6, "DecimalMessage"
      optional :EpochNumber, :int64, 7
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "ArbActivityAssociation" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TaskName, :string, 3
      optional :EpochNumber, :int64, 5
      optional :SourceID, :int64, 6
      optional :SourceType, :string, 7
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "ArbActivityClaimLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Amount, :message, 3, "DecimalMessage"
      optional :MerkleTreeIndex, :int64, 4
      optional :MerkleTreeProof, :string, 5
      optional :ClaimedAt, :message, 6, "google.protobuf.Timestamp"
      optional :TxHash, :message, 7, "HashMessage"
      optional :BlockHash, :message, 8, "HashMessage"
      optional :BlockNumber, :int64, 9
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    ArbActivityConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ArbActivityConfig").msgclass
    ArbActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ArbActivity").msgclass
    ArbActivityAssociation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ArbActivityAssociation").msgclass
    ArbActivityClaimLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ArbActivityClaimLog").msgclass
  end
end
