# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/asset_snapshot.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/asset_snapshot.proto", :syntax => :proto3) do
    add_message "AssetSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :NetValue, :message, 3, "DecimalMessage"
      optional :RecordAt, :message, 4, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    AssetSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AssetSnapshot").msgclass
  end
end
