# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/bad_debt.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/bad_debt.proto", :syntax => :proto3) do
    add_message "BadDebt" do
      optional :ID, :int64, 1
      optional :LiquidatedTrader, :message, 2, "AddressMessage"
      optional :MarketID, :string, 3
      optional :PrimaryAmount, :message, 5, "DecimalMessage"
      optional :SecondaryAmount, :message, 6, "DecimalMessage"
      optional :BlockNumber, :int64, 7
      optional :BlockHash, :message, 8, "HashMessage"
      optional :TxIndex, :int64, 9
      optional :TxHash, :message, 10, "HashMessage"
      optional :Index, :int32, 11
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    BadDebt = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BadDebt").msgclass
  end
end
