# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/basis_ratio_snapshot.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/basis_ratio_snapshot.proto", :syntax => :proto3) do
    add_message "BasisRatioSnapshot" do
      optional :MarketID, :string, 1
      optional :Time, :message, 2, "google.protobuf.Timestamp"
      optional :Basis, :message, 3, "DecimalMessage"
      optional :BasisRatio, :message, 4, "DecimalMessage"
      optional :ID, :int64, 5
    end
  end
end

module Internal
  module Types
    BasisRatioSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BasisRatioSnapshot").msgclass
  end
end
