# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/candle.proto

require 'google/protobuf'


require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/candle.proto", :syntax => :proto3) do
    add_message "MetaPrice" do
      optional :MarketID, :string, 1
      optional :Time, :int64, 2
      optional :Price, :message, 3, "DecimalMessage"
      optional :Ext1, :int64, 4
    end
    add_message "MetaPrices" do
      repeated :MetaPrices, :message, 1, "MetaPrice"
    end
    add_message "MetaPriceCandle" do
      optional :Time, :int64, 1
      optional :Open, :message, 2, "DecimalMessage"
      optional :High, :message, 3, "DecimalMessage"
      optional :Low, :message, 4, "DecimalMessage"
      optional :Close, :message, 5, "DecimalMessage"
    end
    add_message "MetaPriceCandles" do
      optional :MarketID, :string, 1
      repeated :MetaPriceCandles, :message, 2, "MetaPriceCandle"
    end
    add_message "PriceCandle" do
      optional :Time, :int64, 1
      optional :Open, :string, 2
      optional :High, :string, 3
      optional :Low, :string, 4
      optional :Close, :string, 5
    end
    add_message "TradeCandle" do
      optional :Time, :int64, 1
      optional :TradeCount, :int32, 2
      optional :Open, :string, 3
      optional :High, :string, 4
      optional :Low, :string, 5
      optional :Close, :string, 6
      optional :Volume, :string, 7
      optional :QuoteVolume, :string, 8
    end
    add_message "Candles" do
      optional :priceType, :enum, 1, "PriceType"
      optional :marketID, :string, 2
      optional :messageID, :uint64, 3
      optional :messageTime, :int64, 4
      repeated :Intervals, :enum, 5, "Interval"
      repeated :priceCandles, :message, 6, "PriceCandle"
      repeated :tradeCandles, :message, 7, "TradeCandle"
    end
    add_message "Market24HourStatus" do
      optional :time, :int64, 1
      optional :messageID, :int64, 2
      optional :marketID, :string, 3
      optional :openPrice, :string, 4
      optional :closePrice, :string, 5
      optional :baseVol, :string, 6
      optional :quoteVol, :string, 7
      optional :totalBaseVol, :string, 8
      optional :totalQuoteVol, :string, 9
      optional :high, :string, 10
      optional :low, :string, 11
    end
    add_message "Market24HourStatusMap" do
      map :map, :string, :message, 1, "Market24HourStatus"
    end
    add_enum "Interval" do
      value :I1M, 0
      value :I5M, 1
      value :I15M, 2
      value :I30M, 3
      value :I1H, 4
      value :I2H, 5
      value :I4H, 6
      value :I6H, 7
      value :I1D, 8
      value :I1W, 9
      value :I1MO, 10
      value :ICount, 11
      value :I1S, 100
    end
    add_enum "PriceType" do
      value :TradePrice, 0
      value :MarkPrice, 1
      value :IndexPrice, 2
      value :IndexPriceWithVol, 4
      value :OffchainMarkPrice, 5
      value :OffchainMarkPriceWithVol, 6
      value :PremiumIndex, 7
    end
    add_enum "CandleStep" do
      value :Default, 0
      value :S1Sec, 1000
      value :S1Min, 60000
      value :S5Min, 300000
      value :S15Min, 900000
      value :S30Min, 1800000
      value :S1Hour, 3600000
      value :S2Hour, 7200000
      value :S4Hour, 14400000
      value :S6Hour, 21600000
      value :S1Day, 86400000
      value :S1Week, 604800000
    end
  end
end

module Internal
  module Types
    MetaPrice = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MetaPrice").msgclass
    MetaPrices = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MetaPrices").msgclass
    MetaPriceCandle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MetaPriceCandle").msgclass
    MetaPriceCandles = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MetaPriceCandles").msgclass
    PriceCandle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PriceCandle").msgclass
    TradeCandle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TradeCandle").msgclass
    Candles = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Candles").msgclass
    Market24HourStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Market24HourStatus").msgclass
    Market24HourStatusMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Market24HourStatusMap").msgclass
    Interval = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Interval").enummodule
    PriceType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PriceType").enummodule
    CandleStep = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CandleStep").enummodule
  end
end
