# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/cex.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'
require 'google/protobuf/wrappers_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/cex.proto", :syntax => :proto3) do
    add_message "CexWithdrawalLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :CexName, :enum, 3, "CexName"
      optional :Network, :enum, 4, "CexNetwork"
      optional :AssetName, :enum, 5, "CexAsset"
      optional :Amount, :message, 6, "DecimalMessage"
      optional :Status, :enum, 7, "CexWithdrawalStatus"
      optional :WithdrawID, :string, 8
      optional :CreatedAt, :message, 9, "google.protobuf.Timestamp"
    end
    add_message "AssetMovementLogExtraInfo" do
      optional :DepositForBurnTxHash, :string, 1
      optional :CCTPAttestation, :string, 2
      optional :CCTPMessage, :string, 3
      optional :CCTPEventNonce, :string, 4
      optional :ReceiveMessageTxHash, :string, 5
      optional :DepositToContractTxHash, :string, 6
      optional :InternalTransferTxHash, :string, 7
      optional :WithdrawToContractTxHash, :string, 8
      optional :DepositToBinanceTxHash, :string, 9
      optional :DegenWithdrawID, :int64, 10
      optional :DegenInternalTransferID, :int64, 11
      optional :ErrorMessage, :string, 12
      optional :TransferTxHash, :string, 13
      optional :ApproveAllowanceSenderLogID, :int64, 14
      optional :InternalTransferSenderLogID, :int64, 15
      optional :WithdrawToContractSenderLogID, :int64, 16
      optional :DepositToContractSenderLogID, :int64, 17
    end
    add_message "AssetMovementLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :CexWithdrawalLogID, :string, 3
      optional :Type, :enum, 4, "AssetMovementType"
      optional :Stage, :enum, 5, "AssetMovementStage"
      optional :Amount, :message, 6, "DecimalMessage"
      optional :TransactionFee, :message, 7, "DecimalMessage"
      optional :CreatedAt, :message, 8, "google.protobuf.Timestamp"
      optional :ExtraInfo, :message, 9, "AssetMovementLogExtraInfo"
      optional :UseCCTP, :bool, 10
    end
    add_message "SystemBotBalanceLog" do
      optional :ID, :int64, 1
      optional :PerpBotUSDCAmount, :message, 2, "DecimalMessage"
      optional :PerpBotETHAmount, :message, 3, "DecimalMessage"
      optional :PerpOpenInterestBotUSDCAmount, :message, 4, "DecimalMessage"
      optional :PerpOpenInterestBotETHAmount, :message, 5, "DecimalMessage"
      optional :DegenBotUSDCAmount, :message, 6, "DecimalMessage"
      optional :DegenBotETHAmount, :message, 7, "DecimalMessage"
      optional :DegenActiveBotUSDCAmount, :message, 8, "DecimalMessage"
      optional :DegenActiveBotETHAmount, :message, 9, "DecimalMessage"
      optional :BinanceUSDCAmount, :message, 10, "DecimalMessage"
      optional :BinanceETHAmount, :message, 11, "DecimalMessage"
      optional :PerpBotUnWithdrawFeeAmount, :message, 12, "DecimalMessage"
      optional :DegenBotUnWithdrawFeeAmount, :message, 13, "DecimalMessage"
      optional :EquivalentUSDCBalance, :message, 14, "DecimalMessage"
      optional :ArbitrumETHAmount, :message, 15, "DecimalMessage"
      optional :ArbitrumUSDCAmount, :message, 16, "DecimalMessage"
      optional :BaseETHAmount, :message, 17, "DecimalMessage"
      optional :BaseUSDCAmount, :message, 18, "DecimalMessage"
      optional :JOJOTraderBotJOJOAmount, :message, 19, "DecimalMessage"
      optional :JOJOTraderBotWETHAmount, :message, 20, "DecimalMessage"
      optional :JOJOTraderBotETHAmount, :message, 21, "DecimalMessage"
      optional :CreatedAt, :message, 30, "google.protobuf.Timestamp"
    end
    add_message "JOJOMovementLog" do
      optional :ID, :int64, 1
      optional :FromAccount, :message, 2, "AddressMessage"
      optional :ToAccount, :message, 3, "AddressMessage"
      optional :Amount, :message, 4, "DecimalMessage"
      optional :TxHash, :message, 5, "HashMessage"
      optional :Stage, :enum, 6, "JOJOMovementStage"
      optional :SenderLogID, :int64, 7
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "JOJOTradeLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Amount, :message, 3, "DecimalMessage"
      optional :SwapWETHToETHLogID, :int64, 4
      optional :Status, :enum, 5, "JOJOTradeLogStatus"
      optional :ErrorMessage, :string, 6
      optional :Type, :enum, 7, "JOJOTradeLogType"
      optional :TxHash, :message, 8, "HashMessage"
      optional :GasLimit, :uint64, 9
      optional :GasPrice, :message, 10, "DecimalMessage"
      optional :GasUsed, :uint64, 11
      optional :Nonce, :message, 12, "google.protobuf.Int64Value"
      optional :AssetMovementLogID, :int64, 13
      optional :SwapETHToWETHLogID, :int64, 14
      optional :SenderLogID, :int64, 15
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "BotAccountWalletPath" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :WalletPath, :string, 3
      optional :AccountRole, :string, 4
      optional :CreatedAt, :message, 5, "google.protobuf.Timestamp"
    end
    add_enum "CexWithdrawalStatus" do
      value :ACTIVE, 0
      value :SETTLED, 1
    end
    add_enum "CexName" do
      value :FAKE, 0
      value :BINANCE, 1
    end
    add_enum "CexNetwork" do
      value :ARBITRUM, 0
      value :BASE, 1
    end
    add_enum "CexAsset" do
      value :USDC, 0
      value :ETH, 1
    end
    add_enum "AssetMovementType" do
      value :ETH_BINANCE_TO_BASE_EOA, 0
      value :USDC_BINANCE_TO_BASE_EOA_DEALER, 1
      value :USDC_BINANCE_TO_BASE_EOA_DEGEN_DEALER, 2
      value :ETH_BINANCE_TO_ARBITRUM_EOA, 3
      value :INTERNAL_TRANSFER_TO_BASE_EOA_DEALER, 4
      value :USDC_BASE_EOA_DEALER_TO_BINANCE, 5
      value :INTERNAL_TRANSFER_TO_BASE_EOA_DEGEN_DEALER, 6
      value :USDC_BASE_CHAIN_TO_BINANCE, 7
      value :USDC_ARBITRUM_CHAIN_TO_BINANCE, 8
      value :ETH_BASE_EOA_TO_BINANCE, 9
      value :JUSD_TO_BASE_EOA_DEALER, 10
      value :USDC_BASE_CHAIN_TO_SENDER_ACCOUNT, 11
      value :VEJOJO_REWARDS_TO_DEGEN_DEALER, 12
    end
    add_enum "AssetMovementStage" do
      value :ASSET_MOVEMENT_STAGE_CREATED, 0
      value :ASSET_MOVEMENT_STAGE_CEX_WITHDRAWAL_REQUEST_SENT, 1
      value :ASSET_MOVEMENT_STAGE_CEX_WITHDRAWAL_REQUEST_SUCCESS, 2
      value :ASSET_MOVEMENT_STAGE_CCTP_DEPOSIT_FOR_BURN_CALLED, 3
      value :ASSET_MOVEMENT_STAGE_CCTP_ATTESTATION_CONFIRMED, 4
      value :ASSET_MOVEMENT_STAGE_CCTP_RECEIVE_MESSAGE_CALLED, 5
      value :ASSET_MOVEMENT_STAGE_DEPOSIT_TO_CONTRACT_CALLED, 6
      value :ASSET_MOVEMENT_STAGE_EOA_BALANCE_UPDATED, 7
      value :ASSET_MOVEMENT_STAGE_SETTLED, 8
      value :ASSET_MOVEMENT_STAGE_REJECTED, 9
      value :ASSET_MOVEMENT_STAGE_FAILED, 10
      value :ASSET_MOVEMENT_STAGE_DEPOSIT_TO_BINANCE, 11
      value :ASSET_MOVEMENT_STAGE_BINANCE_CONFIRMING, 12
    end
    add_enum "JOJOMovementStage" do
      value :JOJO_MOVEMENT_STAGE_CREATED, 0
      value :JOJO_MOVEMENT_STAGE_SETTLED, 1
      value :JOJO_MOVEMENT_STAGE_FAILED, 2
      value :JOJO_MOVEMENT_STAGE_EXPIRED, 3
    end
    add_enum "JOJOTradeLogStatus" do
      value :CREATED, 0
      value :REQUEST_DEPOSIT_ETH_FROM_BINANCE, 1
      value :DEPOSITED_ETH_FROM_BINANCE, 2
      value :SWAPPED_ETH_TO_WETH, 3
      value :REQUEST_SWAP_WETH_TO_ETH, 4
      value :SWAPPED_WETH_TO_ETH, 5
      value :PENDING, 6
      value :SUCCESSFUL, 7
      value :FAILED, 8
      value :SELL_JOJO_TO_WETH, 9
    end
    add_enum "JOJOTradeLogType" do
      value :BUY_JOJO, 0
      value :SELL_JOJO, 1
      value :DEPOSIT_WETH, 2
      value :WITHDRAW_WETH, 3
      value :TRANSFER_JOJO, 4
      value :TRANSFER_ETH_TO_BINANCE, 5
    end
  end
end

module Internal
  module Types
    CexWithdrawalLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CexWithdrawalLog").msgclass
    AssetMovementLogExtraInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AssetMovementLogExtraInfo").msgclass
    AssetMovementLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AssetMovementLog").msgclass
    SystemBotBalanceLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SystemBotBalanceLog").msgclass
    JOJOMovementLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JOJOMovementLog").msgclass
    JOJOTradeLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JOJOTradeLog").msgclass
    BotAccountWalletPath = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BotAccountWalletPath").msgclass
    CexWithdrawalStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CexWithdrawalStatus").enummodule
    CexName = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CexName").enummodule
    CexNetwork = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CexNetwork").enummodule
    CexAsset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CexAsset").enummodule
    AssetMovementType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AssetMovementType").enummodule
    AssetMovementStage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AssetMovementStage").enummodule
    JOJOMovementStage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JOJOMovementStage").enummodule
    JOJOTradeLogStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JOJOTradeLogStatus").enummodule
    JOJOTradeLogType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JOJOTradeLogType").enummodule
  end
end
