# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/chain_link_date_stream.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/chain_link_date_stream.proto", :syntax => :proto3) do
    add_message "ChainLinkDataStreamMarket" do
      optional :ID, :int64, 1
      optional :MarketID, :string, 2
      optional :Enable, :bool, 3
      optional :FeedID, :string, 4
      optional :ChainLinkOracle, :message, 5, "AddressMessage"
      optional :OracleName, :string, 6
      optional :PriceChangeThreshold, :message, 7, "DecimalMessage"
    end
  end
end

module Internal
  module Types
    ChainLinkDataStreamMarket = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ChainLinkDataStreamMarket").msgclass
  end
end
