# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/check_in_activity.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/check_in_activity.proto", :syntax => :proto3) do
    add_message "CheckInActivityConfig" do
      optional :ID, :int64, 1
      optional :TotalRewardAmount, :message, 2, "DecimalMessage"
      optional :StartAt, :message, 3, "google.protobuf.Timestamp"
      optional :EndAt, :message, 7, "google.protobuf.Timestamp"
      optional :RewardTokenAddress, :message, 8, "AddressMessage"
    end
    add_message "CheckInActivity" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TaskName, :string, 3
      optional :Amount, :message, 4, "DecimalMessage"
      optional :EventPoints, :message, 5, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "CheckInActivityAssociation" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TaskName, :string, 3
      optional :SourceID, :int64, 4
      optional :SourceType, :string, 5
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "CheckInActivityEpochReward" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :RewardAmount, :message, 3, "DecimalMessage"
      optional :AmountUnit, :string, 4
      optional :SenderLogID, :int64, 5
      optional :ActivityConfigID, :int64, 6
      optional :IP, :string, 7
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    CheckInActivityConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CheckInActivityConfig").msgclass
    CheckInActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CheckInActivity").msgclass
    CheckInActivityAssociation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CheckInActivityAssociation").msgclass
    CheckInActivityEpochReward = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CheckInActivityEpochReward").msgclass
  end
end
