# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/collateral_market.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/collateral_market.proto", :syntax => :proto3) do
    add_message "CollateralMarket" do
      optional :ID, :string, 1
      optional :IsEnabled, :bool, 2
      optional :TokenAddress, :message, 3, "AddressMessage"
      optional :CreditDecimals, :int64, 4
      optional :CollateralSymbol, :string, 5
      optional :LiquidationMortgageRate, :message, 19, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    CollateralMarket = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CollateralMarket").msgclass
  end
end
