# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/commission_rebate_daily_record.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/commission_rebate_daily_record.proto", :syntax => :proto3) do
    add_message "CommissionRebateEpochRecord" do
      optional :ID, :int64, 1
      optional :InviterAccount, :message, 2, "AddressMessage"
      optional :InviteeAccount, :message, 3, "AddressMessage"
      optional :Amount, :message, 4, "DecimalMessage"
      optional :TotalPoints, :message, 5, "DecimalMessage"
      optional :RecordAt, :message, 6, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 7, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 8, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    CommissionRebateEpochRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CommissionRebateEpochRecord").msgclass
  end
end
