# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/commission_rebate_settlement.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/commission_rebate_settlement.proto", :syntax => :proto3) do
    add_message "CommissionRebateSettlement" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Amount, :message, 3, "DecimalMessage"
      optional :SettledAmount, :message, 4, "DecimalMessage"
      optional :UnsettledAmount, :message, 5, "DecimalMessage"
      optional :CreatedAt, :message, 6, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 7, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    CommissionRebateSettlement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CommissionRebateSettlement").msgclass
  end
end
