# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/committed_lp_snapshot.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/committed_lp_snapshot.proto", :syntax => :proto3) do
    add_message "CommittedLPSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :CommittedLPAmount, :message, 3, "DecimalMessage"
      optional :StakeLPAmount, :message, 4, "DecimalMessage"
      optional :RecordAt, :message, 19, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    CommittedLPSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CommittedLPSnapshot").msgclass
  end
end
