# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/degen.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/hash_pb'
require 'internal/types/degen_asset_pb'
require 'internal/types/degen_position_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/degen.proto", :syntax => :proto3) do
    add_message "DegenSystemStatus" do
      optional :SuspendService, :bool, 1
      optional :PNLRiskPolicyTrigger, :bool, 2
      optional :MarginRiskPolicyTrigger, :bool, 3
    end
    add_message "DegenIndexPrice" do
      optional :MarketID, :string, 1
      optional :JoJoTime, :int64, 2
      optional :IndexTime, :int64, 3
      optional :IntPrice, :int64, 4
      optional :Price, :message, 5, "DecimalMessage"
    end
    add_message "DegenIndexPrices" do
      repeated :DegenIndexPrices, :message, 1, "DegenIndexPrice"
    end
    add_message "DegenMarketAvailableLeverage" do
      repeated :Leverages, :string, 1
    end
    add_message "DegenClosePositionFeeRateItem" do
      optional :L, :message, 1, "DecimalMessage"
      optional :R, :message, 2, "DecimalMessage"
      optional :V, :message, 3, "DecimalMessage"
    end
    add_message "DegenClosePositionFeeRate" do
      optional :MinRate, :message, 1, "DecimalMessage"
      optional :MaxRate, :message, 2, "DecimalMessage"
      repeated :Items, :message, 3, "DegenClosePositionFeeRateItem"
    end
    add_message "DegenMarket" do
      optional :ID, :uint64, 1
      optional :MarketID, :string, 2
      optional :Precision, :int32, 3
      optional :FeeRate, :message, 4, "DecimalMessage"
      optional :TickSize, :message, 5, "DecimalMessage"
      optional :StepSize, :message, 6, "DecimalMessage"
      optional :MinMarginAmount, :message, 7, "DecimalMessage"
      optional :MaxMarginAmount, :message, 8, "DecimalMessage"
      optional :MaxPositionNum, :int32, 9
      optional :LiquidationRate, :message, 12, "DecimalMessage"
      optional :InitialLeverage, :message, 13, "DecimalMessage"
      optional :AvailableLeverage, :message, 14, "DegenMarketAvailableLeverage"
      optional :ClosePositionFeeRate, :message, 15, "DegenClosePositionFeeRate"
    end
    add_message "DegenAggregatePNL" do
      optional :ID, :int64, 1
      optional :MarketID, :string, 2
      optional :RecordAt, :message, 3, "google.protobuf.Timestamp"
      optional :PositionCount, :int32, 4
      optional :TakeProfitCount, :int32, 5
      optional :LiquidationCount, :int32, 6
      optional :UserCloseCount, :int32, 7
      optional :OpenPositionFee, :message, 8, "DecimalMessage"
      optional :ClosePositionFee, :message, 9, "DecimalMessage"
      optional :LiquidationFee, :message, 10, "DecimalMessage"
      optional :TotalPNL, :message, 11, "DecimalMessage"
      optional :TakeProfitPNL, :message, 12, "DecimalMessage"
      optional :LiquidationPNL, :message, 13, "DecimalMessage"
      optional :UserClosePNL, :message, 14, "DecimalMessage"
      optional :SystemPNLWinCount, :int32, 15
      optional :SystemWithFeeWinCount, :int32, 16
    end
    add_message "DegenAccountState" do
      optional :Asset, :message, 1, "DegenAccountAsset"
      repeated :Positions, :message, 2, "DegenPosition"
    end
    add_message "DegenIncome" do
      optional :ID, :int64, 1
      optional :OtherID, :int64, 2
      optional :OtherSubID, :int64, 3
      optional :IncomeType, :int32, 4
      optional :Desc, :string, 5
      optional :Account, :message, 6, "AddressMessage"
      optional :JoJoAccount, :bool, 7
      optional :MarketID, :string, 8
      optional :PaperSize, :message, 9, "DecimalMessage"
      optional :UsdcAmount, :message, 10, "DecimalMessage"
      optional :TradePrice, :message, 11, "DecimalMessage"
      optional :TriggerPrice, :message, 12, "DecimalMessage"
      optional :IncomeTime, :message, 13, "google.protobuf.Timestamp"
      optional :LogIndex, :uint64, 14
    end
    add_message "DegenTrade" do
      optional :ID, :int64, 1
      optional :TradeID, :int64, 2
      optional :PositionID, :int64, 3
      optional :Account, :message, 4, "AddressMessage"
      optional :JoJoAccount, :bool, 5
      optional :MarketID, :string, 6
      optional :TradeType, :int32, 7
      optional :TradeSide, :int32, 8
      optional :Desc, :string, 9
      optional :Amount, :message, 10, "DecimalMessage"
      optional :Price, :message, 11, "DecimalMessage"
      optional :PNL, :message, 12, "DecimalMessage"
      optional :Fee, :message, 13, "DecimalMessage"
      optional :TradeTime, :message, 14, "google.protobuf.Timestamp"
      optional :LogIndex, :uint64, 15
    end
    add_message "DegenBlockchainLog" do
      optional :ID, :int64, 1
      optional :Topic, :string, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :Amount, :message, 4, "DecimalMessage"
      optional :BlockNumber, :uint64, 5
      optional :BlockHash, :message, 6, "HashMessage"
      optional :TxHash, :message, 7, "HashMessage"
      optional :Status, :int32, 8
      optional :CreatedAt, :message, 9, "google.protobuf.Timestamp"
      optional :SettledAt, :message, 10, "google.protobuf.Timestamp"
      optional :Desc, :string, 11
      optional :OtherID, :int64, 12
      optional :IsInternal, :bool, 13
    end
    add_message "DegenTransferToSenderAccountLog" do
      optional :ID, :int64, 1
      optional :LogIndex, :uint64, 2
      optional :CreatedAt, :message, 3, "google.protobuf.Timestamp"
      optional :TransferSource, :string, 4
      optional :SenderAccount, :message, 5, "AddressMessage"
      optional :TotalTransfer, :message, 6, "DecimalMessage"
      optional :TransferFee, :message, 7, "DecimalMessage"
      optional :TransferLiquidationFee, :message, 8, "DecimalMessage"
      optional :TransferCounterpartyAccountPNL, :message, 9, "DecimalMessage"
      optional :TransferPrizePool, :message, 10, "DecimalMessage"
    end
    add_message "DegenRiskAccount" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :IsBlacklisted, :bool, 3
      optional :PositionMarginLimit, :message, 4, "DecimalMessage"
      optional :DailyVolumeLimit, :message, 5, "DecimalMessage"
      optional :TakeProfitRatioLimit, :message, 6, "DecimalMessage"
    end
    add_message "DegenOpenPositionRiskPolicy" do
      optional :ID, :int64, 1
      optional :Name, :string, 2
      optional :ProfitCondition, :message, 3, "DecimalMessage"
      optional :TradeCountCondition, :int32, 4
      optional :TradingDaysCondition, :int32, 5
      optional :WinRateCondition, :message, 6, "DecimalMessage"
      optional :VolumeCondition, :message, 7, "DecimalMessage"
      optional :PositionMarginLimit, :message, 8, "DecimalMessage"
      optional :DailyVolumeLimit, :message, 9, "DecimalMessage"
      optional :TakeProfitRatioLimit, :message, 10, "DecimalMessage"
    end
  end
end

module Internal
  module Types
    DegenSystemStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenSystemStatus").msgclass
    DegenIndexPrice = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenIndexPrice").msgclass
    DegenIndexPrices = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenIndexPrices").msgclass
    DegenMarketAvailableLeverage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenMarketAvailableLeverage").msgclass
    DegenClosePositionFeeRateItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenClosePositionFeeRateItem").msgclass
    DegenClosePositionFeeRate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenClosePositionFeeRate").msgclass
    DegenMarket = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenMarket").msgclass
    DegenAggregatePNL = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenAggregatePNL").msgclass
    DegenAccountState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenAccountState").msgclass
    DegenIncome = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenIncome").msgclass
    DegenTrade = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenTrade").msgclass
    DegenBlockchainLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenBlockchainLog").msgclass
    DegenTransferToSenderAccountLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenTransferToSenderAccountLog").msgclass
    DegenRiskAccount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenRiskAccount").msgclass
    DegenOpenPositionRiskPolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenOpenPositionRiskPolicy").msgclass
  end
end
