# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/degen_asset.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/degen_asset.proto", :syntax => :proto3) do
    add_message "DegenAccountAsset" do
      optional :Account, :message, 1, "AddressMessage"
      optional :CreditAmount, :message, 2, "DecimalMessage"
      optional :PendingCreditAmount, :message, 3, "DecimalMessage"
    end
    add_message "DegenAccountAssetWithPositionMargin" do
      optional :Account, :message, 1, "AddressMessage"
      optional :CreditAmount, :message, 2, "DecimalMessage"
      optional :PendingCreditAmount, :message, 3, "DecimalMessage"
      optional :PositionMargin, :message, 4, "DecimalMessage"
    end
    add_message "DegenAssetSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :NetValue, :message, 3, "DecimalMessage"
      optional :RecordAt, :message, 4, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 5, "google.protobuf.Timestamp"
    end
    add_message "DegenAggregateAsset" do
      optional :ID, :int64, 1
      optional :IncomeID, :int64, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :Amount, :message, 4, "DecimalMessage"
    end
  end
end

module Internal
  module Types
    DegenAccountAsset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenAccountAsset").msgclass
    DegenAccountAssetWithPositionMargin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenAccountAssetWithPositionMargin").msgclass
    DegenAssetSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenAssetSnapshot").msgclass
    DegenAggregateAsset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenAggregateAsset").msgclass
  end
end
