# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/degen_position.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/degen_position.proto", :syntax => :proto3) do
    add_message "DegenPosition" do
      optional :ID, :int64, 1
      optional :PositionID, :int64, 2
      optional :MarketID, :string, 3
      optional :Account, :message, 4, "AddressMessage"
      optional :JoJoAccount, :bool, 5
      optional :OpenPositionSide, :int32, 6
      optional :ClosePositionType, :int32, 7
      optional :Leverage, :message, 8, "DecimalMessage"
      optional :TakeProfitRatio, :message, 9, "DecimalMessage"
      optional :OpenPositionPrice, :message, 10, "DecimalMessage"
      optional :TakeProfitPrice, :message, 11, "DecimalMessage"
      optional :LiquidationPrice, :message, 12, "DecimalMessage"
      optional :PositionSize, :message, 13, "DecimalMessage"
      optional :PositionMargin, :message, 14, "DecimalMessage"
      optional :OpenPositionFee, :message, 15, "DecimalMessage"
      optional :ClosePositionIndexPrice, :message, 16, "DecimalMessage"
      optional :ClosePositionFee, :message, 17, "DecimalMessage"
      optional :LiquidationFee, :message, 18, "DecimalMessage"
      optional :PNL, :message, 19, "DecimalMessage"
      optional :RefundCredit, :message, 20, "DecimalMessage"
      optional :OpenPositionTime, :message, 21, "google.protobuf.Timestamp"
      optional :ClosePositionTime, :message, 22, "google.protobuf.Timestamp"
      optional :OpenTradeID, :int64, 23
      optional :CloseTradeID, :int64, 24
      optional :OpenLogIndex, :uint64, 25
      optional :CloseLogIndex, :uint64, 26
      optional :IP, :string, 27
    end
    add_message "DegenAggregatePosition" do
      optional :ID, :int64, 1
      optional :PositionID, :int64, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :OpenPositionFee, :message, 4, "DecimalMessage"
      optional :ClosePositionFee, :message, 5, "DecimalMessage"
      optional :LiquidationFee, :message, 6, "DecimalMessage"
      optional :PNL, :message, 7, "DecimalMessage"
      optional :RefundCredit, :message, 8, "DecimalMessage"
      optional :Volume, :message, 9, "DecimalMessage"
      optional :WinCount, :int32, 10
      optional :TotalCount, :int32, 11
      optional :TradingDays, :int32, 12
      optional :LatestDay, :message, 13, "google.protobuf.Timestamp"
      optional :LatestDayVol, :message, 14, "DecimalMessage"
    end
    add_message "DegenPositionSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :RecordAt, :message, 3, "google.protobuf.Timestamp"
      optional :TotalCount, :int32, 4
      optional :WinCount, :int32, 5
      optional :LossCount, :int32, 6
      optional :OpenPositionFee, :message, 7, "DecimalMessage"
      optional :ClosePositionFee, :message, 8, "DecimalMessage"
      optional :LiquidationFee, :message, 9, "DecimalMessage"
      optional :PNL, :message, 10, "DecimalMessage"
    end
  end
end

module Internal
  module Types
    DegenPosition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenPosition").msgclass
    DegenAggregatePosition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenAggregatePosition").msgclass
    DegenPositionSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenPositionSnapshot").msgclass
  end
end
