# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/degenlog.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/degenlog.proto", :syntax => :proto3) do
    add_message "DegenLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Type, :enum, 3, "DEGEN_LOG_TYPE"
      optional :Status, :enum, 4, "DEGEN_LOG_STATUS"
      optional :CreatedAt, :message, 6, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 7, "google.protobuf.Timestamp"
      optional :Data, :bytes, 8
    end
    add_enum "DEGEN_LOG_TYPE" do
      value :DEPOSIT, 0
      value :WITHDRAW, 1
      value :LIQUIDATION, 2
    end
    add_enum "DEGEN_LOG_STATUS" do
      value :CREATED, 0
      value :SUCCESSFUL, 1
      value :FAILED, 2
    end
  end
end

module Internal
  module Types
    DegenLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenLog").msgclass
    DEGEN_LOG_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DEGEN_LOG_TYPE").enummodule
    DEGEN_LOG_STATUS = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DEGEN_LOG_STATUS").enummodule
  end
end
