# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/degen_lucky_draw.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/degen_lucky_draw.proto", :syntax => :proto3) do
    add_message "DegenLuckyDrawInfo" do
      optional :ID, :int64, 1
      optional :EpochID, :int64, 2
      optional :BeginPositionID, :int64, 3
      optional :EndPositionID, :int64, 4
      optional :TradingFee, :message, 5, "DecimalMessage"
      optional :LiquidationFee, :message, 6, "DecimalMessage"
      optional :SystemPNL, :message, 7, "DecimalMessage"
      optional :PrizeRate, :int32, 8
      optional :PrizeAmount, :message, 9, "DecimalMessage"
      optional :TotalChance, :int32, 10
      optional :StartCountingTime, :message, 11, "google.protobuf.Timestamp"
      optional :EndCountingTime, :message, 12, "google.protobuf.Timestamp"
      optional :StartLotteryTime, :message, 13, "google.protobuf.Timestamp"
      optional :EndLotteryTime, :message, 14, "google.protobuf.Timestamp"
      optional :TransferTradingFee, :message, 15, "DecimalMessage"
      optional :TransferLiquidationFee, :message, 16, "DecimalMessage"
      optional :TransferSystemPNL, :message, 17, "DecimalMessage"
      optional :Status, :int32, 18
      optional :F1, :int32, 19
      optional :F2, :int32, 20
      optional :F3, :int32, 21
      optional :F4, :int32, 22
    end
    add_message "DegenLuckyDrawPrivateInfo" do
      optional :LuckyDrawInfo, :message, 1, "DegenLuckyDrawInfo"
      optional :TotalChance, :int32, 2
      optional :UsedChange, :int32, 3
      optional :NextEpochChance, :int32, 4
    end
    add_message "DegenLuckyDrawLotteryChance" do
      optional :ID, :uint64, 1
      optional :EpochID, :int64, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :Amount, :message, 4, "DecimalMessage"
      optional :LotteryChance, :int32, 5
    end
    add_message "DegenLuckyDrawLotteryRecord" do
      optional :ID, :uint64, 1
      optional :EpochID, :int64, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :RecordID, :int64, 4
      optional :RecordStatus, :int32, 5
      optional :Amount, :message, 6, "DecimalMessage"
      optional :RecordTime, :message, 7, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    DegenLuckyDrawInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenLuckyDrawInfo").msgclass
    DegenLuckyDrawPrivateInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenLuckyDrawPrivateInfo").msgclass
    DegenLuckyDrawLotteryChance = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenLuckyDrawLotteryChance").msgclass
    DegenLuckyDrawLotteryRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenLuckyDrawLotteryRecord").msgclass
  end
end
