# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/degen_kline.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/degen_kline.proto", :syntax => :proto3) do
    add_message "DegenKLine" do
      optional :ID, :int64, 1
      optional :MarketID, :string, 2
      optional :KLineType, :int32, 3
      optional :StartTs, :int64, 4
      optional :TradeCount, :int32, 5
      optional :Open, :message, 6, "DecimalMessage"
      optional :High, :message, 7, "DecimalMessage"
      optional :Low, :message, 8, "DecimalMessage"
      optional :Close, :message, 9, "DecimalMessage"
      optional :Volume, :message, 10, "DecimalMessage"
      optional :QuoteVolume, :message, 11, "DecimalMessage"
      optional :CreatedAt, :message, 12, "google.protobuf.Timestamp"
    end
    add_message "DegenKLines" do
      repeated :DegenKLines, :message, 1, "DegenKLine"
    end
    add_message "DegenKLineSnapshot" do
      optional :MarketID, :string, 1
      optional :TotalVolume, :message, 2, "DecimalMessage"
      optional :TotalQuoteVolume, :message, 3, "DecimalMessage"
      repeated :DegenKLines, :message, 4, "DegenKLine"
      optional :SecondKLine, :message, 5, "DegenKLine"
    end
    add_message "DegenKLineSnapshots" do
      optional :KafkaOffset, :int64, 1
      optional :LogIndex, :uint64, 2
      repeated :DegenKLineSnapshots, :message, 3, "DegenKLineSnapshot"
    end
    add_message "DegenKLineSnapshotData" do
      optional :KafkaOffset, :int64, 1
      optional :LonIndex, :uint64, 2
      optional :CreatedAt, :message, 13, "google.protobuf.Timestamp"
      optional :Data, :bytes, 3
    end
  end
end

module Internal
  module Types
    DegenKLine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenKLine").msgclass
    DegenKLines = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenKLines").msgclass
    DegenKLineSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenKLineSnapshot").msgclass
    DegenKLineSnapshots = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenKLineSnapshots").msgclass
    DegenKLineSnapshotData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenKLineSnapshotData").msgclass
  end
end
