# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/degen_snapshot.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/degen_snapshot.proto", :syntax => :proto3) do
    add_message "DegenProfitSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Profit, :message, 3, "DecimalMessage"
      optional :CumulativeProfit, :message, 4, "DecimalMessage"
      optional :RecordAt, :message, 5, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "DegenTradeVolumeSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Volume, :message, 3, "DecimalMessage"
      optional :Previous6daysVolume, :message, 4, "DecimalMessage"
      optional :Previous29daysVolume, :message, 5, "DecimalMessage"
      optional :TotalVolume, :message, 6, "DecimalMessage"
      optional :TotalTradeCount, :int32, 7
      optional :RecordAt, :message, 8, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 9, "google.protobuf.Timestamp"
      optional :CurrentMonthVolume, :message, 10, "DecimalMessage"
    end
  end
end

module Internal
  module Types
    DegenProfitSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenProfitSnapshot").msgclass
    DegenTradeVolumeSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenTradeVolumeSnapshot").msgclass
  end
end
