# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/device_record.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/device_record.proto", :syntax => :proto3) do
    add_message "DeviceRecord" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :OrderID, :int64, 3
      optional :IP, :string, 4
      optional :UserAgent, :string, 5
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    DeviceRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DeviceRecord").msgclass
  end
end
