# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/dodo_account_claim_log.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/dodo_account_claim_log.proto", :syntax => :proto3) do
    add_message "DodoAccountClaimLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Amount, :message, 3, "DecimalMessage"
      optional :Points, :message, 4, "DecimalMessage"
      optional :MerkleTreeIndex, :int64, 5
      optional :MerkleTreeProof, :string, 6
      optional :ClaimedAt, :message, 7, "google.protobuf.Timestamp"
      optional :TxHash, :message, 8, "HashMessage"
      optional :BlockHash, :message, 9, "HashMessage"
      optional :BlockNumber, :int64, 10
      optional :EpochNumber, :int64, 11
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    DodoAccountClaimLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DodoAccountClaimLog").msgclass
  end
end
