# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/email_verification.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/email_verification.proto", :syntax => :proto3) do
    add_message "EmailVerification" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Email, :string, 3
      optional :Token, :string, 4
      optional :ExpiredAt, :message, 19, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    EmailVerification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EmailVerification").msgclass
  end
end
