# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/engine.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/types/types_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/engine.proto", :syntax => :proto3) do
    add_message "EngineOrder" do
      optional :ID, :int64, 1
      optional :Side, :enum, 2, "SIDE"
      optional :Amount, :message, 3, "DecimalMessage"
      optional :Price, :message, 4, "DecimalMessage"
      optional :TimeInForce, :enum, 5, "TIF"
      optional :Account, :message, 6, "AddressMessage"
      optional :finalReason, :string, 7
      optional :OrderTS, :int64, 8
      optional :EnqueueTS, :int64, 9
      optional :IsLiquidityOrder, :bool, 10
    end
    add_message "OrderInBook" do
      optional :ID, :int64, 1
      optional :Amount, :message, 2, "DecimalMessage"
      optional :Price, :message, 3, "DecimalMessage"
      optional :Account, :message, 4, "AddressMessage"
    end
    add_message "BranchMatchResult" do
      optional :OrderAmount, :message, 1, "DecimalMessage"
      optional :TotalMatchedAmount, :message, 2, "DecimalMessage"
      repeated :MatchedOrders, :message, 3, "OrderInBook"
      repeated :MatchedAmounts, :message, 4, "DecimalMessage"
      repeated :MakerTradeIDs, :int64, 5
      repeated :TakerTradeIDs, :int64, 6
      optional :Time, :message, 7, "google.protobuf.Timestamp"
    end
    add_message "NewMinute" do
      optional :OffsetDurationFromMinuteBeginning, :int64, 1
      optional :TriggeredAt, :message, 2, "google.protobuf.Timestamp"
    end
    add_message "EventProcessResult" do
      optional :time, :int64, 1
      map :context, :string, :string, 2
    end
    add_message "OrderbookProcessResult" do
      optional :Sequence, :uint64, 1
      optional :Order, :message, 2, "EngineOrder"
      optional :Matched, :message, 3, "BranchMatchResult"
      optional :LeftOnOrderbookAmount, :message, 4, "DecimalMessage"
      optional :RemoveFromOrderbookAmount, :message, 5, "DecimalMessage"
      optional :Type, :enum, 7, "EnqueueType"
      optional :MaxBid, :message, 8, "DecimalMessage"
      optional :MinAsk, :message, 9, "DecimalMessage"
      optional :BidTreeSize, :int32, 11
      optional :AskTreeSize, :int32, 12
      optional :MarketID, :string, 13
      optional :MatchTS, :int64, 14
      optional :InsiderTrading, :bool, 15
      optional :InsiderLeverage, :message, 16, "DecimalMessage"
    end
    add_message "EngineProcessResult" do
      optional :epochID, :int64, 1
      optional :engineProcessType, :enum, 2, "EngineProcessType"
      optional :eventProcessResult, :message, 3, "EventProcessResult"
      repeated :orderProcessResults, :message, 4, "OrderbookProcessResult"
    end
    add_enum "EnqueueType" do
      value :NEW, 0
      value :CANCEL, 1
    end
    add_enum "EngineProcessType" do
      value :ProcessOrder, 0
      value :ProcessEventIncrEpochID, 1
      value :ProcessEventNewMinute, 2
    end
  end
end

module Internal
  module Types
    EngineOrder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EngineOrder").msgclass
    OrderInBook = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderInBook").msgclass
    BranchMatchResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BranchMatchResult").msgclass
    NewMinute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NewMinute").msgclass
    EventProcessResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EventProcessResult").msgclass
    OrderbookProcessResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderbookProcessResult").msgclass
    EngineProcessResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EngineProcessResult").msgclass
    EnqueueType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EnqueueType").enummodule
    EngineProcessType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EngineProcessType").enummodule
  end
end
