# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/funding_rate_price_sample.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/funding_rate_price_sample.proto", :syntax => :proto3) do
    add_message "FundingRatePriceSample" do
      optional :MarketID, :string, 1
      optional :Time, :message, 2, "google.protobuf.Timestamp"
      optional :IndexPrice, :message, 3, "DecimalMessage"
      optional :JOJOBidPrice, :message, 4, "DecimalMessage"
      optional :JOJOAskPrice, :message, 5, "DecimalMessage"
    end
  end
end

module Internal
  module Types
    FundingRatePriceSample = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRatePriceSample").msgclass
  end
end
