# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/funding_rate_arbitrage_log.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/funding_rate_arbitrage_log.proto", :syntax => :proto3) do
    add_message "FundingRateArbitrageLogExtraInfo" do
    end
    add_message "FundingRateArbitrageLog" do
      optional :Account, :message, 1, "AddressMessage"
      optional :EventName, :enum, 2, "FundingRateArbitrageEvent"
      optional :BlockNumber, :int64, 3
      optional :BlockHash, :message, 4, "HashMessage"
      optional :TxIndex, :int64, 5
      optional :TxHash, :message, 6, "HashMessage"
      optional :Time, :message, 7, "google.protobuf.Timestamp"
      optional :ExtraInfo, :message, 8, "FundingRateArbitrageLogExtraInfo"
    end
    add_enum "FundingRateArbitrageEvent" do
      value :DEPOSIT, 0
      value :REQUEST_WITHDRAW, 1
      value :CANCLE_WITHDRAW, 2
      value :EXECUTE_WITHDRAW, 3
    end
  end
end

module Internal
  module Types
    FundingRateArbitrageLogExtraInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageLogExtraInfo").msgclass
    FundingRateArbitrageLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageLog").msgclass
    FundingRateArbitrageEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageEvent").enummodule
  end
end
