# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/funding_rate_arbitrage.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/hash_pb'
require 'internal/types/order_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/funding_rate_arbitrage.proto", :syntax => :proto3) do
    add_message "FundingRateArbitrageLogExtraInfo" do
      optional :WithdrawEarnUSDCAmount, :message, 1, "DecimalMessage"
      optional :WithdrawIndex, :message, 2, "DecimalMessage"
      optional :WithdrawFeeAmount, :message, 3, "DecimalMessage"
      optional :WithdrawUSDCAmount, :message, 4, "DecimalMessage"
      optional :DepositUSDCAmount, :message, 5, "DecimalMessage"
      optional :DepositFeeAmount, :message, 6, "DecimalMessage"
      optional :DepositEarnUSDCAmount, :message, 7, "DecimalMessage"
      optional :WithdrawalExecutedTxHash, :message, 8, "HashMessage"
    end
    add_message "FundingRateArbitrageLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :EventName, :enum, 3, "FundingRateArbitrageEvent"
      optional :BlockNumber, :int64, 4
      optional :BlockHash, :message, 5, "HashMessage"
      optional :TxIndex, :int64, 6
      optional :TxHash, :message, 7, "HashMessage"
      optional :Time, :message, 8, "google.protobuf.Timestamp"
      optional :ExtraInfo, :message, 9, "FundingRateArbitrageLogExtraInfo"
      optional :WithdrawRequestID, :int64, 10
      optional :IsWithdrawalExecuted, :bool, 11
    end
    add_message "FundingRateArbitrageAdminLogExtraInfo" do
      optional :Order, :message, 1, "Order"
      optional :Amount, :message, 2, "DecimalMessage"
      repeated :executedWithdrawalIDs, :uint64, 3
      optional :MinReceivedAmount, :message, 4, "DecimalMessage"
      optional :Side, :string, 5
      optional :TokenName, :string, 6
    end
    add_message "FundingRateArbitrageAdminLog" do
      optional :ID, :int64, 5
      optional :Operator, :string, 1
      optional :Time, :message, 2, "google.protobuf.Timestamp"
      optional :EventName, :enum, 3, "FundingRateArbitrageAdminLogEvent"
      optional :Memo, :string, 4
      optional :SenderLogID, :uint64, 6
      optional :BatchNumber, :string, 7
      optional :ExtraInfo, :message, 8, "FundingRateArbitrageAdminLogExtraInfo"
    end
    add_message "FundingRateArbitrageAccountState" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :EarnUSDCBalance, :message, 3, "DecimalMessage"
      optional :FrozenEarnUSDCBalance, :message, 4, "DecimalMessage"
      optional :TotalDepositAmount, :message, 5, "DecimalMessage"
      optional :TotalWithdrawAmount, :message, 6, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "FundingRateArbitrageAccountStateSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :NetValue, :message, 3, "DecimalMessage"
      optional :RecordAt, :message, 4, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "FundingRateArbitrageEarnUSDCSnapshot" do
      optional :ID, :int64, 1
      optional :EarnUSDCTotalSupply, :message, 2, "DecimalMessage"
      optional :EarnUSDCIndex, :message, 3, "DecimalMessage"
      optional :RecordAt, :message, 4, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_enum "FundingRateArbitrageEvent" do
      value :DEPOSIT, 0
      value :REQUEST_WITHDRAW, 1
      value :CANCLE_WITHDRAW, 2
      value :EXECUTE_WITHDRAW, 3
    end
    add_enum "FundingRateArbitrageAdminLogEvent" do
      value :LONG_ETH, 0
      value :SHORT_ETH, 1
      value :SWAP_BUY_TOKEN, 2
      value :SWAP_SELL_TOKEN, 3
      value :DEPOSIT_USDC_TO_PERP, 4
      value :WITHDRAW_USDC_FROM_PERP, 5
      value :EXECUTE_WITHDRAWALS, 6
      value :DEPOSIT_JUSD_TO_PERP, 7
      value :WITHDRAW_JUSD_FROM_PERP, 8
    end
  end
end

module Internal
  module Types
    FundingRateArbitrageLogExtraInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageLogExtraInfo").msgclass
    FundingRateArbitrageLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageLog").msgclass
    FundingRateArbitrageAdminLogExtraInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageAdminLogExtraInfo").msgclass
    FundingRateArbitrageAdminLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageAdminLog").msgclass
    FundingRateArbitrageAccountState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageAccountState").msgclass
    FundingRateArbitrageAccountStateSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageAccountStateSnapshot").msgclass
    FundingRateArbitrageEarnUSDCSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageEarnUSDCSnapshot").msgclass
    FundingRateArbitrageEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageEvent").enummodule
    FundingRateArbitrageAdminLogEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateArbitrageAdminLogEvent").enummodule
  end
end
