# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/fundingrate.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'google/protobuf/wrappers_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/fundingrate.proto", :syntax => :proto3) do
    add_message "FundingRateRecord" do
      optional :ID, :int64, 1
      optional :MarketID, :string, 2
      optional :Time, :message, 3, "google.protobuf.Timestamp"
      optional :ContractFundingRate, :message, 4, "DecimalMessage"
      optional :FrontendFundingRate, :message, 5, "DecimalMessage"
      optional :Status, :enum, 6, "FUNDING_RATE_RECORD_STATUS"
      optional :ErrorMessage, :string, 7
      optional :BlockNumber, :message, 8, "google.protobuf.Int64Value"
      optional :LogIndex, :message, 9, "google.protobuf.Int64Value"
      optional :SettledAt, :message, 10, "google.protobuf.Timestamp"
      optional :MarkPrice, :message, 11, "DecimalMessage"
      optional :AveragePremium, :message, 12, "DecimalMessage"
    end
    add_enum "FUNDING_RATE_RECORD_STATUS" do
      value :CREATED, 0
      value :PENDING, 1
      value :FAILED, 2
      value :SETTLED, 3
      value :INCOME_DISPATCHED, 4
    end
  end
end

module Internal
  module Types
    FundingRateRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateRecord").msgclass
    FUNDING_RATE_RECORD_STATUS = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FUNDING_RATE_RECORD_STATUS").enummodule
  end
end
