# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/grid_order.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/grid_order.proto", :syntax => :proto3) do
    add_message "GridOrder" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :MarketID, :string, 3
      optional :Status, :enum, 4, "GRID_ORDER_STATUS"
      optional :LowerPrice, :message, 5, "DecimalMessage"
      optional :UpperPrice, :message, 6, "DecimalMessage"
      optional :Type, :enum, 7, "GRID_ORDER_TYPE"
      optional :StopPriceType, :enum, 8, "STOP_PRICE_TYPE"
      optional :StopLowerPrice, :message, 9, "DecimalMessage"
      optional :StopUpperPrice, :message, 10, "DecimalMessage"
      optional :InvestmentAmount, :message, 11, "DecimalMessage"
      optional :GridCount, :int64, 12
      optional :FinalReason, :string, 13
      optional :PaperSize, :message, 14, "DecimalMessage"
      optional :TakeProfitPnl, :message, 15, "DecimalMessage"
      optional :StopLossPnl, :message, 16, "DecimalMessage"
      optional :CloseType, :enum, 17, "GRID_ORDER_CLOSE_TYPE"
      optional :HasPosition, :bool, 18
      optional :HasTransferBackAssets, :bool, 19
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
      optional :CloseGridAt, :message, 22, "google.protobuf.Timestamp"
      optional :SettledAt, :message, 23, "google.protobuf.Timestamp"
      optional :AdditionalInvestmentAmount, :message, 24, "DecimalMessage"
    end
    add_enum "GRID_ORDER_STATUS" do
      value :CREATED, 0
      value :ACTIVE, 1
      value :CANCELED, 2
      value :FAILED, 3
      value :FINISHED, 4
      value :CLOSING, 5
    end
    add_enum "GRID_ORDER_TYPE" do
      value :ARITHMETIC, 0
      value :GEOMETRIC, 1
    end
    add_enum "STOP_PRICE_TYPE" do
      value :MARK_PRICE, 0
      value :LAST_PRICE, 1
    end
    add_enum "GRID_ORDER_CLOSE_TYPE" do
      value :CLOSE_GRID_AND_POSITION, 0
      value :CLOSE_GRID, 1
    end
  end
end

module Internal
  module Types
    GridOrder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GridOrder").msgclass
    GRID_ORDER_STATUS = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GRID_ORDER_STATUS").enummodule
    GRID_ORDER_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GRID_ORDER_TYPE").enummodule
    STOP_PRICE_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("STOP_PRICE_TYPE").enummodule
    GRID_ORDER_CLOSE_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GRID_ORDER_CLOSE_TYPE").enummodule
  end
end
