# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/income.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'google/protobuf/wrappers_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/income.proto", :syntax => :proto3) do
    add_message "IncomeExtraInfo" do
      optional :OrderAmount, :message, 1, "DecimalMessage"
      optional :OrderPrice, :message, 2, "DecimalMessage"
      optional :BadDebtPrimaryAmount, :message, 3, "DecimalMessage"
      optional :BadDebtSecondaryAmount, :message, 4, "DecimalMessage"
      optional :TransferPrimaryAmount, :message, 5, "DecimalMessage"
      optional :TransferSecondaryAmount, :message, 6, "DecimalMessage"
      optional :LiquidatorTakeoverPrice, :message, 7, "DecimalMessage"
      optional :LiquidationPricePatch, :bool, 8
      optional :TradePrice, :message, 9, "DecimalMessage"
      optional :AmountType, :string, 10
      optional :LiquidationTriggerPrice, :message, 11, "DecimalMessage"
    end
    add_message "Income" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :MarketID, :string, 3
      optional :type, :enum, 4, "INCOME_TYPE"
      optional :Amount, :message, 5, "DecimalMessage"
      optional :TradeID, :message, 6, "google.protobuf.Int64Value"
      optional :TxHash, :message, 7, "HashMessage"
      optional :Time, :message, 8, "google.protobuf.Timestamp"
      optional :BlockHash, :message, 9, "HashMessage"
      optional :BlockNumber, :int64, 10
      optional :LogIndex, :message, 11, "google.protobuf.Int64Value"
      optional :ExtraInfo, :message, 12, "IncomeExtraInfo"
      optional :SourceID, :int64, 13
      optional :SourceType, :string, 14
    end
    add_enum "INCOME_TYPE" do
      value :DEPOSIT, 0
      value :WITHDRAWAL, 1
      value :LIQUIDATED, 2
      value :LIQUIDATE, 3
      value :TAKER_FEE, 4
      value :MAKER_FEE, 5
      value :BUY, 6
      value :SELL, 7
      value :FUNDING_FEE, 8
      value :COMMISSION, 9
      value :BONUS, 10
      value :SYSTEM, 11
      value :SETTLEMENT, 12
      value :TRANSFER_IN, 13
      value :TRANSFER_OUT, 14
      value :REBATE, 15
    end
  end
end

module Internal
  module Types
    IncomeExtraInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IncomeExtraInfo").msgclass
    Income = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Income").msgclass
    INCOME_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("INCOME_TYPE").enummodule
  end
end
