# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/index_price_data_source.proto

require 'google/protobuf'



Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/index_price_data_source.proto", :syntax => :proto3) do
    add_message "IndexPriceDataSource" do
      optional :ID, :uint64, 1
      optional :MarketID, :string, 2
      optional :DefaultSource, :int32, 3
      optional :BinanceKey, :string, 4
      optional :BinanceIsRawUsdc, :bool, 5
      optional :OkxKey, :string, 6
      optional :OkxIsRawUsdc, :bool, 7
      optional :BybitKey, :string, 8
      optional :BybitIsRawUsdc, :bool, 9
    end
  end
end

module Internal
  module Types
    IndexPriceDataSource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IndexPriceDataSource").msgclass
  end
end
