# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/insider_trading.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/insider_trading.proto", :syntax => :proto3) do
    add_message "InsiderTradingRule" do
      optional :ID, :int64, 1
      optional :Enable, :bool, 2
      optional :MarketID, :string, 3
      optional :MinTradingIntervalSec, :int64, 4
      optional :MaxTradingIntervalSec, :int64, 5
      optional :MinTradingVolume, :message, 6, "DecimalMessage"
      optional :MaxTradingVolume, :message, 7, "DecimalMessage"
      optional :MaxAccountRisk, :message, 8, "DecimalMessage"
      optional :MaxAccountExposure, :message, 9, "DecimalMessage"
      optional :Account0, :message, 10, "AddressMessage"
      optional :Account1, :message, 11, "AddressMessage"
      optional :MaxSpreadRate, :message, 12, "DecimalMessage"
      optional :MinVolumeByPriceRange, :message, 13, "DecimalMessage"
      optional :MinMinuteOrderCount, :int32, 14
      optional :MinNetValue, :message, 15, "DecimalMessage"
      optional :ZeroSumPosition, :bool, 16
      optional :Leverage, :message, 17, "DecimalMessage"
      optional :CreditMinRate, :int32, 18
      optional :CreditMaxRate, :int32, 19
      optional :NextTriggerTime, :message, 20, "google.protobuf.Timestamp"
      optional :TradeCount, :int32, 21
    end
  end
end

module Internal
  module Types
    InsiderTradingRule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InsiderTradingRule").msgclass
  end
end
