# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/insurance_fund_record.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/insurance_fund_record.proto", :syntax => :proto3) do
    add_message "InsuranceFundRecord" do
      optional :ID, :int64, 1
      optional :Time, :message, 2, "google.protobuf.Timestamp"
      optional :PrimaryCredit, :message, 3, "DecimalMessage"
      optional :SecondaryCredit, :message, 4, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    InsuranceFundRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InsuranceFundRecord").msgclass
  end
end
