# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/jusd_collateral.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'
require 'internal/types/market_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/jusd_collateral.proto", :syntax => :proto3) do
    add_message "JusdCollateralPosition" do
      optional :ID, :string, 1
      optional :Amount, :message, 2, "DecimalMessage"
      optional :MarkPrice, :message, 3, "DecimalMessage"
      optional :TokenAddress, :message, 4, "AddressMessage"
      optional :CreditDecimals, :int64, 5
      optional :OracleCreditDecimals, :int64, 6
    end
    add_message "CollateralMarket" do
      optional :ID, :string, 1
      optional :IsEnabled, :bool, 2
      optional :TokenAddress, :message, 3, "AddressMessage"
      optional :CreditDecimals, :int64, 4
      optional :CollateralSymbol, :string, 5
      optional :MarkPrice, :message, 6, "DecimalMessage"
      optional :OracleCreditDecimals, :int64, 7
      optional :PriceOracleAdaptorType, :enum, 8, "PriceOracleAdaptorType"
      optional :PriceOracleAdaptorAddress, :message, 9, "AddressMessage"
      optional :MarkPriceCreditDecimals, :int64, 10
      optional :PriceUnit, :string, 11
      optional :AssetPriceCreditDecimals, :int64, 12
      optional :AssetPriceAddress, :message, 13, "AddressMessage"
      optional :BorrowBalanceCreditDecimals, :int64, 14
      optional :VolumePrecision, :int64, 15
      optional :PricePrecision, :int64, 16
      optional :LiquidationMortgageRate, :message, 19, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
      optional :TID, :int64, 22
    end
    add_message "AccountCollateralState" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :BorrowBalance, :message, 3, "DecimalMessage"
      optional :EthDepositAmount, :message, 4, "DecimalMessage"
      optional :BtcDepositAmount, :message, 5, "DecimalMessage"
      optional :Risk, :message, 6, "DecimalMessage"
      repeated :Positions, :message, 7, "JusdCollateralPosition"
      optional :LiqDepositAmount, :message, 8, "DecimalMessage"
      optional :ArbDepositAmount, :message, 9, "DecimalMessage"
      optional :LinkDepositAmount, :message, 10, "DecimalMessage"
      optional :GmxDepositAmount, :message, 11, "DecimalMessage"
      optional :WstethDepositAmount, :message, 12, "DecimalMessage"
      optional :MagicDepositAmount, :message, 13, "DecimalMessage"
      optional :MUSDCDepositAmount, :message, 14, "DecimalMessage"
      optional :CbETHDepositAmount, :message, 15, "DecimalMessage"
      optional :DegenDepositAmount, :message, 16, "DecimalMessage"
      optional :AeroDepositAmount, :message, 17, "DecimalMessage"
      optional :EarnUSDCDepositAmount, :message, 18, "DecimalMessage"
      optional :JwrapMUSDCDepositAmount, :message, 19, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
      optional :WUSDMDepositAmount, :message, 22, "DecimalMessage"
      optional :PumpBTCDepositAmount, :message, 23, "DecimalMessage"
    end
  end
end

module Internal
  module Types
    JusdCollateralPosition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JusdCollateralPosition").msgclass
    CollateralMarket = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CollateralMarket").msgclass
    AccountCollateralState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountCollateralState").msgclass
  end
end
