# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/jusd_bank_event.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'google/protobuf/wrappers_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/jusd_bank_event.proto", :syntax => :proto3) do
    add_message "JusdBankEventExtraInfo" do
      optional :WithdrawReceivedAmount, :message, 1, "DecimalMessage"
    end
    add_message "JusdBankEvent" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Amount, :message, 3, "DecimalMessage"
      optional :Type, :enum, 4, "JUSD_BANK_EVENT_TYPE"
      optional :CollateralSymbol, :string, 5
      optional :TxHash, :message, 6, "HashMessage"
      optional :Time, :message, 7, "google.protobuf.Timestamp"
      optional :BlockHash, :message, 8, "HashMessage"
      optional :BlockNumber, :int64, 9
      optional :LogIndex, :message, 10, "google.protobuf.Int64Value"
      optional :ExtraInfo, :message, 11, "JusdBankEventExtraInfo"
    end
    add_enum "JUSD_BANK_EVENT_TYPE" do
      value :DEPOSIT, 0
      value :BORROW, 1
      value :REPAY, 2
      value :WITHDRAW, 3
      value :LIQUIDATE, 4
    end
  end
end

module Internal
  module Types
    JusdBankEventExtraInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JusdBankEventExtraInfo").msgclass
    JusdBankEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JusdBankEvent").msgclass
    JUSD_BANK_EVENT_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JUSD_BANK_EVENT_TYPE").enummodule
  end
end
