# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/key_event_pointer.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/key_event_pointer.proto", :syntax => :proto3) do
    add_message "KeyEventPointer" do
      optional :ID, :int64, 1
      optional :EventName, :string, 2
      optional :ExecutionCount, :int64, 3
      optional :CreatedAt, :message, 4, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 5, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    KeyEventPointer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("KeyEventPointer").msgclass
  end
end
