# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/liquidity_bot.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/types/trade_pb'
require 'internal/types/types_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/liquidity_bot.proto", :syntax => :proto3) do
    add_message "LiquidityJoJoTrade" do
      optional :ID, :int64, 1
      optional :MarketID, :string, 2
      optional :JoJoTradeID, :int64, 3
      optional :JoJoOrderID, :int64, 4
      optional :OrderSide, :enum, 5, "SIDE"
      optional :Status, :enum, 6, "TX_STATUS"
      optional :Account, :message, 7, "AddressMessage"
      optional :CounterParty, :message, 9, "AddressMessage"
      optional :Amount, :message, 10, "DecimalMessage"
      optional :Price, :message, 11, "DecimalMessage"
      optional :BinanceUserOrderID, :int64, 12
      optional :BinanceRevertUserOrderID, :int64, 13
      optional :CreatedAt, :message, 14, "google.protobuf.Timestamp"
      optional :JoJoTradeTime, :message, 15, "google.protobuf.Timestamp"
      optional :BinanceTradeTime, :message, 16, "google.protobuf.Timestamp"
      optional :BinanceRevertTradeTime, :message, 17, "google.protobuf.Timestamp"
      optional :Offset, :int64, 18
    end
    add_message "LiquidityBinanceOrder" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :MarketID, :string, 3
      optional :JoJoTradeID, :int64, 4
      optional :BinanceUserOrderID, :int64, 5
      optional :Status, :enum, 6, "TX_STATUS"
      optional :OrderAmount, :message, 7, "DecimalMessage"
      optional :FilledAmount, :message, 8, "DecimalMessage"
      optional :AskPrice, :message, 9, "DecimalMessage"
      optional :BidPrice, :message, 10, "DecimalMessage"
      optional :Time, :message, 11, "google.protobuf.Timestamp"
      optional :CreateOrderResult, :bytes, 12
      optional :OrderData, :bytes, 13
      optional :ErrorMsg, :string, 14
      optional :IsRevertOrder, :bool, 15
    end
    add_message "LiquidityHedgeProgress" do
      optional :ID, :int64, 1
      optional :MarketID, :string, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :LiquidityJoJoTradeID, :int64, 4
      optional :JoJoAmount, :message, 5, "DecimalMessage"
      optional :BinanceAmount, :message, 6, "DecimalMessage"
    end
    add_message "LiquidityJoJoTradeStatusSyncProgress" do
      optional :ID, :int64, 1
      optional :MarketID, :string, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :LiquidityJoJoTradeID, :int64, 4
    end
    add_message "LiquidityTradeDetail" do
      optional :ID, :int64, 1
      optional :MarketID, :string, 2
      optional :JoJoTradeID, :int64, 3
      optional :TradeTime, :message, 4, "google.protobuf.Timestamp"
      optional :Status, :enum, 5, "TX_STATUS"
      optional :Account, :message, 6, "AddressMessage"
      optional :Amount, :message, 7, "DecimalMessage"
      optional :Price, :message, 8, "DecimalMessage"
      optional :Fee, :message, 9, "DecimalMessage"
      optional :BinanceOrderID, :int64, 10
      optional :BinanceTradeAmount, :string, 11
      optional :BinanceTradeAvgPrice, :string, 12
      optional :BinanceTradeFee, :message, 13, "DecimalMessage"
      optional :BinanceRevertOrderID, :int64, 14
      optional :BinanceRevertTradeAmount, :string, 15
      optional :BinanceRevertTradeAvgPrice, :string, 16
      optional :BinanceRevertTradeFee, :message, 17, "DecimalMessage"
      optional :BinanceTradeData, :bytes, 18
      optional :BinanceRevertTradeData, :bytes, 19
    end
    add_message "LiquidityBotRule" do
      optional :ID, :int64, 1
      optional :EnableJoJoPlaceOrder, :bool, 2
      optional :EnableBinancePlaceOrder, :bool, 3
      optional :MarketID, :string, 4
      optional :BnSymbol, :string, 5
      optional :HalfSpread, :message, 6, "DecimalMessage"
      optional :MinHalfSpread, :message, 7, "DecimalMessage"
      optional :MaxHalfSpread, :message, 8, "DecimalMessage"
      optional :QuantityPrecision, :int32, 9
      optional :MinOrderAmount, :message, 10, "DecimalMessage"
      optional :MaxOrderVolume, :message, 11, "DecimalMessage"
      optional :MaxPositionVolume, :message, 12, "DecimalMessage"
      optional :MinBinanceOrderAmount, :message, 13, "DecimalMessage"
      optional :VolumeLimitValue, :message, 14, "DecimalMessage"
    end
    add_message "LiquidityTradeStatistic" do
      optional :ID, :int64, 1
      optional :LiquidityJoJoTradeID, :int64, 2
      optional :MarketID, :string, 3
      optional :JoJoOrderSide, :enum, 4, "SIDE"
      optional :JoJoTradeID, :int64, 5
      optional :JoJoTradeTime, :message, 6, "google.protobuf.Timestamp"
      optional :JoJoPrice, :message, 7, "DecimalMessage"
      optional :JoJoAmount, :message, 8, "DecimalMessage"
      optional :JoJoFee, :message, 9, "DecimalMessage"
      optional :BinanceOrderID, :int64, 10
      optional :BinanceTradeCount, :int64, 11
      optional :BinanceTradeTime, :message, 12, "google.protobuf.Timestamp"
      optional :BinancePrice, :message, 13, "DecimalMessage"
      optional :BinanceAmount, :message, 14, "DecimalMessage"
      optional :BinanceFee, :message, 15, "DecimalMessage"
      optional :DiffTimeMs, :int64, 16
      optional :DiffPrice, :message, 17, "DecimalMessage"
      optional :DiffPriceRatio, :message, 18, "DecimalMessage"
    end
  end
end

module Internal
  module Types
    LiquidityJoJoTrade = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LiquidityJoJoTrade").msgclass
    LiquidityBinanceOrder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LiquidityBinanceOrder").msgclass
    LiquidityHedgeProgress = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LiquidityHedgeProgress").msgclass
    LiquidityJoJoTradeStatusSyncProgress = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LiquidityJoJoTradeStatusSyncProgress").msgclass
    LiquidityTradeDetail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LiquidityTradeDetail").msgclass
    LiquidityBotRule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LiquidityBotRule").msgclass
    LiquidityTradeStatistic = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LiquidityTradeStatistic").msgclass
  end
end
