# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/market.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/types/position_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/market.proto", :syntax => :proto3) do
    add_message "LiquidationThresholdSectionItem" do
      optional :Min, :int32, 1
      optional :Max, :int32, 2
      optional :Val, :message, 3, "DecimalMessage"
    end
    add_message "LiquidationThresholdSection" do
      optional :Default, :message, 1, "DecimalMessage"
      repeated :Items, :message, 2, "LiquidationThresholdSectionItem"
    end
    add_message "Market" do
      optional :ID, :string, 1
      optional :PerpAddress, :message, 2, "AddressMessage"
      optional :IsEnabled, :bool, 3
      optional :MakerFeeRate, :message, 5, "DecimalMessage"
      optional :TakerFeeRate, :message, 6, "DecimalMessage"
      optional :MaxNumOrders, :int32, 7
      optional :MinPrice, :message, 8, "DecimalMessage"
      optional :MaxPrice, :message, 9, "DecimalMessage"
      optional :TickSize, :message, 10, "DecimalMessage"
      optional :MinAmount, :message, 11, "DecimalMessage"
      optional :MaxAmount, :message, 12, "DecimalMessage"
      optional :StepSize, :message, 13, "DecimalMessage"
      optional :Name, :string, 14
      optional :Desc, :string, 15
      optional :BaseAssetName, :string, 17
      optional :QuoteAssetName, :string, 18
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
      optional :LiquidationLeverageRate, :message, 22, "DecimalMessage"
      optional :Stage, :enum, 23, "MARKET_STAGE"
      optional :SuspendedAt, :message, 24, "google.protobuf.Timestamp"
      optional :MaxPriceOffsetTolerantPercentage, :message, 26, "DecimalMessage"
      optional :InitialLeverageRate, :message, 27, "DecimalMessage"
      optional :IsFundingRateCollectable, :bool, 28
      optional :FundingRateCollectionStartAt, :message, 29, "google.protobuf.Timestamp"
      optional :PriceOracleAdaptorType, :enum, 30, "PriceOracleAdaptorType"
      optional :PriceOracleAdaptorAddress, :message, 31, "AddressMessage"
      optional :MaxExposure, :message, 32, "DecimalMessage"
      optional :LiquidationThresholdSection, :message, 35, "LiquidationThresholdSection"
    end
    add_message "SingleMarketStatus" do
      optional :LiquidationThreshold, :message, 1, "DecimalMessage"
      optional :LiquidationPriceOff, :message, 2, "DecimalMessage"
      optional :InsuranceFeeRate, :message, 3, "DecimalMessage"
      optional :FundingRate, :message, 4, "DecimalMessage"
      optional :MarketPriceSource, :message, 5, "AddressMessage"
      optional :Perp, :message, 6, "AddressMessage"
      optional :MarkPrice, :message, 7, "DecimalMessage"
      optional :IndexPrice, :message, 8, "DecimalMessage"
      optional :MarketID, :string, 9
      optional :OffchainMarkPrice, :message, 10, "DecimalMessage"
    end
    add_message "UnitedMarket" do
      optional :Market, :message, 1, "Market"
      optional :Status, :message, 2, "SingleMarketStatus"
    end
    add_message "MarketRiskState" do
      optional :MarketID, :string, 1
      optional :TotalLongAmount, :message, 2, "DecimalMessage"
      optional :TotalShortAmount, :message, 3, "DecimalMessage"
      repeated :AccountOpeningPositions, :message, 4, "Position"
      optional :Status, :message, 5, "SingleMarketStatus"
    end
    add_enum "MARKET_STAGE" do
      value :MARKET_STAGE_CREATED, 0
      value :MARKET_STAGE_WAITING, 1
      value :MARKET_STAGE_TRADING, 2
    end
    add_enum "PriceOracleAdaptorType" do
      value :DEV, 0
      value :CHAINLINK, 1
      value :SELF_MANAGED, 2
      value :CHAINLINK_DS_ONLY, 3
    end
  end
end

module Internal
  module Types
    LiquidationThresholdSectionItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LiquidationThresholdSectionItem").msgclass
    LiquidationThresholdSection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LiquidationThresholdSection").msgclass
    Market = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Market").msgclass
    SingleMarketStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SingleMarketStatus").msgclass
    UnitedMarket = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UnitedMarket").msgclass
    MarketRiskState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MarketRiskState").msgclass
    MARKET_STAGE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MARKET_STAGE").enummodule
    PriceOracleAdaptorType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PriceOracleAdaptorType").enummodule
  end
end
