# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/mark_price.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/mark_price.proto", :syntax => :proto3) do
    add_message "MarkPrice" do
      optional :MarketID, :string, 1
      optional :Time, :message, 2, "google.protobuf.Timestamp"
      optional :Price, :message, 3, "DecimalMessage"
      optional :BlockNumber, :int64, 4
      optional :LogIndex, :int64, 5
      optional :DataSource, :int32, 6
    end
    add_message "OffchainMarkPrice" do
      optional :MarketID, :string, 1
      optional :Time, :message, 2, "google.protobuf.Timestamp"
      optional :Price, :message, 3, "DecimalMessage"
      optional :ID, :int64, 4
    end
    add_message "OffchainMarkPriceBaseData" do
      optional :MarketID, :string, 1
      optional :Time, :message, 2, "google.protobuf.Timestamp"
      optional :IndexPrice, :message, 3, "DecimalMessage"
      optional :BidPrice, :message, 4, "DecimalMessage"
      optional :AskPrice, :message, 5, "DecimalMessage"
      optional :ID, :int64, 6
    end
  end
end

module Internal
  module Types
    MarkPrice = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MarkPrice").msgclass
    OffchainMarkPrice = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OffchainMarkPrice").msgclass
    OffchainMarkPriceBaseData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OffchainMarkPriceBaseData").msgclass
  end
end
