# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/market_account.proto

require 'google/protobuf'


require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/market_account.proto", :syntax => :proto3) do
    add_message "MarketAccount" do
      optional :Name, :string, 1
      optional :MakerAccount, :message, 2, "AddressMessage"
      optional :TakerAccount, :message, 3, "AddressMessage"
      optional :ID, :int64, 4
    end
  end
end

module Internal
  module Types
    MarketAccount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MarketAccount").msgclass
  end
end
