# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/novice_activity.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/novice_activity.proto", :syntax => :proto3) do
    add_message "NoviceActivity" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :ActivityType, :string, 3
      optional :Amount, :message, 4, "DecimalMessage"
      optional :WaitingToClaimedPoints, :int64, 5
      optional :ClaimedPoints, :int64, 6
      optional :KafkaOffset, :int64, 7
      optional :LastRecordAt, :message, 8, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "NoviceActivityDetail" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :ActivityType, :string, 3
      optional :SecondaryType, :int64, 4
      optional :Amount, :message, 5, "DecimalMessage"
      optional :Points, :int64, 6
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "NoviceActivityAssociation" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :ActivityType, :string, 3
      optional :SourceID, :int64, 4
      optional :SourceType, :string, 5
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "NoviceActivityClaimLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Amount, :message, 3, "DecimalMessage"
      optional :MerkleTreeIndex, :int64, 4
      optional :MerkleTreeProof, :string, 5
      optional :ClaimedAt, :message, 6, "google.protobuf.Timestamp"
      optional :TxHash, :message, 7, "HashMessage"
      optional :BlockHash, :message, 8, "HashMessage"
      optional :BlockNumber, :int64, 9
      optional :IP, :string, 10
      optional :UserAgent, :string, 11
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    NoviceActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NoviceActivity").msgclass
    NoviceActivityDetail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NoviceActivityDetail").msgclass
    NoviceActivityAssociation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NoviceActivityAssociation").msgclass
    NoviceActivityClaimLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NoviceActivityClaimLog").msgclass
  end
end
