# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/old_account_recall_activity.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/old_account_recall_activity.proto", :syntax => :proto3) do
    add_message "OldAccountRecallActivityConfig" do
      optional :StartAt, :message, 1, "google.protobuf.Timestamp"
      optional :EndAt, :message, 2, "google.protobuf.Timestamp"
      optional :StartClaimAt, :message, 3, "google.protobuf.Timestamp"
      optional :ID, :int64, 4
    end
    add_message "OldAccountRecallActivity" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Amount, :message, 4, "DecimalMessage"
      optional :MerkleTreeIndex, :int64, 5
      optional :MerkleTreeProof, :string, 6
      optional :ClaimedAt, :message, 7, "google.protobuf.Timestamp"
      optional :TxHash, :message, 8, "HashMessage"
      optional :BlockHash, :message, 9, "HashMessage"
      optional :BlockNumber, :int64, 10
      optional :CreatedAt, :message, 11, "google.protobuf.Timestamp"
      optional :SendEmail, :bool, 12
      optional :TradeAmount, :message, 13, "DecimalMessage"
      optional :ClickEmailAt, :message, 14, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    OldAccountRecallActivityConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OldAccountRecallActivityConfig").msgclass
    OldAccountRecallActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OldAccountRecallActivity").msgclass
  end
end
