# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/open_interest.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/open_interest.proto", :syntax => :proto3) do
    add_message "OpenInterestRule" do
      optional :ID, :int64, 1
      optional :Enable, :bool, 2
      optional :MarketID, :string, 3
      optional :Account0, :message, 4, "AddressMessage"
      optional :Account1, :message, 5, "AddressMessage"
      optional :Leverage, :message, 6, "DecimalMessage"
      optional :MaxOpenRate, :message, 7, "DecimalMessage"
      optional :MinTradingVolume, :message, 8, "DecimalMessage"
      optional :MaxTradingVolume, :message, 9, "DecimalMessage"
      optional :MaxAccountRisk, :message, 10, "DecimalMessage"
      optional :MaxAccountExposure, :message, 11, "DecimalMessage"
      optional :MaxSpreadRate, :message, 12, "DecimalMessage"
      optional :MinMinuteOrderCount, :int32, 13
      optional :OtherMarketID, :string, 14
    end
  end
end

module Internal
  module Types
    OpenInterestRule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OpenInterestRule").msgclass
  end
end
