# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/order.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/types/types_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/order.proto", :syntax => :proto3) do
    add_message "TypesOrderJSON" do
      optional :Prep, :message, 1, "AddressMessage"
      optional :Singer, :message, 2, "AddressMessage"
      optional :Sender, :message, 3, "AddressMessage"
      optional :PaperAmount, :message, 4, "DecimalMessage"
      optional :CreditAmount, :message, 5, "DecimalMessage"
      optional :Info, :bytes, 6
      optional :Signature, :bytes, 7
    end
    add_message "OrderSequences" do
      repeated :Sequences, :string, 1
    end
    add_message "GasFeeInfo" do
      optional :GasLimit, :message, 1, "DecimalMessage"
      optional :GasPrice, :message, 2, "DecimalMessage"
      optional :EthIndexPrice, :message, 3, "DecimalMessage"
      optional :GasFeeOffset, :message, 4, "DecimalMessage"
    end
    add_message "Order" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :MarketID, :string, 3
      optional :Side, :enum, 4, "SIDE"
      optional :Price, :message, 5, "DecimalMessage"
      optional :TimeInForce, :enum, 6, "TIF"
      optional :AveragePrice, :message, 7, "DecimalMessage"
      optional :Status, :enum, 8, "ORDER_STATUS"
      optional :Type, :enum, 9, "OT"
      optional :Amount, :message, 10, "DecimalMessage"
      optional :AvailableAmount, :message, 11, "DecimalMessage"
      optional :FilledAmount, :message, 12, "DecimalMessage"
      optional :CanceledAmount, :message, 13, "DecimalMessage"
      optional :PendingAmount, :message, 14, "DecimalMessage"
      optional :ExpiredAmount, :message, 15, "DecimalMessage"
      optional :FailedAmount, :message, 16, "DecimalMessage"
      optional :JSON, :message, 17, "TypesOrderJSON"
      optional :Hash, :message, 18, "HashMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
      optional :Expiration, :message, 22, "google.protobuf.Timestamp"
      optional :isUsingOperatorSignature, :bool, 23
      optional :Source, :enum, 24, "ORDER_SOURCE"
      optional :HasTpsl, :bool, 25
      optional :CanceledAt, :message, 26, "google.protobuf.Timestamp"
      optional :Sequences, :message, 27, "OrderSequences"
      optional :finalReason, :string, 28
      optional :GasFeeInfo, :message, 29, "GasFeeInfo"
      optional :SourceID, :int64, 30
      optional :SourceType, :string, 31
    end
    add_enum "ORDER_STATUS" do
      value :CREATED, 0
      value :NEW, 1
      value :FILLED, 2
      value :CANCELED, 3
      value :EXPIRED, 4
      value :PARTIAL_FILLED, 5
      value :FAILED, 6
    end
    add_enum "ORDER_SOURCE" do
      value :WEB, 0
      value :APP, 1
      value :INSIDER_TRADING, 2
      value :LIQUIDITY_BOT, 3
    end
  end
end

module Internal
  module Types
    TypesOrderJSON = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TypesOrderJSON").msgclass
    OrderSequences = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderSequences").msgclass
    GasFeeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GasFeeInfo").msgclass
    Order = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Order").msgclass
    ORDER_STATUS = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ORDER_STATUS").enummodule
    ORDER_SOURCE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ORDER_SOURCE").enummodule
  end
end
