# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/orderly.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/orderly.proto", :syntax => :proto3) do
    add_message "OrderlyAccountPrivateKey" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :OrderlyKey, :string, 3
      optional :PrivateKey, :bytes, 4
      optional :Nonce, :bytes, 5
      optional :CreatedAt, :message, 6, "google.protobuf.Timestamp"
    end
    add_message "OrderlyAccountDailyAssetSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :PerpVolume, :message, 4, "DecimalMessage"
      optional :Pnl, :message, 5, "DecimalMessage"
      optional :AssetValue, :message, 6, "DecimalMessage"
      optional :RecordAt, :message, 19, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    OrderlyAccountPrivateKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderlyAccountPrivateKey").msgclass
    OrderlyAccountDailyAssetSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderlyAccountDailyAssetSnapshot").msgclass
  end
end
