# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/perp_log.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/perp_log.proto", :syntax => :proto3) do
    add_message "PerpLogExtraInfo" do
      optional :LiquidatedTrader, :message, 1, "AddressMessage"
      optional :SenderLogID, :int64, 2
      optional :LiquidationTriggerPrice, :message, 6, "DecimalMessage"
    end
    add_message "PerpLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Perp, :message, 3, "AddressMessage"
      optional :SerialNumber, :int32, 4
      optional :PaperChange, :message, 5, "DecimalMessage"
      optional :CreditChange, :message, 6, "DecimalMessage"
      optional :BlockNumber, :int64, 7
      optional :BlockHash, :message, 8, "HashMessage"
      optional :TxIndex, :int64, 9
      optional :TxHash, :message, 10, "HashMessage"
      optional :Index, :int32, 11
      optional :EventName, :enum, 12, "ProtocolEventName"
      optional :RealizedPNL, :message, 13, "DecimalMessage"
      optional :CreditChangeWithoutFee, :message, 14, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :RecordAt, :message, 21, "google.protobuf.Timestamp"
      optional :ExtraInfo, :message, 22, "PerpLogExtraInfo"
    end
    add_message "EventSyncPointer" do
      optional :EventName, :string, 1
      optional :HighestConfirmedBlockNumber, :uint64, 2
      optional :ID, :int64, 3
    end
    add_message "PrePerpLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Perp, :message, 3, "AddressMessage"
      optional :SerialNumber, :int32, 4
      optional :PaperChange, :message, 5, "DecimalMessage"
      optional :CreditChange, :message, 6, "DecimalMessage"
      optional :BlockNumber, :int64, 7
      optional :BlockHash, :message, 8, "HashMessage"
      optional :TxIndex, :int64, 9
      optional :TxHash, :message, 10, "HashMessage"
      optional :Index, :int32, 11
      optional :EventName, :enum, 12, "ProtocolEventName"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :RecordAt, :message, 21, "google.protobuf.Timestamp"
      optional :ExtraInfo, :message, 22, "PerpLogExtraInfo"
    end
    add_enum "ProtocolEventName" do
      value :OrderFilled, 0
      value :BeingLiquidated, 1
      value :JoinLiquidation, 2
      value :Deposit, 3
      value :Withdraw, 4
      value :SetOperator, 5
      value :UpdateFundingRate, 6
      value :NewSubaccount, 8
      value :TransferIn, 9
      value :TransferOut, 10
      value :BadDebt, 11
      value :NewBotSubaccount, 13
    end
  end
end

module Internal
  module Types
    PerpLogExtraInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PerpLogExtraInfo").msgclass
    PerpLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PerpLog").msgclass
    EventSyncPointer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EventSyncPointer").msgclass
    PrePerpLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PrePerpLog").msgclass
    ProtocolEventName = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProtocolEventName").enummodule
  end
end
