# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/position_snapshot.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/types/position_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/position_snapshot.proto", :syntax => :proto3) do
    add_message "PositionSnapshot" do
      optional :Account, :message, 1, "AddressMessage"
      optional :BlockNumber, :int64, 2
      optional :LogIndex, :int32, 3
      optional :MarketID, :string, 4
      optional :SerialNumber, :int32, 5
      optional :Position, :message, 6, "Position"
    end
  end
end

module Internal
  module Types
    PositionSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PositionSnapshot").msgclass
  end
end
