# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/position.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/position.proto", :syntax => :proto3) do
    add_message "Position" do
      optional :MarketID, :string, 1
      optional :Status, :string, 7
      optional :Side, :enum, 8, "PositionSide"
      optional :LongPaperChangeSum, :message, 10, "DecimalMessage"
      optional :ShortPaperChangeSum, :message, 11, "DecimalMessage"
      optional :MaxSize, :message, 12, "DecimalMessage"
      optional :LiquidatePrice, :message, 13, "DecimalMessage"
      optional :SerialStartAt, :int64, 19
      optional :RealizedPNL, :message, 20, "DecimalMessage"
      optional :UnrealizedPNL, :message, 21, "DecimalMessage"
      optional :EnterPrice, :message, 22, "DecimalMessage"
      optional :ExitPrice, :message, 23, "DecimalMessage"
      optional :CreatedAt, :message, 24, "google.protobuf.Timestamp"
      optional :ClosedAt, :message, 25, "google.protobuf.Timestamp"
      optional :LastUpdatedAt, :message, 26, "google.protobuf.Timestamp"
      optional :SerialNumber, :int64, 27
      optional :SerialIndex, :int32, 28
      optional :Account, :message, 29, "AddressMessage"
    end
    add_message "PositionChanged" do
      optional :Position, :message, 1, "Position"
      optional :Account, :message, 2, "AddressMessage"
      optional :CreatedAt, :int64, 3
    end
    add_enum "PositionSide" do
      value :LONG, 0
      value :SHORT, 1
    end
  end
end

module Internal
  module Types
    Position = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Position").msgclass
    PositionChanged = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PositionChanged").msgclass
    PositionSide = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PositionSide").enummodule
  end
end
