# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/pre_launch_activity.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/pre_launch_activity.proto", :syntax => :proto3) do
    add_message "PreLaunchActivityConfig" do
      optional :ID, :int64, 1
      optional :TotalTokenCount, :message, 2, "DecimalMessage"
      optional :EpochTotalTokenCount, :message, 3, "DecimalMessage"
      optional :EachEpochDays, :int64, 4
      optional :TotalEpochNumber, :int64, 5
      optional :StartAt, :message, 6, "google.protobuf.Timestamp"
      optional :EndAt, :message, 7, "google.protobuf.Timestamp"
    end
    add_message "PreLaunchActivity" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TaskName, :string, 3
      optional :Amount, :message, 4, "DecimalMessage"
      optional :EventPoints, :message, 5, "DecimalMessage"
      optional :EpochNumber, :int64, 6
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "PreLaunchActivityAssociation" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TaskName, :string, 3
      optional :EpochNumber, :int64, 5
      optional :SourceID, :int64, 6
      optional :SourceType, :string, 7
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "PreLaunchActivityAssetsSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :NetValue, :message, 3, "DecimalMessage"
      optional :RecordAt, :message, 8, "google.protobuf.Timestamp"
    end
    add_message "PreLaunchActivityEpochPoints" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Points, :message, 3, "DecimalMessage"
      optional :EpochNumber, :int64, 4
      optional :InviteeAccountCount, :int64, 5
      optional :EventPoints, :message, 6, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "PreLaunchActivityClaimLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Amount, :message, 3, "DecimalMessage"
      optional :MerkleTreeIndex, :int64, 4
      optional :MerkleTreeProof, :string, 5
      optional :ClaimedAt, :message, 6, "google.protobuf.Timestamp"
      optional :TxHash, :message, 7, "HashMessage"
      optional :BlockHash, :message, 8, "HashMessage"
      optional :BlockNumber, :int64, 9
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    PreLaunchActivityConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PreLaunchActivityConfig").msgclass
    PreLaunchActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PreLaunchActivity").msgclass
    PreLaunchActivityAssociation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PreLaunchActivityAssociation").msgclass
    PreLaunchActivityAssetsSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PreLaunchActivityAssetsSnapshot").msgclass
    PreLaunchActivityEpochPoints = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PreLaunchActivityEpochPoints").msgclass
    PreLaunchActivityClaimLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PreLaunchActivityClaimLog").msgclass
  end
end
