# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/profit_snapshot.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/profit_snapshot.proto", :syntax => :proto3) do
    add_message "ProfitSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Profit, :message, 3, "DecimalMessage"
      optional :CumulativeProfit, :message, 4, "DecimalMessage"
      optional :RecordAt, :message, 5, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    ProfitSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProfitSnapshot").msgclass
  end
end
