# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/referral_record.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/referral_record.proto", :syntax => :proto3) do
    add_message "ReferralRecord" do
      optional :ID, :int64, 1
      optional :InviterAccount, :message, 2, "AddressMessage"
      optional :InviteeAccount, :message, 3, "AddressMessage"
      optional :CreatedAt, :message, 4, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 5, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    ReferralRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ReferralRecord").msgclass
  end
end
