# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/referral_account.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/referral_account.proto", :syntax => :proto3) do
    add_message "ReferralAccount" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :ReferralCode, :string, 3
      optional :InviterRebateRatio, :int64, 4
      optional :InviteeRebateRatio, :int64, 5
      optional :CreatedAt, :message, 6, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 7, "google.protobuf.Timestamp"
      optional :TotalRebateRatio, :int64, 8
      optional :Role, :string, 9
    end
  end
end

module Internal
  module Types
    ReferralAccount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ReferralAccount").msgclass
  end
end
