# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/s2_airdrop_farm_activity.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/s2_airdrop_farm_activity.proto", :syntax => :proto3) do
    add_message "S2AirdropFarmActivityConfig" do
      optional :ID, :int64, 1
      optional :TotalTokenCount, :message, 2, "DecimalMessage"
      optional :EpochTotalTokenCount, :message, 3, "DecimalMessage"
      optional :EachEpochDays, :int64, 4
      optional :TotalEpochNumber, :int64, 5
      optional :StartAt, :message, 6, "google.protobuf.Timestamp"
      optional :EndAt, :message, 7, "google.protobuf.Timestamp"
    end
    add_message "S2AirdropFarmActivity" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TaskName, :string, 3
      optional :Amount, :message, 4, "DecimalMessage"
      optional :EventPoints, :message, 5, "DecimalMessage"
      optional :EpochNumber, :int64, 6
      optional :LpUSDCAmount, :message, 7, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "S2AirdropFarmActivityAssociation" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TaskName, :string, 3
      optional :SourceID, :int64, 4
      optional :SourceType, :string, 5
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "S2AirdropFarmActivityAssetsSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :NetValue, :message, 3, "DecimalMessage"
      optional :RecordAt, :message, 8, "google.protobuf.Timestamp"
    end
    add_message "S2AirdropFarmActivityEpochPoints" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :EventPoints, :message, 3, "DecimalMessage"
      optional :Tokens, :message, 4, "DecimalMessage"
      optional :EpochNumber, :int64, 5
      optional :InviteeAccountCount, :int64, 6
      optional :VipLevel, :int64, 7
      optional :TradeVolume, :message, 8, "DecimalMessage"
      optional :DailyAverageTVL, :message, 9, "DecimalMessage"
      optional :DailyCommittedLP, :message, 10, "DecimalMessage"
      optional :RecordAt, :message, 19, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "S2AirdropFarmCommittedLPSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :CommittedLPAmount, :message, 3, "DecimalMessage"
      optional :StakeLPAmount, :message, 4, "DecimalMessage"
      optional :RecordAt, :message, 19, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "S2AirdropFarmActivityClaimLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Amount, :message, 3, "DecimalMessage"
      optional :MerkleTreeIndex, :int64, 4
      optional :MerkleTreeProof, :string, 5
      optional :ClaimedAt, :message, 6, "google.protobuf.Timestamp"
      optional :TxHash, :message, 7, "HashMessage"
      optional :BlockHash, :message, 8, "HashMessage"
      optional :BlockNumber, :int64, 9
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    S2AirdropFarmActivityConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("S2AirdropFarmActivityConfig").msgclass
    S2AirdropFarmActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("S2AirdropFarmActivity").msgclass
    S2AirdropFarmActivityAssociation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("S2AirdropFarmActivityAssociation").msgclass
    S2AirdropFarmActivityAssetsSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("S2AirdropFarmActivityAssetsSnapshot").msgclass
    S2AirdropFarmActivityEpochPoints = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("S2AirdropFarmActivityEpochPoints").msgclass
    S2AirdropFarmCommittedLPSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("S2AirdropFarmCommittedLPSnapshot").msgclass
    S2AirdropFarmActivityClaimLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("S2AirdropFarmActivityClaimLog").msgclass
  end
end
