# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/senderlog.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'
require 'google/protobuf/wrappers_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/senderlog.proto", :syntax => :proto3) do
    add_message "SenderLog" do
      optional :ID, :int64, 1
      optional :From, :message, 2, "AddressMessage"
      optional :To, :message, 3, "AddressMessage"
      optional :Value, :message, 4, "DecimalMessage"
      optional :Hash, :message, 5, "HashMessage"
      optional :GasLimit, :uint64, 6
      optional :GasPrice, :message, 7, "DecimalMessage"
      optional :GasUsed, :uint64, 8
      optional :Nonce, :message, 9, "google.protobuf.Int64Value"
      optional :Status, :enum, 10, "SENDER_LOG_STATUS"
      optional :Data, :bytes, 11
      optional :Source, :string, 12
      optional :Namespace, :string, 13
      optional :ErrorMessage, :string, 14
      optional :EthPrice, :message, 15, "DecimalMessage"
      optional :HashOfFailedChaining, :message, 16, "HashMessage"
      optional :SettledAt, :message, 19, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
      optional :FinishedSendingAt, :message, 22, "google.protobuf.Timestamp"
      optional :GasFeeCap, :uint64, 23
      optional :GasTipCap, :uint64, 24
      optional :NodeName, :string, 25
    end
    add_message "SenderConfig" do
      optional :ID, :int64, 1
      optional :EnableGasFeeSimulator, :bool, 2
      optional :EnableWatchOrderFilledLog, :bool, 3
      optional :EnablePollingPendingLogReceipt, :bool, 4
      optional :PollingPendingLogReceiptIntervalMS, :int64, 5
      optional :EnableRetryPendingLogLoop, :bool, 6
      optional :PollingRetryPendingLogLongIntervalMS, :int64, 7
      optional :PollingRetryPendingLogShortIntervalMS, :int64, 8
      optional :RetryPendingLogThresholdSeconds, :int64, 9
      optional :MaxRetryPendingLogCountByFrom, :int64, 10
      optional :PollingPendingLogReceiptCountPerMinute, :int64, 11
      optional :PollingPendingLogReceiptShortIntervalMSPerID, :int64, 12
      optional :PollingPendingLogReceiptLongIntervalMSPerID, :int64, 13
      optional :NewSenderLogRetryTime, :int32, 14
      optional :WsReadNode, :string, 15
      optional :RestReadNode, :string, 16
      optional :RestWriteNode, :string, 17
      repeated :RestBackUpWriteNode, :string, 18
      optional :EnableRetryByBackUpNode, :bool, 19
      optional :GasIncreaseMultiplier, :message, 20, "DecimalMessage"
      optional :GasTipCapIncreaseMultiplier, :message, 21, "DecimalMessage"
      optional :GasTipCapRetryIncreaseMultiplier, :message, 22, "DecimalMessage"
      optional :GasTipCapMaxRetryMultiplier, :message, 23, "DecimalMessage"
      optional :GasFeeCapIncreaseMultiplier, :message, 24, "DecimalMessage"
      optional :GasFeeCapRetryIncreaseMultiplier, :message, 25, "DecimalMessage"
      optional :GasFeeCapMaxRetryMultiplier, :message, 26, "DecimalMessage"
      map :CustomizeChainNoncesMap, :string, :int64, 27
      map :MaxPendingLogCountByFromAddressMap, :string, :int64, 28
      optional :DefaultMaxPendingLogCountPerFromAddress, :int64, 29
      optional :RetryByBackUpNodeIntervalSec, :int64, 30
    end
    add_enum "SENDER_LOG_STATUS" do
      value :PENDING, 0
      value :SUCCESSFUL, 1
      value :FAILED, 2
      value :RETRIED, 3
      value :CREATED, 4
      value :FAST_FAILED, 5
      value :OUT_OF_GAS_RETRIED, 6
    end
  end
end

module Internal
  module Types
    SenderLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SenderLog").msgclass
    SenderConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SenderConfig").msgclass
    SENDER_LOG_STATUS = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SENDER_LOG_STATUS").enummodule
  end
end
