# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/sensitive_word.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/sensitive_word.proto", :syntax => :proto3) do
    add_message "SensitiveWord" do
      optional :ID, :int64, 1
      optional :Word, :string, 2
      optional :CreatedAt, :message, 4, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 5, "google.protobuf.Timestamp"
    end
    add_message "WhitelistWord" do
      optional :ID, :int64, 1
      optional :Word, :string, 2
      optional :CreatedAt, :message, 4, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 5, "google.protobuf.Timestamp"
    end
  end
end

SensitiveWord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SensitiveWord").msgclass
WhitelistWord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WhitelistWord").msgclass
