# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/set_operator_event.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/set_operator_event.proto", :syntax => :proto3) do
    add_message "SetOperatorEvent" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Operator, :message, 3, "AddressMessage"
      optional :IsValid, :bool, 4
      optional :BlockNumber, :int64, 7
      optional :BlockHash, :message, 8, "HashMessage"
      optional :Index, :int32, 11
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    SetOperatorEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SetOperatorEvent").msgclass
  end
end
