# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/slot_machine_draw.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/slot_machine_draw.proto", :syntax => :proto3) do
    add_message "SlotMachineDrawConfig" do
      optional :ID, :int64, 1
      optional :StartAt, :message, 2, "google.protobuf.Timestamp"
      optional :EndAt, :message, 3, "google.protobuf.Timestamp"
      optional :LotteryEndAt, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "SlotMachineDrawActivity" do
      optional :ID, :int64, 1
      optional :ConfigID, :int64, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :TicketsCount, :int64, 4
      optional :TaskName, :string, 5
      optional :TradeAmount, :message, 6, "DecimalMessage"
      optional :LotteryToken, :string, 7
      optional :LotteryPrize, :int64, 8
      optional :Status, :string, 9
      optional :SenderLogID, :int64, 10
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "SlotMachineDrawActivityAssociation" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :TaskName, :string, 3
      optional :SourceID, :int64, 4
      optional :SourceType, :string, 5
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    SlotMachineDrawConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SlotMachineDrawConfig").msgclass
    SlotMachineDrawActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SlotMachineDrawActivity").msgclass
    SlotMachineDrawActivityAssociation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SlotMachineDrawActivityAssociation").msgclass
  end
end
