# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/strade.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/types/types_pb'
require 'internal/types/trade_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/strade.proto", :syntax => :proto3) do
    add_message "Trade" do
      optional :ID, :int64, 1
      optional :TransactionID, :int64, 2
      optional :Status, :enum, 3, "TX_STATUS"
      optional :MarketID, :string, 4
      optional :OrderID, :int64, 5
      optional :CounterOrderID, :int64, 6
      optional :Amount, :message, 8, "DecimalMessage"
      optional :Price, :message, 9, "DecimalMessage"
      optional :Account, :message, 10, "AddressMessage"
      optional :Fee, :message, 11, "DecimalMessage"
      optional :CounterParty, :message, 12, "AddressMessage"
      optional :Sequence, :uint64, 13
      optional :IsMaker, :bool, 15
      optional :IsBuyer, :bool, 16
      optional :GasFee, :message, 17, "DecimalMessage"
      optional :SettledAt, :message, 19, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
      optional :TimeInForce, :enum, 22, "TIF"
      optional :RealizedPNL, :message, 24, "DecimalMessage"
      optional :OrderType, :enum, 27, "OT"
      optional :OrderHash, :message, 28, "HashMessage"
    end
  end
end

module Internal
  module Types
    Trade = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Trade").msgclass
  end
end
