# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/subaccount.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'
require 'internal/ext/json_message_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/subaccount.proto", :syntax => :proto3) do
    add_message "Subaccount" do
      optional :ID, :int64, 1
      optional :Owner, :message, 2, "AddressMessage"
      optional :Account, :message, 3, "AddressMessage"
      optional :OperatorNicknames, :message, 5, "JsonMessage"
      optional :NicknameFromOperators, :message, 6, "JsonMessage"
      optional :BlockNumber, :int64, 7
      optional :BlockHash, :message, 8, "HashMessage"
      optional :Index, :int32, 11
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :SubaccountType, :enum, 21, "SUBACCOUNT_TYPE"
    end
    add_enum "SUBACCOUNT_TYPE" do
      value :NORMAL, 0
      value :BOT, 2
      value :ISOLATED_MARGIN_BOT, 3
    end
  end
end

module Internal
  module Types
    Subaccount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Subaccount").msgclass
    SUBACCOUNT_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SUBACCOUNT_TYPE").enummodule
  end
end
