# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/tpsl_order.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/types/types_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/tpsl_order.proto", :syntax => :proto3) do
    add_message "TpslOrder" do
      optional :ID, :int64, 1
      optional :OrderID, :int64, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :MarketID, :string, 4
      optional :Side, :enum, 5, "SIDE"
      optional :Amount, :message, 6, "DecimalMessage"
      optional :TriggerPrice, :message, 7, "DecimalMessage"
      optional :TriggerType, :enum, 8, "TRIGGER_TYPE"
      optional :OrderPrice, :message, 9, "DecimalMessage"
      optional :OrderType, :enum, 10, "OT"
      optional :TpslType, :enum, 11, "TPSL_TYPE"
      optional :TpslOrderType, :enum, 12, "TPSL_ORDER_TYPE"
      optional :Status, :enum, 13, "TPSL_STATUS"
      optional :FailedReason, :string, 14
      optional :TriggerAt, :message, 15, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 16, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 17, "google.protobuf.Timestamp"
      optional :OtherSideID, :int64, 18
      optional :TriggeredOrderID, :int64, 19
      optional :TriggerDirection, :enum, 20, "TPSL_TRIGGER_DIRECTION"
      optional :ParentTpslOrderID, :int64, 21
      optional :OrderErrorReason, :string, 22
      optional :TimeInForce, :enum, 23, "TIF"
    end
    add_enum "TRIGGER_TYPE" do
      value :MARK_PRICE, 0
      value :LAST_PRICE, 1
      value :MARK_PRICE_OR_LAST_PRICE, 2
    end
    add_enum "TPSL_TYPE" do
      value :TAKER_PROFIT, 0
      value :STOP_LOSS, 1
    end
    add_enum "TPSL_ORDER_TYPE" do
      value :TPSL_ORDER, 0
      value :TPSL_POSITION, 1
      value :TPSL_STOP_LIMIT_ORDER, 2
      value :TPSL_REDUCE_ONLY, 3
    end
    add_enum "TPSL_STATUS" do
      value :CREATED, 0
      value :INACTIVATED, 1
      value :WAIT_PENDING, 2
      value :PENDING, 3
      value :SUCCESSFUL, 4
      value :CANCELED, 5
      value :FAILED, 6
      value :EXPIRED, 7
    end
    add_enum "TPSL_TRIGGER_DIRECTION" do
      value :GREATER_OR_EQUAL, 0
      value :LESS_OR_EQUAL, 1
    end
  end
end

module Internal
  module Types
    TpslOrder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TpslOrder").msgclass
    TRIGGER_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TRIGGER_TYPE").enummodule
    TPSL_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TPSL_TYPE").enummodule
    TPSL_ORDER_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TPSL_ORDER_TYPE").enummodule
    TPSL_STATUS = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TPSL_STATUS").enummodule
    TPSL_TRIGGER_DIRECTION = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TPSL_TRIGGER_DIRECTION").enummodule
  end
end
