# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/trade_volume_snapshot.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/trade_volume_snapshot.proto", :syntax => :proto3) do
    add_message "TradeVolumeSnapshot" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Volume, :message, 3, "DecimalMessage"
      optional :Previous6daysVolume, :message, 4, "DecimalMessage"
      optional :Previous29daysVolume, :message, 5, "DecimalMessage"
      optional :TotalVolume, :message, 6, "DecimalMessage"
      optional :RecordAt, :message, 7, "google.protobuf.Timestamp"
      optional :CurrentMonthVolume, :message, 8, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    TradeVolumeSnapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TradeVolumeSnapshot").msgclass
  end
end
