# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/trade.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/trade.proto", :syntax => :proto3) do
    add_enum "TX_STATUS" do
      value :TX_CREATED, 0
      value :TX_PENDING, 1
      value :TX_FAILED, 2
      value :TX_SETTLED, 3
    end
  end
end

module Internal
  module Types
    TX_STATUS = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TX_STATUS").enummodule
  end
end
