# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/trade_volume_analysis_log.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/trade_volume_analysis_log.proto", :syntax => :proto3) do
    add_message "TradeVolumeAnalysisLog" do
      optional :ID, :int64, 1
      optional :MarketID, :string, 2
      optional :DegenBotAmount, :message, 3, "DecimalMessage"
      optional :DegenUserAmount, :message, 4, "DecimalMessage"
      optional :PerpBotAmount, :message, 5, "DecimalMessage"
      optional :PerpUserAmount, :message, 6, "DecimalMessage"
      optional :PerpShadowAmount, :message, 7, "DecimalMessage"
      optional :DegenBotFee, :message, 8, "DecimalMessage"
      optional :DegenUserFee, :message, 9, "DecimalMessage"
      optional :PerpBotFee, :message, 10, "DecimalMessage"
      optional :PerpBotGasFee, :message, 11, "DecimalMessage"
      optional :PerpUserFee, :message, 12, "DecimalMessage"
      optional :PerpUserGasFee, :message, 13, "DecimalMessage"
      optional :PerpShadowFee, :message, 14, "DecimalMessage"
      optional :PerpShadowGasFee, :message, 15, "DecimalMessage"
      optional :SenderPerpBotFee, :message, 16, "DecimalMessage"
      optional :SenderPerpUserFee, :message, 17, "DecimalMessage"
      optional :SenderDegenFee, :message, 18, "DecimalMessage"
      optional :SenderOracleFee, :message, 19, "DecimalMessage"
      optional :SenderOtherFee, :message, 20, "DecimalMessage"
      optional :PerpOpenInterestBotAmount, :message, 21, "DecimalMessage"
      optional :PerpOpenInterestBotFee, :message, 22, "DecimalMessage"
      optional :PerpOpenInterestBotGasFee, :message, 23, "DecimalMessage"
      optional :InsurancePNL, :message, 24, "DecimalMessage"
      optional :LiquidationAmount, :message, 25, "DecimalMessage"
      optional :UserJojoTokenCount, :message, 26, "DecimalMessage"
      optional :PerpManifoldFee, :message, 27, "DecimalMessage"
      optional :PerpManifoldAmount, :message, 28, "DecimalMessage"
      optional :RecordAt, :message, 30, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 31, "google.protobuf.Timestamp"
      optional :LiquidityProviderBotAmount, :message, 32, "DecimalMessage"
      optional :LiquidityProviderBotFee, :message, 33, "DecimalMessage"
    end
    add_message "TradeVolumeAnalysisAssociation" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :SourceID, :int64, 3
      optional :SourceType, :string, 4
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "AccountTradeVolumeLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :PerpetualTradeAmount, :message, 3, "DecimalMessage"
      optional :DegenTradeAmount, :message, 4, "DecimalMessage"
      optional :PerpetualNetValue, :message, 6, "DecimalMessage"
      optional :DegenNetValue, :message, 7, "DecimalMessage"
      optional :TotalPerpetualTradeAmount, :message, 8, "DecimalMessage"
      optional :TotalDegenTradeAmount, :message, 9, "DecimalMessage"
      optional :PerpetualCumulativeProfit, :message, 10, "DecimalMessage"
      optional :PerpetualProfit, :message, 11, "DecimalMessage"
      optional :DegenCumulativeProfit, :message, 12, "DecimalMessage"
      optional :DegenProfit, :message, 13, "DecimalMessage"
      optional :RecordAt, :message, 30, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 31, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 32, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Types
    TradeVolumeAnalysisLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TradeVolumeAnalysisLog").msgclass
    TradeVolumeAnalysisAssociation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TradeVolumeAnalysisAssociation").msgclass
    AccountTradeVolumeLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountTradeVolumeLog").msgclass
  end
end
