# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/tx.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/types/trade_pb'
require 'internal/types/strade_pb'
require 'internal/types/order_pb'
require 'internal/ext/hash_pb'
require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/tx.proto", :syntax => :proto3) do
    add_message "BlockchainSettlementComponent" do
      optional :Sequence, :uint64, 1
      optional :MarketID, :string, 2
      optional :TradeID, :int64, 3
      optional :Trade, :message, 4, "Trade"
      optional :Order, :message, 5, "TypesOrderJSON"
      optional :CreatedAt, :message, 6, "google.protobuf.Timestamp"
    end
    add_message "BlockchainSettlement" do
      optional :Sequence, :uint64, 1
      optional :MarketID, :string, 2
      optional :MakersCount, :int32, 3
      optional :Status, :enum, 4, "BlockchainSettlementComponentStatus"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_message "TransactionJSON" do
    end
    add_message "Transaction" do
      optional :ID, :int64, 1
      optional :Status, :enum, 2, "TX_STATUS"
      optional :MarketID, :string, 3
      optional :Hash, :message, 4, "HashMessage"
      optional :Data, :bytes, 5
      optional :Sequence, :uint64, 6
      optional :SettledAt, :message, 19, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "TransactionTrade" do
      optional :TransactionID, :int64, 1
      optional :TradeID, :int64, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :MarketID, :string, 4
      optional :Sequence, :uint64, 5
    end
    add_enum "BlockchainSettlementComponentStatus" do
      value :BlockchainSettlementComponentStatus_CREATED, 0
      value :BlockchainSettlementComponentStatus_SUBMITTED, 1
    end
  end
end

module Internal
  module Types
    BlockchainSettlementComponent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BlockchainSettlementComponent").msgclass
    BlockchainSettlement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BlockchainSettlement").msgclass
    TransactionJSON = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TransactionJSON").msgclass
    Transaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Transaction").msgclass
    TransactionTrade = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TransactionTrade").msgclass
    BlockchainSettlementComponentStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BlockchainSettlementComponentStatus").enummodule
  end
end
