# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/types.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/types.proto", :syntax => :proto3) do
    add_enum "SIDE" do
      value :BUY, 0
      value :SELL, 1
    end
    add_enum "TIF" do
      value :GTC, 0
      value :IOC, 1
      value :FOK, 2
      value :POST_ONLY, 3
      value :GTT, 4
    end
    add_enum "OT" do
      value :LIMIT, 0
      value :MARKET, 1
    end
  end
end

module Internal
  module Types
    SIDE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SIDE").enummodule
    TIF = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TIF").enummodule
    OT = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OT").enummodule
  end
end
