# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/vejojo.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/vejojo.proto", :syntax => :proto3) do
    add_message "VeJOJOEvent" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :LockID, :int64, 3
      optional :JOJOAmount, :message, 4, "DecimalMessage"
      optional :Type, :enum, 5, "VE_JOJO_TYPE"
      optional :LockTime, :int64, 6
      optional :BlockNumber, :int64, 7
      optional :BlockHash, :message, 8, "HashMessage"
      optional :TxHash, :message, 10, "HashMessage"
      optional :Index, :int32, 11
      optional :VeJOJOAmount, :message, 12, "DecimalMessage"
      optional :WithdrawalAt, :message, 13, "google.protobuf.Timestamp"
      optional :WithdrawalTxHash, :message, 14, "HashMessage"
      optional :UnLockAt, :message, 15, "google.protobuf.Timestamp"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "VeJOJOReward" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Amount, :message, 3, "DecimalMessage"
      optional :Status, :enum, 4, "VE_JOJO_REWARD_STATUS"
      optional :BlockHash, :message, 5, "HashMessage"
      optional :TxHash, :message, 6, "HashMessage"
      optional :Index, :int32, 7
      optional :BlockNumber, :int64, 8
      optional :AssetMovementID, :int64, 9
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "VeJOJOAccountState" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :VeJOJOAmount, :message, 3, "DecimalMessage"
      optional :JOJOAmount, :message, 4, "DecimalMessage"
      optional :TotalUSDCReward, :message, 5, "DecimalMessage"
      optional :UnclaimedUSDCReward, :message, 6, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "VeJOJOAprKline" do
      optional :ID, :int64, 1
      optional :APR, :message, 2, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_message "VeJOJORewardSummaryLog" do
      optional :ID, :int64, 1
      optional :TotalUserUSDCReward, :message, 2, "DecimalMessage"
      optional :TotalBotUSDCReward, :message, 3, "DecimalMessage"
      optional :TotalUserJOJOAmount, :message, 4, "DecimalMessage"
      optional :TotalBotJOJOAmount, :message, 5, "DecimalMessage"
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
      optional :UpdatedAt, :message, 21, "google.protobuf.Timestamp"
    end
    add_enum "VE_JOJO_TYPE" do
      value :DEPOSIT, 0
      value :WITHDRAW, 1
    end
    add_enum "VE_JOJO_REWARD_STATUS" do
      value :UNCLAIMED, 0
      value :CLAIMED, 1
    end
  end
end

module Internal
  module Types
    VeJOJOEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VeJOJOEvent").msgclass
    VeJOJOReward = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VeJOJOReward").msgclass
    VeJOJOAccountState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VeJOJOAccountState").msgclass
    VeJOJOAprKline = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VeJOJOAprKline").msgclass
    VeJOJORewardSummaryLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VeJOJORewardSummaryLog").msgclass
    VE_JOJO_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VE_JOJO_TYPE").enummodule
    VE_JOJO_REWARD_STATUS = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VE_JOJO_REWARD_STATUS").enummodule
  end
end
