# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/warpcast_activity.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/warpcast_activity.proto", :syntax => :proto3) do
    add_message "WarpcastActivity" do
      optional :ID, :int64, 1
      optional :Status, :string, 2
      optional :RewardType, :string, 3
      optional :TotalRewardTokenCount, :message, 4, "DecimalMessage"
      optional :RewardTokenPerUser, :message, 5, "DecimalMessage"
      optional :DistributedRewardTokenCount, :message, 6, "DecimalMessage"
      optional :RewardTokenAddress, :message, 7, "AddressMessage"
    end
    add_message "WarpcastActivityClaimLog" do
      optional :ID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :WarpcastActivityID, :int64, 3
      optional :Fid, :string, 4
      optional :Stage, :enum, 5, "WarpcastActivityClaimLogStage"
      optional :SenderLogID, :int64, 6
      optional :IP, :string, 7
      optional :UserAgent, :string, 8
      optional :CreatedAt, :message, 20, "google.protobuf.Timestamp"
    end
    add_enum "WarpcastActivityClaimLogStage" do
      value :WARPCAST_ACTIVITY_CLAIM_LOG_STAGE_CREATED, 0
      value :WARPCAST_ACTIVITY_CLAIM_LOG_STAGE_FAILED, 2
      value :WARPCAST_ACTIVITY_CLAIM_LOG_STAGE_SUCCESSFUL, 3
    end
  end
end

module Internal
  module Types
    WarpcastActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WarpcastActivity").msgclass
    WarpcastActivityClaimLog = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WarpcastActivityClaimLog").msgclass
    WarpcastActivityClaimLogStage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WarpcastActivityClaimLogStage").enummodule
  end
end
