# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/watcher.proto

require 'google/protobuf'



Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/watcher.proto", :syntax => :proto3) do
    add_message "WatcherRecord" do
      optional :LastProcessedBlockNumber, :uint64, 1
      optional :ID, :string, 2
    end
  end
end

module Internal
  module Types
    WatcherRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WatcherRecord").msgclass
  end
end
