# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/types/wrapped_assets_mark_price.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/types/wrapped_assets_mark_price.proto", :syntax => :proto3) do
    add_message "WrappedAssetsMarkPrice" do
      optional :CollateralMarketID, :string, 1
      optional :Time, :message, 2, "google.protobuf.Timestamp"
      optional :Price, :message, 3, "DecimalMessage"
      optional :BlockNumber, :int64, 4
      optional :LogIndex, :int64, 5
    end
  end
end

module Internal
  module Types
    WrappedAssetsMarkPrice = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WrappedAssetsMarkPrice").msgclass
  end
end
