# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/degen/degen_asset_monitor/server.proto for package 'Internal.DegenAssetMonitor'

require 'grpc'
require 'internal/degen/degen_asset_monitor/server_pb'

module Internal
  module DegenAssetMonitor
    module MonitorService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'MonitorService'

        rpc :GetAggregatePosition, ::Internal::DegenAssetMonitor::GetAggregatePositionRequest, ::Internal::DegenAssetMonitor::GetAggregatePositionResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
