# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/degen/degen_asset_monitor/server.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/types/degen_position_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/degen/degen_asset_monitor/server.proto", :syntax => :proto3) do
    add_message "GetAggregatePositionRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "GetAggregatePositionResponse" do
      optional :AggregatePosition, :message, 1, "DegenAggregatePosition"
    end
  end
end

module Internal
  module DegenAssetMonitor
    GetAggregatePositionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAggregatePositionRequest").msgclass
    GetAggregatePositionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAggregatePositionResponse").msgclass
  end
end
