# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/calculation/server.proto for package 'Internal.Calculation'

require 'grpc'
require 'internal/calculation/server_pb'

module Internal
  module Calculation
    module CalcService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'CalcService'

        rpc :GetMarketStatus, ::Internal::Calculation::GetMarketStatusRequest, ::Internal::Types::UnitedMarket
        rpc :GetAllMarketStatus, ::Internal::Calculation::GetAllMarketStatusRequest, ::Internal::Calculation::GetAllMarketStatusResponse
        rpc :WatchAllMarketStatus, ::Internal::Calculation::GetAllMarketStatusRequest, stream(::Internal::Types::UnitedMarket)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
