# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/calculation/server.proto

require 'google/protobuf'

require 'internal/types/market_pb'


Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/calculation/server.proto", :syntax => :proto3) do
    add_message "GetAllMarketStatusRequest" do
    end
    add_message "GetMarketStatusRequest" do
      optional :MarketID, :string, 1
    end
    add_message "GetAllMarketStatusResponse" do
      map :Markets, :string, :message, 1, "UnitedMarket"
    end
  end
end

module Internal
  module Calculation
    GetAllMarketStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAllMarketStatusRequest").msgclass
    GetMarketStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMarketStatusRequest").msgclass
    GetAllMarketStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAllMarketStatusResponse").msgclass
  end
end
