# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/postprocessing/tpsl_types.proto

require 'google/protobuf'


require 'internal/types/order_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/postprocessing/tpsl_types.proto", :syntax => :proto3) do
    add_message "OrderHasTpslResult" do
      optional :ID, :int64, 1
      optional :MarketID, :string, 2
      optional :Status, :enum, 3, "ORDER_STATUS"
      optional :Amount, :message, 4, "DecimalMessage"
      optional :AvailableAmount, :message, 5, "DecimalMessage"
    end
    add_message "DBProcessorOrderHasTpslResult" do
      repeated :orderHasTpslResults, :message, 1, "OrderHasTpslResult"
      optional :Sequence, :uint64, 2
      map :Context, :string, :string, 3
    end
  end
end

module Internal
  module Postprocessing
    OrderHasTpslResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderHasTpslResult").msgclass
    DBProcessorOrderHasTpslResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DBProcessorOrderHasTpslResult").msgclass
  end
end
