# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/check_in_activity/server.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/check_in_activity/server.proto", :syntax => :proto3) do
    add_message "GetCheckInActivityBriefRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "CheckInDailyActivity" do
      optional :PerpetualTradePoints, :message, 1, "DecimalMessage"
      optional :DegenTradePoints, :message, 2, "DecimalMessage"
      optional :PerpetualPNLPoints, :message, 3, "DecimalMessage"
      optional :DegenPNLPoints, :message, 4, "DecimalMessage"
      optional :ContinuousCheckInPoints, :message, 5, "DecimalMessage"
      optional :TotalPoints, :message, 6, "DecimalMessage"
      optional :Day, :int64, 7
      optional :StartAt, :int64, 8
      optional :EndAt, :int64, 9
    end
    add_message "GetCheckInActivityBriefResponse" do
      repeated :DailyActivities, :message, 1, "CheckInDailyActivity"
      optional :StartAt, :int64, 2
      optional :EndAt, :int64, 3
      optional :TotalRewardAmount, :message, 4, "DecimalMessage"
      optional :RewardAt, :int64, 5
      optional :HaveEmail, :bool, 6
    end
    add_message "ClaimCheckInActivityRewardRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :IP, :string, 2
    end
    add_message "ClaimCheckInActivityRewardResponse" do
      optional :ErrorMessage, :enum, 1, "CHECK_IN_ACTIVITY_ERROR_CODE"
    end
    add_enum "CHECK_IN_ACTIVITY_ERROR_CODE" do
      value :NO_ERROR, 0
      value :WRONG_CLAIM_TIME_ERROR, 1
      value :IP_CLAIMED_ERROR, 2
      value :ACCOUNT_CLAIMED_ERROR, 3
      value :NO_CLAIM_LOG_ERROR, 4
      value :SYSTEM_ERROR, 5
    end
  end
end

module Internal
  module CheckInActivityProcessor
    GetCheckInActivityBriefRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetCheckInActivityBriefRequest").msgclass
    CheckInDailyActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CheckInDailyActivity").msgclass
    GetCheckInActivityBriefResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetCheckInActivityBriefResponse").msgclass
    ClaimCheckInActivityRewardRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ClaimCheckInActivityRewardRequest").msgclass
    ClaimCheckInActivityRewardResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ClaimCheckInActivityRewardResponse").msgclass
    CHECK_IN_ACTIVITY_ERROR_CODE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CHECK_IN_ACTIVITY_ERROR_CODE").enummodule
  end
end
