# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/check_in_activity/server.proto for package 'Internal.CheckInActivityProcessor'

require 'grpc'
require 'internal/check_in_activity/server_pb'

module Internal
  module CheckInActivityProcessor
    module CheckInActivity
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'CheckInActivity'

        rpc :GetCheckInActivityBrief, ::Internal::CheckInActivityProcessor::GetCheckInActivityBriefRequest, ::Internal::CheckInActivityProcessor::GetCheckInActivityBriefResponse
        rpc :ClaimCheckInActivityReward, ::Internal::CheckInActivityProcessor::ClaimCheckInActivityRewardRequest, ::Internal::CheckInActivityProcessor::ClaimCheckInActivityRewardResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
