# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/referral/server.proto

require 'google/protobuf'


require 'internal/ext/address_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/referral/server.proto", :syntax => :proto3) do
    add_message "GetReferralCodeRequest" do
      optional :Address, :message, 1, "AddressMessage"
    end
    add_message "GetReferralCodeResponse" do
      optional :ReferralCode, :string, 1
      optional :InviterRebateRatio, :int64, 2
      optional :InviteeRebateRatio, :int64, 3
      optional :AccountRole, :string, 4
    end
    add_message "CanRegisterWithReferralCodeRequest" do
      optional :Address, :message, 1, "AddressMessage"
      optional :ReferralCode, :string, 2
    end
    add_message "CanRegisterWithReferralCodeResponse" do
      optional :OK, :bool, 1
      optional :InviterAddress, :message, 2, "AddressMessage"
      optional :InviterRebateRatio, :int64, 3
      optional :InviteeRebateRatio, :int64, 4
      optional :CanNotBindReferralCodeReason, :string, 5
    end
    add_message "RegisterReferralRecordRequest" do
      optional :InviteeAddress, :message, 1, "AddressMessage"
      optional :InviterAddress, :message, 2, "AddressMessage"
    end
    add_message "RegisterReferralRecordResponse" do
      optional :OK, :bool, 1
      optional :CanNotBindReferralCodeReason, :string, 2
    end
    add_message "UpdateCommissionRebateRatioRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :InviterRebateRatio, :int64, 2
      optional :InviteeRebateRatio, :int64, 3
    end
    add_message "UpdateCommissionRebateRatioResponse" do
      optional :OK, :bool, 1
      optional :UpdateFailedReason, :string, 2
    end
    add_message "AccountCommissionRebateRatio" do
      optional :Account, :message, 1, "AddressMessage"
      optional :TotalRebateRatio, :int64, 2
    end
    add_message "BatchUpdateCommissionRebateRatiosRequest" do
      repeated :AccountCommissionRebateRatios, :message, 1, "AccountCommissionRebateRatio"
    end
    add_message "BatchUpdateCommissionRebateRatiosResponse" do
      optional :OK, :bool, 1
    end
    add_message "GetAccountRoleByReferralCodeRequest" do
      optional :ReferralCode, :string, 1
    end
    add_message "GetAccountRoleByReferralCodeResponse" do
      optional :AccountRole, :string, 1
      optional :InviteeRebateRatio, :int64, 2
      optional :Account, :message, 3, "AddressMessage"
    end
  end
end

module Internal
  module Referral
    GetReferralCodeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetReferralCodeRequest").msgclass
    GetReferralCodeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetReferralCodeResponse").msgclass
    CanRegisterWithReferralCodeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CanRegisterWithReferralCodeRequest").msgclass
    CanRegisterWithReferralCodeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CanRegisterWithReferralCodeResponse").msgclass
    RegisterReferralRecordRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RegisterReferralRecordRequest").msgclass
    RegisterReferralRecordResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RegisterReferralRecordResponse").msgclass
    UpdateCommissionRebateRatioRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UpdateCommissionRebateRatioRequest").msgclass
    UpdateCommissionRebateRatioResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UpdateCommissionRebateRatioResponse").msgclass
    AccountCommissionRebateRatio = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AccountCommissionRebateRatio").msgclass
    BatchUpdateCommissionRebateRatiosRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BatchUpdateCommissionRebateRatiosRequest").msgclass
    BatchUpdateCommissionRebateRatiosResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BatchUpdateCommissionRebateRatiosResponse").msgclass
    GetAccountRoleByReferralCodeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountRoleByReferralCodeRequest").msgclass
    GetAccountRoleByReferralCodeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountRoleByReferralCodeResponse").msgclass
  end
end
