# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/referral/server.proto for package 'Internal.Referral'

require 'grpc'
require 'internal/referral/server_pb'

module Internal
  module Referral
    module ReferralService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'ReferralService'

        rpc :GetReferralCode, ::Internal::Referral::GetReferralCodeRequest, ::Internal::Referral::GetReferralCodeResponse
        rpc :GetAccountRoleByReferralCode, ::Internal::Referral::GetAccountRoleByReferralCodeRequest, ::Internal::Referral::GetAccountRoleByReferralCodeResponse
        rpc :CanRegisterWithReferralCode, ::Internal::Referral::CanRegisterWithReferralCodeRequest, ::Internal::Referral::CanRegisterWithReferralCodeResponse
        rpc :RegisterReferralRecord, ::Internal::Referral::RegisterReferralRecordRequest, ::Internal::Referral::RegisterReferralRecordResponse
        rpc :UpdateCommissionRebateRatio, ::Internal::Referral::UpdateCommissionRebateRatioRequest, ::Internal::Referral::UpdateCommissionRebateRatioResponse
        rpc :BatchUpdateCommissionRebateRatios, ::Internal::Referral::BatchUpdateCommissionRebateRatiosRequest, ::Internal::Referral::BatchUpdateCommissionRebateRatiosResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
