# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/market_data/server.proto

require 'google/protobuf'

require 'internal/types/candle_pb'
require 'google/protobuf/empty_pb'
require 'google/protobuf/wrappers_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/market_data/server.proto", :syntax => :proto3) do
  end
end

module Internal
  module Market_data
  end
end
