# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/market_data/server.proto for package 'Internal.Market_data'

require 'grpc'
require 'internal/market_data/server_pb'

module Internal
  module MarketData
    module MarketDataService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'MarketDataService'

        rpc :CandleStream, ::Google::Protobuf::Empty, stream(::Internal::Types::Candles)
        rpc :Market24HourStatusStream, ::Google::Protobuf::Empty, stream(::Internal::Types::Market24HourStatus)
        rpc :GetMarket24HourStatus, ::Google::Protobuf::StringValue, ::Internal::Types::Market24HourStatus
        rpc :GetAllMarket24HourStatus, ::Google::Protobuf::Empty, ::Internal::Types::Market24HourStatusMap
      end

      Stub = Service.rpc_stub_class
    end
  end
end
