# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/cancel_order_gateway/server.proto for package 'Internal.CancelOrderGateway'

require 'grpc'
require 'internal/cancel_order_gateway/server_pb'

module Internal
  module CancelOrderGateway
    module CancelOrderGatewayService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'CancelOrderGatewayService'

        rpc :CancelOrder, ::Internal::Core::CancelOrderRequest, ::Internal::Core::CancelOrderResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
