# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/cancel_order_gateway/server.proto

require 'google/protobuf'

require 'internal/core/server_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/cancel_order_gateway/server.proto", :syntax => :proto3) do
  end
end

module Internal
  module CancelOrderGateway
  end
end
