# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/s2_airdrop_farm_activity/server.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'
require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/s2_airdrop_farm_activity/server.proto", :syntax => :proto3) do
    add_message "GetS2AirdropFarmActivityBriefRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :EpochNumber, :int64, 2
      optional :SourceFrom, :string, 3
    end
    add_message "S2AirdropFarmEpochActivity" do
      optional :StartAt, :int64, 1
      optional :EndAt, :int64, 2
      optional :TotalTokenCount, :int64, 3
      optional :TradeVolume, :message, 4, "DecimalMessage"
      optional :TradeVolumePoints, :message, 5, "DecimalMessage"
      optional :DailyAverageTVL, :message, 6, "DecimalMessage"
      optional :DailyAverageTVLPoints, :message, 7, "DecimalMessage"
      optional :InviteeAccountCount, :int64, 8
      optional :RewardTokens, :message, 9, "DecimalMessage"
      optional :EpochNumber, :int64, 10
      optional :ActivityStatus, :string, 11
      optional :EventPoints, :message, 12, "DecimalMessage"
      optional :AssetsSnapshotExecuteCount, :int64, 13
      optional :RewardTokenRatio, :string, 14
      optional :AccountRole, :string, 15
      optional :Account, :message, 16, "AddressMessage"
      optional :TotalPoints, :message, 17, "DecimalMessage"
      optional :TotalTradeVolume, :message, 18, "DecimalMessage"
      optional :TotalDailyAverageTVL, :message, 19, "DecimalMessage"
      optional :PerpNetValue, :message, 20, "DecimalMessage"
      optional :DegenNetValue, :message, 21, "DecimalMessage"
      optional :DailyCommittedLP, :message, 22, "DecimalMessage"
      optional :DailyCommittedLPPoints, :message, 23, "DecimalMessage"
      optional :CommittedLPSnapshotExecuteCount, :int64, 24
      optional :TotalCommittedLPTVL, :message, 25, "DecimalMessage"
    end
    add_message "GetS2AirdropFarmActivityBriefResponse" do
      optional :EpochActivity, :message, 1, "S2AirdropFarmEpochActivity"
      optional :TotalRewardTokens, :message, 2, "DecimalMessage"
      optional :RewardsTokensToBeClaimed, :message, 3, "DecimalMessage"
      optional :VipLevel, :int64, 4
      optional :VipLevelIncreaseRatio, :message, 5, "DecimalMessage"
      optional :JOJOPrice24HoursAgo, :message, 6, "DecimalMessage"
      optional :LastEpochTotalPoints, :message, 7, "DecimalMessage"
      optional :MerkleIndex, :int64, 8
      repeated :MerkleProof, :string, 9
      optional :IsClaimed, :bool, 10
    end
    add_message "S2AirdropFarmActivityStatus" do
      optional :AccountRole, :string, 2
      optional :TradeVolume, :message, 3, "DecimalMessage"
      optional :DailyAverageTVL, :message, 4, "DecimalMessage"
      optional :RewardTokens, :message, 5, "DecimalMessage"
      optional :RewardTokenRatio, :string, 6
      optional :EventPoints, :message, 7, "DecimalMessage"
      optional :DailyCommittedLP, :message, 8, "DecimalMessage"
    end
    add_message "S2AirdropFarmEpochActivityStatus" do
      optional :EpochNumber, :int64, 1
      repeated :Activities, :message, 2, "S2AirdropFarmActivityStatus"
    end
    add_message "GetS2AirdropFarmActivitySummaryStatsRequest" do
      optional :EpochNumber, :int64, 1
    end
    add_message "GetS2AirdropFarmActivitySummaryStatsResponse" do
      repeated :EpochActivities, :message, 1, "S2AirdropFarmEpochActivityStatus"
      optional :CurrentEpochNumber, :int64, 2
      optional :BotTotalPointsRatio, :message, 3, "DecimalMessage"
      optional :UserTotalPointsRatio, :message, 4, "DecimalMessage"
    end
    add_message "GetS2AirdropFarmRanklingListRequest" do
      optional :AccountRole, :string, 1
      optional :AccountCount, :int64, 2
      optional :EpochNumber, :int64, 3
      optional :Account, :message, 4, "AddressMessage"
    end
    add_message "GetS2AirdropFarmRanklingListResponse" do
      repeated :EpochActivities, :message, 1, "S2AirdropFarmEpochActivity"
      optional :CurrentEpochNumber, :int64, 2
    end
    add_message "GetS2AirdropFarmRanklingListForApiRequest" do
      optional :SortBy, :string, 1
      optional :Account, :message, 2, "AddressMessage"
    end
    add_message "S2UserRanking" do
      optional :MaskedAccount, :string, 1
      optional :Ranking, :int64, 2
      optional :DailyTradeAmount, :message, 4, "DecimalMessage"
      optional :TotalTradeAmount, :message, 5, "DecimalMessage"
      optional :DailyEventPoints, :message, 6, "DecimalMessage"
      optional :TotalEventPoints, :message, 7, "DecimalMessage"
      optional :IsMe, :bool, 9
    end
    add_message "GetS2AirdropFarmRanklingListForApiResponse" do
      repeated :UserRankings, :message, 1, "S2UserRanking"
    end
  end
end

module Internal
  module S2AirdropFarmActivityProcessor
    GetS2AirdropFarmActivityBriefRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetS2AirdropFarmActivityBriefRequest").msgclass
    S2AirdropFarmEpochActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("S2AirdropFarmEpochActivity").msgclass
    GetS2AirdropFarmActivityBriefResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetS2AirdropFarmActivityBriefResponse").msgclass
    S2AirdropFarmActivityStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("S2AirdropFarmActivityStatus").msgclass
    S2AirdropFarmEpochActivityStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("S2AirdropFarmEpochActivityStatus").msgclass
    GetS2AirdropFarmActivitySummaryStatsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetS2AirdropFarmActivitySummaryStatsRequest").msgclass
    GetS2AirdropFarmActivitySummaryStatsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetS2AirdropFarmActivitySummaryStatsResponse").msgclass
    GetS2AirdropFarmRanklingListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetS2AirdropFarmRanklingListRequest").msgclass
    GetS2AirdropFarmRanklingListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetS2AirdropFarmRanklingListResponse").msgclass
    GetS2AirdropFarmRanklingListForApiRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetS2AirdropFarmRanklingListForApiRequest").msgclass
    S2UserRanking = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("S2UserRanking").msgclass
    GetS2AirdropFarmRanklingListForApiResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetS2AirdropFarmRanklingListForApiResponse").msgclass
  end
end
