# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/s2_airdrop_farm_activity/server.proto for package 'Internal.S2AirdropFarmActivityProcessor'

require 'grpc'
require 'internal/s2_airdrop_farm_activity/server_pb'

module Internal
  module S2AirdropFarmActivityProcessor
    module S2AirdropFarmActivity
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'S2AirdropFarmActivity'

        rpc :GetS2AirdropFarmActivityBrief, ::Internal::S2AirdropFarmActivityProcessor::GetS2AirdropFarmActivityBriefRequest, ::Internal::S2AirdropFarmActivityProcessor::GetS2AirdropFarmActivityBriefResponse
        rpc :GetS2AirdropFarmActivitySummaryStats, ::Internal::S2AirdropFarmActivityProcessor::GetS2AirdropFarmActivitySummaryStatsRequest, ::Internal::S2AirdropFarmActivityProcessor::GetS2AirdropFarmActivitySummaryStatsResponse
        rpc :GetS2AirdropFarmRanklingList, ::Internal::S2AirdropFarmActivityProcessor::GetS2AirdropFarmRanklingListRequest, ::Internal::S2AirdropFarmActivityProcessor::GetS2AirdropFarmRanklingListResponse
        rpc :UpdateS2AccountsVipLevelNotification, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :GetS2AirdropFarmRankingListForApi, ::Internal::S2AirdropFarmActivityProcessor::GetS2AirdropFarmRanklingListForApiRequest, ::Internal::S2AirdropFarmActivityProcessor::GetS2AirdropFarmRanklingListForApiResponse
        rpc :FillS2YesterdayUserTokensCount, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
      end

      Stub = Service.rpc_stub_class
    end
  end
end
