# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: admin/server.proto for package 'Internal.Admin'

require 'grpc'
require 'admin/server_pb'

module Internal
  module Admin
    module AdminService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'AdminService'

        rpc :GetAccountList, ::Internal::Types::GetAccountListRequest, ::Internal::Types::GetAccountListResponse
        rpc :GetAccountInfo, ::Internal::Admin::GetAccountInfoRequest, ::Internal::Admin::GetAccountInfoResponse
        rpc :ReloadAccountInfo, ::Internal::Admin::ReloadAccountInfoRequest, ::Internal::Admin::ReloadAccountInfoResponse
        rpc :GetAccountOrdersAndTrades, ::Internal::Admin::GetAccountOrdersAndTradesRequest, ::Internal::Admin::GetAccountOrdersAndTradesResponse
        rpc :CancelAccountOrder, ::Internal::Admin::CancelAccountOrderRequest, ::Internal::Admin::CancelAccountOrderResponse
        rpc :FailAccountTrade, ::Internal::Admin::FailAccountTradeRequest, ::Internal::Admin::FailAccountTradeResponse
        rpc :GetPlatformRisks, ::Internal::Admin::GetPlatformRisksRequest, ::Internal::Core::GetPlatformRisksResponse
        rpc :GetMarketAccountDetail, ::Internal::Admin::GetMarketAccountDetailRequest, ::Internal::Admin::GetMarketAccountDetailResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
