# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin/server.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'
require 'internal/types/account_pb'
require 'internal/core/server_pb'
require 'internal/types/order_pb'
require 'internal/types/strade_pb'
require 'internal/types/position_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("admin/server.proto", :syntax => :proto3) do
    add_message "GetAccountInfoRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "GetAccountInfoResponse" do
      optional :Account, :message, 1, "AddressMessage"
      optional :BlockchainState, :message, 2, "AccountBlockchainState"
      repeated :Positions, :message, 3, "Position"
      optional :FrozenMarginAmount, :message, 4, "DecimalMessage"
      optional :AvailableMarginAmount, :message, 5, "DecimalMessage"
    end
    add_message "ReloadAccountInfoRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "ReloadAccountInfoResponse" do
      optional :OK, :bool, 1
    end
    add_message "GetAccountOrdersAndTradesRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "GetAccountOrdersAndTradesResponse" do
      repeated :Orders, :message, 1, "Order"
      repeated :Trades, :message, 2, "Trade"
    end
    add_message "CancelAccountOrderRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :OrderID, :int64, 2
      optional :MarketID, :string, 3
    end
    add_message "CancelAccountOrderResponse" do
      optional :NotFoundInCore, :bool, 1
    end
    add_message "FailAccountTradeRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :TradeID, :int64, 2
      optional :MarketID, :string, 3
    end
    add_message "FailAccountTradeResponse" do
      optional :NotFoundInCore, :bool, 1
      optional :SetFailed, :bool, 2
    end
    add_message "BinanceAccountAsset" do
      optional :Asset, :string, 1
      optional :InitialMargin, :string, 2
      optional :MaintMargin, :string, 3
      optional :MarginBalance, :string, 4
      optional :MaxWithdrawAmount, :string, 5
      optional :OpenOrderInitialMargin, :string, 6
      optional :PositionInitialMargin, :string, 7
      optional :UnrealizedProfit, :string, 8
      optional :WalletBalance, :string, 9
    end
    add_message "BinancePosition" do
      optional :Isolated, :bool, 1
      optional :Leverage, :string, 2
      optional :InitialMargin, :string, 3
      optional :MaintMargin, :string, 4
      optional :OpenOrderInitialMargin, :string, 5
      optional :Symbol, :string, 6
      optional :UnrealizedProfit, :string, 7
      optional :EntryPrice, :string, 8
      optional :MaxNotional, :string, 9
      optional :PositionSide, :string, 10
      optional :PositionAmt, :string, 11
      optional :Notional, :string, 12
      optional :IsolatedWallet, :string, 13
      optional :UpdateTime, :int64, 14
    end
    add_message "BinanceAccount" do
      repeated :Assets, :message, 1, "BinanceAccountAsset"
      optional :FeeTier, :int64, 2
      optional :CanTrade, :bool, 3
      optional :CanDeposit, :bool, 4
      optional :CanWithdraw, :bool, 5
      optional :TotalMaintMargin, :string, 6
      optional :TotalWalletBalance, :string, 7
      optional :TotalUnrealizedProfit, :string, 8
      optional :TotalMarginBalance, :string, 9
      optional :TotalPositionInitialMargin, :string, 10
      optional :TotalOpenOrderInitialMargin, :string, 11
      optional :TotalCrossWalletBalance, :string, 12
      optional :TotalCrossUnPnl, :string, 13
      optional :AvailableBalance, :string, 14
      optional :MaxWithdrawAmount, :string, 15
      repeated :Positions, :message, 16, "BinancePosition"
    end
    add_message "GetMarketAccountDetailRequest" do
      optional :Name, :string, 1
    end
    add_message "GetMarketAccountDetailResponse" do
      optional :AccountName, :string, 1
      optional :MakerAccount, :message, 2, "AddressMessage"
      optional :MakerBlockchainState, :message, 3, "AccountBlockchainState"
      repeated :MakerPositions, :message, 4, "Position"
      optional :TakerAccount, :message, 5, "AddressMessage"
      optional :TakerBlockchainState, :message, 6, "AccountBlockchainState"
      repeated :TakerPositions, :message, 7, "Position"
      optional :TotalMutualTradeFee, :message, 8, "DecimalMessage"
      optional :BinanceAccount, :message, 9, "BinanceAccount"
    end
    add_message "GetPlatformRisksRequest" do
      optional :AccountRole, :string, 1
    end
  end
end

module Internal
  module Admin
    GetAccountInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountInfoRequest").msgclass
    GetAccountInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountInfoResponse").msgclass
    ReloadAccountInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ReloadAccountInfoRequest").msgclass
    ReloadAccountInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ReloadAccountInfoResponse").msgclass
    GetAccountOrdersAndTradesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountOrdersAndTradesRequest").msgclass
    GetAccountOrdersAndTradesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAccountOrdersAndTradesResponse").msgclass
    CancelAccountOrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelAccountOrderRequest").msgclass
    CancelAccountOrderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelAccountOrderResponse").msgclass
    FailAccountTradeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FailAccountTradeRequest").msgclass
    FailAccountTradeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FailAccountTradeResponse").msgclass
    BinanceAccountAsset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BinanceAccountAsset").msgclass
    BinancePosition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BinancePosition").msgclass
    BinanceAccount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BinanceAccount").msgclass
    GetMarketAccountDetailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMarketAccountDetailRequest").msgclass
    GetMarketAccountDetailResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMarketAccountDetailResponse").msgclass
    GetPlatformRisksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPlatformRisksRequest").msgclass
  end
end
