# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/order/constructor.proto

require 'google/protobuf'


require 'internal/types/types_pb'
require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/order/constructor.proto", :syntax => :proto3) do
    add_message "NewOrderRequest" do
      optional :MarketID, :string, 1
      optional :Side, :enum, 2, "SIDE"
      optional :OrderType, :enum, 3, "OT"
      optional :TIF, :enum, 4, "TIF"
      optional :Price, :message, 5, "DecimalMessage"
      optional :Amount, :message, 6, "DecimalMessage"
      optional :Expiration, :int64, 7
      optional :Info, :bytes, 8
      optional :Signature, :bytes, 9
      optional :OrderSource, :string, 10
      optional :TpTriggerPrice, :message, 11, "DecimalMessage"
      optional :TpTriggerType, :string, 12
      optional :SlTriggerPrice, :message, 13, "DecimalMessage"
      optional :SlTriggerType, :string, 14
      optional :Account, :message, 15, "AddressMessage"
    end
  end
end

module Internal
  module Order
    NewOrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NewOrderRequest").msgclass
  end
end
