# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/asset_movement/server.proto for package 'Internal.AssetMovement'

require 'grpc'
require 'internal/asset_movement/server_pb'

module Internal
  module AssetMovement
    module AssetMovement
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'AssetMovement'

        rpc :GetBotAccountList, ::Internal::AssetMovement::GetBotAccountListRequest, ::Internal::AssetMovement::GetBotAccountListResponse
        rpc :GetPerpOpenInterestBotAccountList, ::Google::Protobuf::Empty, ::Internal::AssetMovement::GetPerpOpenInterestBotAccountListResponse
        rpc :TransferAssetToBinance, ::Internal::AssetMovement::TransferAssetToBinanceRequest, ::Internal::AssetMovement::TransferAssetToBinanceResponse
        rpc :ManuallyTransferAssetToBinance, ::Internal::AssetMovement::ManuallyTransferAssetToBinanceRequest, ::Internal::AssetMovement::ManuallyTransferAssetToBinanceResponse
        rpc :GetBotJOJOAssetList, ::Internal::AssetMovement::GetBotJOJOAssetListRequest, ::Internal::AssetMovement::GetBotJOJOAssetListResponse
        rpc :GetUserJOJOAssetSummary, ::Google::Protobuf::Empty, ::Internal::AssetMovement::GetUserJOJOAssetSummaryResponse
        rpc :TransferJOJOAsset, ::Internal::AssetMovement::TransferJOJOAssetRequest, ::Internal::AssetMovement::TransferJOJOAssetResponse
        rpc :StakeJOJOAsset, ::Internal::AssetMovement::StakeJOJOAssetRequest, ::Internal::AssetMovement::StakeJOJOAssetResponse
        rpc :RequestDepositETHFromBinance, ::Internal::AssetMovement::RequestDepositETHFromBinanceRequest, ::Internal::AssetMovement::RequestDepositETHFromBinanceResponse
        rpc :TransferETHToBinance, ::Internal::AssetMovement::TransferETHToBinanceRequest, ::Internal::AssetMovement::TransferETHToBinanceResponse
        rpc :DepositJUSDToContract, ::Internal::AssetMovement::DepositJUSDToContractRequest, ::Internal::AssetMovement::DepositJUSDToContractResponse
        rpc :ClaimVeJOJOReward, ::Internal::AssetMovement::ClaimVeJOJORewardRequest, ::Internal::AssetMovement::ClaimVeJOJORewardResponse
        rpc :DepositVeJOJORewardToDegenDealer, ::Internal::AssetMovement::DepositVeJOJORewardToDegenDealerRequest, ::Internal::AssetMovement::DepositVeJOJORewardToDegenDealerResponse
        rpc :TriggerInternalTransfer, ::Internal::AssetMovement::TriggerInternalTransferRequest, ::Internal::AssetMovement::TriggerInternalTransferResponse
        rpc :CheckDepositToBinanceStatus, ::Internal::AssetMovement::CheckDepositToBinanceStatusRequest, ::Internal::AssetMovement::CheckDepositToBinanceStatusResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
