# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/asset_movement/server.proto

require 'google/protobuf'


require 'internal/decimal/decimal_pb'
require 'internal/ext/address_pb'
require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/asset_movement/server.proto", :syntax => :proto3) do
    add_message "GetBotAccountListRequest" do
      optional :Scene, :string, 1
    end
    add_message "GetBotAccountListResponse" do
      repeated :Accounts, :message, 1, "AddressMessage"
      optional :AvailableAccountCount, :int64, 2
    end
    add_message "PerpOpenInterestBotMarketRule" do
      optional :MarketID, :string, 1
      repeated :Accounts, :message, 2, "AddressMessage"
      optional :MinimumBalance, :message, 3, "DecimalMessage"
      optional :MovementAmount, :message, 4, "DecimalMessage"
      optional :InitialMovementAmount, :message, 5, "DecimalMessage"
      optional :NetValueDiffRateForInternalTransfer, :message, 6, "DecimalMessage"
    end
    add_message "GetPerpOpenInterestBotAccountListResponse" do
      repeated :PerpOpenInterestBotMarketRules, :message, 1, "PerpOpenInterestBotMarketRule"
    end
    add_message "TransferAssetToBinanceRequest" do
      optional :Amount, :message, 1, "DecimalMessage"
      optional :DegenWithdrawID, :int64, 2
    end
    add_message "TransferAssetToBinanceResponse" do
      optional :AssetMovementLog, :int64, 1
    end
    add_message "ManuallyTransferAssetToBinanceRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Amount, :message, 2, "DecimalMessage"
      optional :TransferFrom, :string, 3
    end
    add_message "ManuallyTransferAssetToBinanceResponse" do
      optional :AssetMovementLog, :int64, 1
    end
    add_message "GetBotJOJOAssetListRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "BotJOJOAsset" do
      optional :Account, :message, 1, "AddressMessage"
      optional :JOJOAmount, :message, 2, "DecimalMessage"
      optional :Role, :string, 3
      optional :StakedJOJOAmount, :message, 4, "DecimalMessage"
      optional :VeJOJOAmount, :message, 5, "DecimalMessage"
      optional :TotalUSDCRewards, :message, 6, "DecimalMessage"
      optional :UnclaimedUSDCRewards, :message, 7, "DecimalMessage"
    end
    add_message "GetBotJOJOAssetListResponse" do
      repeated :BotJOJOAssets, :message, 1, "BotJOJOAsset"
    end
    add_message "TransferJOJOAssetRequest" do
      optional :FromAccount, :message, 1, "AddressMessage"
      optional :ToAccount, :message, 2, "AddressMessage"
      optional :Amount, :message, 3, "DecimalMessage"
    end
    add_message "TransferJOJOAssetResponse" do
      optional :ErrorMessage, :string, 1
    end
    add_message "StakeJOJOAssetRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Amount, :message, 2, "DecimalMessage"
      optional :LockTime, :int64, 3
    end
    add_message "StakeJOJOAssetResponse" do
      optional :ErrorMessage, :string, 1
    end
    add_message "GetUserJOJOAssetSummaryResponse" do
      optional :TotalVeJOJOAmount, :message, 1, "DecimalMessage"
      optional :TotalUSDCRewards, :message, 2, "DecimalMessage"
      optional :TotalUnclaimedUSDCRewards, :message, 3, "DecimalMessage"
      optional :TotalStakedJOJOAmount, :message, 4, "DecimalMessage"
      optional :TotalPreLaunchJOJOAmount, :message, 5, "DecimalMessage"
      optional :TotalAirdropFarmJOJOAmount, :message, 6, "DecimalMessage"
      optional :TotalDodoJOJOAmount, :message, 7, "DecimalMessage"
      optional :TotalNoviceJOJOAmount, :message, 8, "DecimalMessage"
      optional :TotalWarpcastJOJOAmount, :message, 9, "DecimalMessage"
      optional :TotalSlotMachineJOJOAmount, :message, 10, "DecimalMessage"
      optional :TotalPreLaunchJOJOUnclaimedAmount, :message, 11, "DecimalMessage"
      optional :TotalAirdropFarmJOJOUnclaimedAmount, :message, 12, "DecimalMessage"
      optional :TotalDodoJOJOUnclaimedAmount, :message, 13, "DecimalMessage"
      optional :TotalNoviceJOJOUnclaimedAmount, :message, 14, "DecimalMessage"
      optional :TotalWarpcastJOJOUnclaimedAmount, :message, 15, "DecimalMessage"
      optional :DodoLpJOJOAmount, :message, 16, "DecimalMessage"
      optional :AeroLpJOJOAmount, :message, 17, "DecimalMessage"
    end
    add_message "RequestDepositETHFromBinanceRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Amount, :message, 2, "DecimalMessage"
    end
    add_message "DepositJUSDToContractRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Amount, :message, 2, "DecimalMessage"
    end
    add_message "RequestDepositETHFromBinanceResponse" do
      optional :ErrorMessage, :string, 1
      optional :AssetMovementLogID, :int64, 2
    end
    add_message "TransferETHToBinanceRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Amount, :message, 2, "DecimalMessage"
    end
    add_message "TransferETHToBinanceResponse" do
      optional :ErrorMessage, :string, 1
      optional :AssetMovementLogID, :int64, 2
    end
    add_message "DepositJUSDToContractResponse" do
      optional :AssetMovementLog, :int64, 1
    end
    add_message "ClaimVeJOJORewardRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "ClaimVeJOJORewardResponse" do
      optional :ErrorMessage, :string, 1
    end
    add_message "DepositVeJOJORewardToDegenDealerRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "DepositVeJOJORewardToDegenDealerResponse" do
      optional :ErrorMessage, :string, 1
    end
    add_message "TriggerInternalTransferRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Amount, :message, 3, "DecimalMessage"
      optional :TransferType, :string, 4
    end
    add_message "TriggerInternalTransferResponse" do
      optional :ErrorMessage, :string, 1
      optional :AssetMovementLogID, :int64, 2
    end
    add_message "CheckDepositToBinanceStatusRequest" do
      optional :DepositToBinanceTxHash, :string, 1
    end
    add_message "CheckDepositToBinanceStatusResponse" do
      optional :ErrorMessage, :string, 1
      optional :Status, :string, 2
    end
  end
end

module Internal
  module AssetMovement
    GetBotAccountListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetBotAccountListRequest").msgclass
    GetBotAccountListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetBotAccountListResponse").msgclass
    PerpOpenInterestBotMarketRule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PerpOpenInterestBotMarketRule").msgclass
    GetPerpOpenInterestBotAccountListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPerpOpenInterestBotAccountListResponse").msgclass
    TransferAssetToBinanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TransferAssetToBinanceRequest").msgclass
    TransferAssetToBinanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TransferAssetToBinanceResponse").msgclass
    ManuallyTransferAssetToBinanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ManuallyTransferAssetToBinanceRequest").msgclass
    ManuallyTransferAssetToBinanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ManuallyTransferAssetToBinanceResponse").msgclass
    GetBotJOJOAssetListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetBotJOJOAssetListRequest").msgclass
    BotJOJOAsset = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BotJOJOAsset").msgclass
    GetBotJOJOAssetListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetBotJOJOAssetListResponse").msgclass
    TransferJOJOAssetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TransferJOJOAssetRequest").msgclass
    TransferJOJOAssetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TransferJOJOAssetResponse").msgclass
    StakeJOJOAssetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StakeJOJOAssetRequest").msgclass
    StakeJOJOAssetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StakeJOJOAssetResponse").msgclass
    GetUserJOJOAssetSummaryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetUserJOJOAssetSummaryResponse").msgclass
    RequestDepositETHFromBinanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RequestDepositETHFromBinanceRequest").msgclass
    DepositJUSDToContractRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DepositJUSDToContractRequest").msgclass
    RequestDepositETHFromBinanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RequestDepositETHFromBinanceResponse").msgclass
    TransferETHToBinanceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TransferETHToBinanceRequest").msgclass
    TransferETHToBinanceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TransferETHToBinanceResponse").msgclass
    DepositJUSDToContractResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DepositJUSDToContractResponse").msgclass
    ClaimVeJOJORewardRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ClaimVeJOJORewardRequest").msgclass
    ClaimVeJOJORewardResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ClaimVeJOJORewardResponse").msgclass
    DepositVeJOJORewardToDegenDealerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DepositVeJOJORewardToDegenDealerRequest").msgclass
    DepositVeJOJORewardToDegenDealerResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DepositVeJOJORewardToDegenDealerResponse").msgclass
    TriggerInternalTransferRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TriggerInternalTransferRequest").msgclass
    TriggerInternalTransferResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TriggerInternalTransferResponse").msgclass
    CheckDepositToBinanceStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CheckDepositToBinanceStatusRequest").msgclass
    CheckDepositToBinanceStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CheckDepositToBinanceStatusResponse").msgclass
  end
end
