# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/monitor/price_monitor.proto

require 'google/protobuf'


require 'internal/types/candle_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/monitor/price_monitor.proto", :syntax => :proto3) do
    add_message "GetPriceRequest" do
      optional :MarketID, :string, 1
    end
    add_message "GetPriceResponse" do
      optional :Price, :message, 1, "MetaPrice"
    end
    add_message "GetAllPriceRequest" do
    end
    add_message "GetAllPriceResponse" do
      repeated :Prices, :message, 1, "MetaPrice"
    end
  end
end

module Internal
  module Monitor
    GetPriceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPriceRequest").msgclass
    GetPriceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPriceResponse").msgclass
    GetAllPriceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAllPriceRequest").msgclass
    GetAllPriceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAllPriceResponse").msgclass
  end
end
