# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/monitor/price_monitor.proto for package 'Internal.Monitor'

require 'grpc'
require 'internal/monitor/price_monitor_pb'

module Internal
  module Monitor
    module PriceMonitorService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'PriceMonitorService'

        rpc :GetMarkPrice, ::Internal::Monitor::GetPriceRequest, ::Internal::Monitor::GetPriceResponse
        rpc :GetAllMarkPrice, ::Internal::Monitor::GetAllPriceRequest, ::Internal::Monitor::GetAllPriceResponse
        rpc :GetIndexPrice, ::Internal::Monitor::GetPriceRequest, ::Internal::Monitor::GetPriceResponse
        rpc :GetAllIndexPrice, ::Internal::Monitor::GetAllPriceRequest, ::Internal::Monitor::GetAllPriceResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
