# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/sender/server.proto

require 'google/protobuf'

require 'internal/types/senderlog_pb'

require 'internal/ext/address_pb'
require 'internal/ext/hash_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/sender/server.proto", :syntax => :proto3) do
    add_message "CreateSenderLogRequest" do
      optional :From, :message, 1, "AddressMessage"
      optional :To, :message, 2, "AddressMessage"
      optional :Value, :string, 3
      optional :Data, :bytes, 4
      optional :GasPrice, :string, 5
      optional :GasLimit, :uint32, 6
      optional :Source, :string, 7
      optional :Namespace, :string, 8
    end
    add_message "GetRequest" do
      optional :Hash, :message, 1, "HashMessage"
      optional :Source, :string, 2
    end
    add_message "GetResponse" do
      repeated :Logs, :message, 1, "SenderLog"
    end
    add_message "SubscribeMessage" do
      optional :Hash, :message, 1, "HashMessage"
      optional :Source, :string, 2
    end
    add_message "SubscribeResponse" do
      optional :Log, :message, 1, "SenderLog"
    end
    add_message "RetrySenderLogGasInfo" do
      optional :Gas, :uint64, 1
      optional :GasTipCap, :message, 2, "DecimalMessage"
      optional :GasFeeCap, :message, 3, "DecimalMessage"
    end
    add_message "GetPendingSenderLogGasInfoRequest" do
      optional :SenderLogId, :int64, 1
    end
    add_message "GetPendingSenderLogGasInfoResponse" do
      optional :ErrorMsg, :string, 1
      optional :SenderLogId, :int64, 2
      optional :GasInfo, :message, 3, "RetrySenderLogGasInfo"
    end
    add_message "RetryPendingSenderLogRequest" do
      optional :SenderLogId, :int64, 1
      optional :GasInfo, :message, 2, "RetrySenderLogGasInfo"
    end
    add_message "RetryPendingSenderLogResponse" do
      optional :ErrorMsg, :string, 1
      optional :NewSenderLogHash, :string, 2
    end
  end
end

module Internal
  module Sender
    CreateSenderLogRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateSenderLogRequest").msgclass
    GetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetRequest").msgclass
    GetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetResponse").msgclass
    SubscribeMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SubscribeMessage").msgclass
    SubscribeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SubscribeResponse").msgclass
    RetrySenderLogGasInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RetrySenderLogGasInfo").msgclass
    GetPendingSenderLogGasInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPendingSenderLogGasInfoRequest").msgclass
    GetPendingSenderLogGasInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetPendingSenderLogGasInfoResponse").msgclass
    RetryPendingSenderLogRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RetryPendingSenderLogRequest").msgclass
    RetryPendingSenderLogResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RetryPendingSenderLogResponse").msgclass
  end
end
