# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/price_alert/server.proto for package 'Internal.PriceAlert'

require 'grpc'
require 'internal/price_alert/server_pb'

module Internal
  module PriceAlert
    module PriceAlertService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'PriceAlertService'

        rpc :CreatePriceAlterRule, ::Internal::PriceAlert::CreatePriceAlertRuleRequest, ::Internal::PriceAlert::CreatePriceAlertRuleResponse
        rpc :CancelPriceAlterRule, ::Internal::PriceAlert::CancelPriceAlertRuleRequest, ::Internal::PriceAlert::CancelPriceAlertRuleResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
