# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/price_alert/server.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'
require 'internal/types/price_alert_rule_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/price_alert/server.proto", :syntax => :proto3) do
    add_message "CreatePriceAlertRuleRequest" do
      optional :MarketID, :string, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :Price, :message, 3, "DecimalMessage"
      optional :AlertType, :string, 4
      optional :PercentChange, :message, 5, "DecimalMessage"
      optional :AlertFrequency, :string, 6
      optional :ExpiredAt, :int64, 7
      optional :TimeRange, :int64, 8
    end
    add_message "CreatePriceAlertRuleResponse" do
      optional :PriceAlertRule, :message, 1, "PriceAlertRule"
    end
    add_message "CancelPriceAlertRuleRequest" do
      optional :PriceAlertRuleID, :int64, 1
      optional :Account, :message, 2, "AddressMessage"
      optional :MarketID, :string, 3
    end
    add_message "CancelPriceAlertRuleResponse" do
      optional :PriceAlertRule, :message, 1, "PriceAlertRule"
      optional :ErrorMessage, :string, 2
    end
  end
end

module Internal
  module PriceAlert
    CreatePriceAlertRuleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreatePriceAlertRuleRequest").msgclass
    CreatePriceAlertRuleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreatePriceAlertRuleResponse").msgclass
    CancelPriceAlertRuleRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelPriceAlertRuleRequest").msgclass
    CancelPriceAlertRuleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CancelPriceAlertRuleResponse").msgclass
  end
end
