# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/sensitive_word/server.proto

require 'google/protobuf'



Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/sensitive_word/server.proto", :syntax => :proto3) do
    add_message "IsSensitiveWordRequest" do
      optional :Word, :string, 1
    end
    add_message "IsSensitiveWordResponse" do
      optional :IsSensitiveWord, :bool, 1
      optional :SensitiveWord, :string, 2
    end
  end
end

IsSensitiveWordRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsSensitiveWordRequest").msgclass
IsSensitiveWordResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IsSensitiveWordResponse").msgclass
