# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/sensitive_word/server.proto for package ''

require 'grpc'
require 'internal/sensitive_word/server_pb'

module SensitiveWordDetectionService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'SensitiveWordDetectionService'

    rpc :IsSensitiveWord, ::IsSensitiveWordRequest, ::IsSensitiveWordResponse
  end

  Stub = Service.rpc_stub_class
end
