# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/degen/degen_market_data/server.proto

require 'google/protobuf'

require 'internal/types/candle_pb'
require 'internal/types/degen_kline_pb'
require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/degen/degen_market_data/server.proto", :syntax => :proto3) do
  end
end

module Internal
  module degen_market_data
  end
end
