# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/degen/degen_market_data/server.proto for package 'Internal.degen_market_data'

require 'grpc'
require 'internal/degen/degen_market_data/server_pb'

module Internal
  module DegenMarketData
    module DegenMarketDataService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'DegenMarketDataService'

        rpc :DegenKLinesStream, ::Google::Protobuf::Empty, stream(::Internal::Types::DegenKLines)
        rpc :Market24HourStatusStream, ::Google::Protobuf::Empty, stream(::Internal::Types::Market24HourStatus)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
