# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/email_sender/server.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/email_sender/server.proto", :syntax => :proto3) do
    add_message "SendVerificationEmailRequest" do
      optional :Email, :string, 1
      optional :Nickname, :string, 2
      optional :Account, :message, 3, "AddressMessage"
      optional :VerificationToken, :string, 4
    end
    add_message "SendNotificationAfterFirstSettingUpEmailRequest" do
      optional :Email, :string, 1
      optional :Nickname, :string, 2
      optional :Account, :message, 3, "AddressMessage"
    end
    add_message "SendEmailResponse" do
      optional :OK, :bool, 1
      optional :SendGridResponseCode, :int32, 2
      optional :SendGridResponseBody, :string, 3
    end
    add_message "SendAccountRiskNotificationEmailRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Email, :string, 2
      optional :Nickname, :string, 3
      optional :Risk, :message, 4, "DecimalMessage"
      optional :TotalBalance, :message, 5, "DecimalMessage"
      optional :MaintenanceMargin, :message, 6, "DecimalMessage"
    end
    add_message "SendLiquidationEmailRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Email, :string, 2
      optional :Nickname, :string, 3
      optional :LiquidationType, :string, 4
      optional :MarketID, :string, 5
      optional :LiquidatePrice, :message, 6, "DecimalMessage"
      optional :LiquidationTriggerPrice, :message, 7, "DecimalMessage"
    end
    add_message "SendTpslOrderEmailRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Email, :string, 2
      optional :Nickname, :string, 3
      optional :MarketID, :string, 4
      optional :OrderSide, :string, 5
      optional :OrderStatus, :string, 6
      optional :OrderPrice, :message, 7, "DecimalMessage"
      optional :OrderAmount, :message, 8, "DecimalMessage"
      optional :TpslOrderType, :string, 9
    end
    add_message "SendGTTOrderExpiredEmailRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Email, :string, 2
      optional :Nickname, :string, 3
      optional :MarketID, :string, 4
      optional :OrderSide, :string, 5
      optional :OrderPrice, :message, 6, "DecimalMessage"
      optional :ExpiredAmount, :message, 7, "DecimalMessage"
    end
    add_message "SendCollateralRiskNotificationRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Email, :string, 2
      optional :Nickname, :string, 3
      optional :Risk, :message, 4, "DecimalMessage"
      optional :BorrowBalance, :message, 5, "DecimalMessage"
    end
    add_message "SendGridOrderTerminationNotificationRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Email, :string, 2
      optional :Nickname, :string, 3
      optional :MarketID, :string, 4
      optional :FailedReason, :string, 5
      optional :GridOrderCloseType, :string, 6
    end
    add_message "SendFundingRateArbitrageExecuteWithdrawNotificationRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Email, :string, 2
      optional :Nickname, :string, 3
      optional :WithdrawAmount, :message, 4, "DecimalMessage"
    end
    add_message "SendAirdropNotificationRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Email, :string, 2
      optional :Nickname, :string, 3
    end
    add_message "RemoveAirdropFarmTeamMemberRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Email, :string, 2
      optional :Nickname, :string, 3
      optional :TeamName, :string, 4
    end
    add_message "RejectAirdropFarmTeamMemberRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Email, :string, 2
      optional :Nickname, :string, 3
      optional :TeamName, :string, 4
    end
    add_message "SendOldUserRecallEmailRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Email, :string, 2
      optional :Nickname, :string, 3
    end
    add_message "PriceAlertEmailRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Email, :string, 2
      optional :Nickname, :string, 3
      optional :NotifyContent, :string, 4
    end
  end
end

module Internal
  module Email_sender
    SendVerificationEmailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendVerificationEmailRequest").msgclass
    SendNotificationAfterFirstSettingUpEmailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendNotificationAfterFirstSettingUpEmailRequest").msgclass
    SendEmailResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendEmailResponse").msgclass
    SendAccountRiskNotificationEmailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendAccountRiskNotificationEmailRequest").msgclass
    SendLiquidationEmailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendLiquidationEmailRequest").msgclass
    SendTpslOrderEmailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendTpslOrderEmailRequest").msgclass
    SendGTTOrderExpiredEmailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendGTTOrderExpiredEmailRequest").msgclass
    SendCollateralRiskNotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendCollateralRiskNotificationRequest").msgclass
    SendGridOrderTerminationNotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendGridOrderTerminationNotificationRequest").msgclass
    SendFundingRateArbitrageExecuteWithdrawNotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendFundingRateArbitrageExecuteWithdrawNotificationRequest").msgclass
    SendAirdropNotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendAirdropNotificationRequest").msgclass
    RemoveAirdropFarmTeamMemberRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RemoveAirdropFarmTeamMemberRequest").msgclass
    RejectAirdropFarmTeamMemberRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RejectAirdropFarmTeamMemberRequest").msgclass
    SendOldUserRecallEmailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SendOldUserRecallEmailRequest").msgclass
    PriceAlertEmailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PriceAlertEmailRequest").msgclass
  end
end
