# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/email_sender/server.proto for package 'Internal.Email_sender'

require 'grpc'
require 'internal/email_sender/server_pb'

module Internal
  module EmailSender
    module EmailSenderService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'EmailSenderService'

        rpc :SendVerificationEmail, ::Internal::EmailSender::SendVerificationEmailRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :SendNotificationAfterFirstSettingUpEmail, ::Internal::EmailSender::SendNotificationAfterFirstSettingUpEmailRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :SendAccountRiskNotificationEmail, ::Internal::EmailSender::SendAccountRiskNotificationEmailRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :SendFundingRateArbitrageAccountRiskNotificationEmail, ::Internal::EmailSender::SendAccountRiskNotificationEmailRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :SendLiquidationEmail, ::Internal::EmailSender::SendLiquidationEmailRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :SendTpslOrderTriggerEmail, ::Internal::EmailSender::SendTpslOrderEmailRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :SendGTTOrderExpiredEmail, ::Internal::EmailSender::SendGTTOrderExpiredEmailRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :SendCollateralRiskNotificationEmail, ::Internal::EmailSender::SendCollateralRiskNotificationRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :SendGridOrderTerminationNotificationEmail, ::Internal::EmailSender::SendGridOrderTerminationNotificationRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :SendFundingRateArbitrageExecuteWithdrawNotificationEmail, ::Internal::EmailSender::SendFundingRateArbitrageExecuteWithdrawNotificationRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :SendFundingRateArbitrageCollateralRiskNotificationEmail, ::Internal::EmailSender::SendCollateralRiskNotificationRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :SendAirdropNotificationEmail, ::Internal::EmailSender::SendAirdropNotificationRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :RemoveAirdropFarmTeamMemberEmail, ::Internal::EmailSender::RemoveAirdropFarmTeamMemberRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :RejectAirdropFarmTeamMemberRequestEmail, ::Internal::EmailSender::RejectAirdropFarmTeamMemberRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :SendOldUserRecallEmail, ::Internal::EmailSender::SendOldUserRecallEmailRequest, ::Internal::EmailSender::SendEmailResponse
        rpc :PriceAlertEmail, ::Internal::EmailSender::PriceAlertEmailRequest, ::Internal::EmailSender::SendEmailResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
