# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/gas_fee_simulator/server.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'

require 'internal/decimal/decimal_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/gas_fee_simulator/server.proto", :syntax => :proto3) do
    add_message "TradeGasFeeResponse" do
      optional :GasPrice, :message, 1, "DecimalMessage"
      optional :GasLimit, :message, 2, "DecimalMessage"
    end
    add_message "GasPriceResponse" do
      optional :GasPrice, :message, 1, "DecimalMessage"
    end
    add_message "GasFeeRequest" do
      optional :MakerOrderCount, :int64, 1
      optional :SenderLogID, :int64, 2
    end
    add_message "GasFeeResponse" do
      optional :GasPrice, :message, 1, "DecimalMessage"
      optional :GasLimit, :message, 2, "DecimalMessage"
      optional :BaseFee, :message, 3, "DecimalMessage"
      optional :GasTipCap, :message, 4, "DecimalMessage"
    end
  end
end

module Internal
  module GasFeeSimulator
    TradeGasFeeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TradeGasFeeResponse").msgclass
    GasPriceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GasPriceResponse").msgclass
    GasFeeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GasFeeRequest").msgclass
    GasFeeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GasFeeResponse").msgclass
  end
end
