# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/gas_fee_simulator/server.proto for package 'Internal.GasFeeSimulator'

require 'grpc'
require 'internal/gas_fee_simulator/server_pb'

module Internal
  module GasFeeSimulator
    module GasFeeSimulatorService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'GasFeeSimulatorService'

        rpc :GetTradeGasFee, ::Google::Protobuf::Empty, ::Internal::GasFeeSimulator::TradeGasFeeResponse
        rpc :GetGasFee, ::Internal::GasFeeSimulator::GasFeeRequest, ::Internal::GasFeeSimulator::GasFeeResponse
        rpc :WatchTradeGasFee, ::Google::Protobuf::Empty, stream(::Internal::GasFeeSimulator::TradeGasFeeResponse)
        rpc :RefreshAndGetSuggestGasPrice, ::Google::Protobuf::Empty, ::Internal::GasFeeSimulator::GasPriceResponse
        rpc :GetSuggestGasPrice, ::Google::Protobuf::Empty, ::Internal::GasFeeSimulator::GasPriceResponse
        rpc :EnterHighFrequencyRefreshGasMode, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
      end

      Stub = Service.rpc_stub_class
    end
  end
end
