# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/degen/degen_kline_cache/server.proto for package 'Internal.DegenKLineCache'

require 'grpc'
require 'internal/degen/degen_kline_cache/server_pb'

module Internal
  module DegenKLineCache
    module DegenKLineCacheService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'DegenKLineCacheService'

        rpc :GetDegenKLines, ::Internal::DegenKLineCache::GetDegenKLinesRequest, ::Internal::DegenKLineCache::GetDegenKLinesResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
