# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/degen/degen_kline_cache/server.proto

require 'google/protobuf'

require 'internal/types/candle_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/degen/degen_kline_cache/server.proto", :syntax => :proto3) do
    add_message "GetDegenKLinesRequest" do
      optional :MarketID, :string, 1
      optional :Interval, :enum, 2, "Interval"
      optional :StartTime, :int64, 3
      optional :EndTime, :int64, 4
    end
    add_message "GetDegenKLinesResponse" do
      repeated :TradeCandles, :message, 1, "TradeCandle"
    end
  end
end

module Internal
  module DegenKLineCache
    GetDegenKLinesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetDegenKLinesRequest").msgclass
    GetDegenKLinesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetDegenKLinesResponse").msgclass
  end
end
