# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/blockchain/server.proto

require 'google/protobuf'


require 'google/protobuf/timestamp_pb'
require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/blockchain/server.proto", :syntax => :proto3) do
    add_message "BlockInfo" do
      optional :BlockNumber, :uint64, 1
      optional :Time, :message, 2, "google.protobuf.Timestamp"
    end
  end
end

module Internal
  module Blockchain
    BlockInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BlockInfo").msgclass
  end
end
