# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/blockchain/server.proto for package 'Internal.Blockchain'

require 'grpc'
require 'internal/blockchain/server_pb'

module Internal
  module Blockchain
    module BlockChainGateway
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'BlockChainGateway'

        rpc :GetLatestBlock, ::Google::Protobuf::Empty, ::Internal::Blockchain::BlockInfo
        rpc :WatchLatestBlock, ::Google::Protobuf::Empty, stream(::Internal::Blockchain::BlockInfo)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
