# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/fundingrate/types.proto for package 'Internal.Fundingrate'

require 'grpc'
require 'internal/fundingrate/types_pb'

module Internal
  module Fundingrate
    module FundingRateService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'FundingRateService'

        rpc :GetMarketCurrentFrontendFundingRate, ::Internal::Fundingrate::GetMarketCurrentFrontendFundingRateRequest, ::Internal::Fundingrate::GetMarketCurrentFrontendFundingRateResponse
        rpc :GetAllMarketCurrentFrontendFundingRates, ::Google::Protobuf::Empty, ::Internal::Fundingrate::GetAllMarketCurrentFrontendFundingRatesResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
