# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/fundingrate/types.proto

require 'google/protobuf'


require 'google/protobuf/empty_pb'
require 'internal/decimal/decimal_pb'
require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/fundingrate/types.proto", :syntax => :proto3) do
    add_message "GetMarketCurrentFrontendFundingRateRequest" do
      optional :MarketID, :string, 1
    end
    add_message "GetMarketCurrentFrontendFundingRateResponse" do
      optional :CurrentFundingRate, :message, 1, "DecimalMessage"
      optional :NextTime, :message, 2, "google.protobuf.Timestamp"
      optional :Interval, :enum, 3, "FundingRateInterval"
    end
    add_message "MarketCurrentFrontendFundingRate" do
      optional :CurrentFundingRate, :message, 1, "DecimalMessage"
      optional :NextTime, :message, 2, "google.protobuf.Timestamp"
      optional :MarketID, :string, 3
      optional :FundingRateLimit, :string, 4
      optional :AveragePremium, :message, 5, "DecimalMessage"
      optional :Interval, :enum, 6, "FundingRateInterval"
    end
    add_message "GetAllMarketCurrentFrontendFundingRatesResponse" do
      repeated :MarketFundingRates, :message, 1, "MarketCurrentFrontendFundingRate"
    end
    add_enum "FundingRateInterval" do
      value :I8H, 0
      value :I5M, 1
      value :I10S, 2
      value :I5S, 3
      value :I1M, 4
    end
  end
end

module Internal
  module Fundingrate
    GetMarketCurrentFrontendFundingRateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMarketCurrentFrontendFundingRateRequest").msgclass
    GetMarketCurrentFrontendFundingRateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetMarketCurrentFrontendFundingRateResponse").msgclass
    MarketCurrentFrontendFundingRate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MarketCurrentFrontendFundingRate").msgclass
    GetAllMarketCurrentFrontendFundingRatesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAllMarketCurrentFrontendFundingRatesResponse").msgclass
    FundingRateInterval = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FundingRateInterval").enummodule
  end
end
