# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/config_center/server.proto

require 'google/protobuf'

require 'internal/types/market_pb'
require 'internal/types/degen_pb'
require 'internal/types/app_version_pb'

require 'google/protobuf/empty_pb'
require 'google/protobuf/wrappers_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/config_center/server.proto", :syntax => :proto3) do
    add_message "MarketStream" do
      repeated :Market, :message, 1, "Market"
    end
    add_message "DegenMarketStream" do
      repeated :DegenMarket, :message, 1, "DegenMarket"
    end
    add_message "MarketStatusStream" do
      repeated :SingleMarketStatus, :message, 1, "SingleMarketStatus"
    end
    add_message "InternalHost" do
      repeated :Host, :string, 1
    end
    add_message "ConfigStream" do
      oneof :kind do
        optional :MarketStream, :message, 1, "MarketStream"
        optional :MarketStatusStream, :message, 2, "MarketStatusStream"
        optional :InternalHost, :message, 3, "InternalHost"
        optional :DegenMarketStream, :message, 4, "DegenMarketStream"
        optional :AppVersion, :message, 5, "AppVersion"
      end
    end
    add_message "ConfigStreams" do
      repeated :ConfigStream, :message, 1, "ConfigStream"
    end
    add_enum "ConfigAction" do
      value :Add, 0
      value :Del, 1
      value :Update, 2
    end
  end
end

module Internal
  module ConfigCenter
    MarketStream = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MarketStream").msgclass
    DegenMarketStream = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenMarketStream").msgclass
    MarketStatusStream = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MarketStatusStream").msgclass
    InternalHost = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("InternalHost").msgclass
    ConfigStream = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ConfigStream").msgclass
    ConfigStreams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ConfigStreams").msgclass
    ConfigAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ConfigAction").enummodule
  end
end
