# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/config_center/server.proto for package 'Internal.ConfigCenter'

require 'grpc'
require 'internal/config_center/server_pb'

module Internal
  module ConfigCenter
    module ConfigCenterService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'ConfigCenterService'

        rpc :GetConfigCheckSum, ::Google::Protobuf::Int64Value, ::Google::Protobuf::StringValue
        rpc :GetConfig, ::Google::Protobuf::Int64Value, ::Internal::ConfigCenter::ConfigStreams
        rpc :SetConfig, ::Internal::ConfigCenter::ConfigStream, ::Google::Protobuf::Empty
        rpc :ReloadConfig, ::Google::Protobuf::Int64Value, ::Google::Protobuf::Empty
        rpc :WatchConfig, ::Google::Protobuf::Int64Value, stream(::Internal::ConfigCenter::ConfigStream)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
