# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/arb_activity_processor/server.proto for package 'Internal.ArbActivityProcessor'

require 'grpc'
require 'internal/arb_activity_processor/server_pb'

module Internal
  module ArbActivityProcessor
    module ArbActivity
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'ArbActivity'

        rpc :GetAccountRewardPoints, ::Internal::ArbActivityProcessor::GetAccountRewardPointsRequest, ::Internal::ArbActivityProcessor::GetAccountRewardPointsResponse
        rpc :GetArbActivityBrief, ::Google::Protobuf::Empty, ::Internal::ArbActivityProcessor::GetArbActivityBriefResponse
        rpc :GetTradeMiningRankingList, ::Internal::ArbActivityProcessor::GetTradeMiningRankingListRequest, ::Internal::ArbActivityProcessor::GetTradeMiningRankingListResponse
        rpc :GetNoviceActivityRankingList, ::Google::Protobuf::Empty, ::Internal::ArbActivityProcessor::GetNoviceActivityRankingListResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
