# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/ext/address.proto

require 'google/protobuf'



Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/ext/address.proto", :syntax => :proto3) do
    add_message "AddressMessage" do
      optional :Value, :bytes, 1
    end
  end
end

module Internal
  module Ext
    AddressMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AddressMessage").msgclass
  end
end
