# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/ext/hash.proto

require 'google/protobuf'



Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/ext/hash.proto", :syntax => :proto3) do
    add_message "HashMessage" do
      optional :Value, :bytes, 1
    end
  end
end

module Internal
  module Ext
    HashMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("HashMessage").msgclass
  end
end
