# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/ext/json_message.proto

require 'google/protobuf'



Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/ext/json_message.proto", :syntax => :proto3) do
    add_message "JsonMessage" do
      map :Value, :string, :string, 1
      optional :IsValid, :bool, 2
    end
  end
end

module Internal
  module Ext
    JsonMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JsonMessage").msgclass
  end
end
