# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/ext/null_string.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/ext/null_string.proto", :syntax => :proto3) do
    add_message "NullString" do
      optional :text, :string, 1
      optional :is_not_null, :bool, 2
    end
  end
end

module Internal
  module Ext
    NullString = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NullString").msgclass
  end
end
