# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/airdrop_farm_activity/server.proto

require 'google/protobuf'


require 'internal/ext/address_pb'
require 'internal/decimal/decimal_pb'
require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/airdrop_farm_activity/server.proto", :syntax => :proto3) do
    add_message "GetAirdropFarmActivityBriefRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :EpochNumber, :int64, 2
      optional :SourceFrom, :string, 3
    end
    add_message "AirdropFarmEpochActivity" do
      optional :StartAt, :int64, 1
      optional :EndAt, :int64, 2
      optional :TotalTokenCount, :int64, 3
      optional :TradeVolume, :message, 4, "DecimalMessage"
      optional :TradeVolumePoints, :message, 5, "DecimalMessage"
      optional :DailyAverageTVL, :message, 6, "DecimalMessage"
      optional :DailyAverageTVLPoints, :message, 7, "DecimalMessage"
      optional :InviteeAccountCount, :int64, 8
      optional :RewardTokens, :message, 9, "DecimalMessage"
      optional :EpochNumber, :int64, 10
      optional :ActivityStatus, :string, 11
      optional :EventPoints, :message, 12, "DecimalMessage"
      optional :AssetsSnapshotExecuteCount, :int64, 13
      optional :RewardTokenRatio, :string, 14
      optional :AccountRole, :string, 15
      optional :Account, :message, 16, "AddressMessage"
      optional :TotalPoints, :message, 17, "DecimalMessage"
      optional :TotalTradeVolume, :message, 18, "DecimalMessage"
      optional :TotalDailyAverageTVL, :message, 19, "DecimalMessage"
      optional :PerpNetValue, :message, 20, "DecimalMessage"
      optional :DegenNetValue, :message, 21, "DecimalMessage"
      optional :DailyCommittedLP, :message, 22, "DecimalMessage"
      optional :DailyCommittedLPPoints, :message, 23, "DecimalMessage"
      optional :CommittedLPSnapshotExecuteCount, :int64, 24
      optional :TotalCommittedLPTVL, :message, 25, "DecimalMessage"
    end
    add_message "GetAirdropFarmActivityBriefResponse" do
      optional :EpochActivity, :message, 1, "AirdropFarmEpochActivity"
      optional :TotalRewardTokens, :message, 2, "DecimalMessage"
      optional :RewardsTokensToBeClaimed, :message, 3, "DecimalMessage"
      optional :VipLevel, :int64, 4
      optional :VipLevelIncreaseRatio, :message, 5, "DecimalMessage"
      optional :JOJOPrice24HoursAgo, :message, 6, "DecimalMessage"
      optional :LastEpochTotalPoints, :message, 7, "DecimalMessage"
      optional :MerkleIndex, :int64, 8
      repeated :MerkleProof, :string, 9
      optional :IsClaimed, :bool, 10
    end
    add_message "AirdropFarmActivityStatus" do
      optional :AccountRole, :string, 2
      optional :TradeVolume, :message, 3, "DecimalMessage"
      optional :DailyAverageTVL, :message, 4, "DecimalMessage"
      optional :RewardTokens, :message, 5, "DecimalMessage"
      optional :RewardTokenRatio, :string, 6
      optional :EventPoints, :message, 7, "DecimalMessage"
      optional :DailyCommittedLP, :message, 8, "DecimalMessage"
    end
    add_message "AirdropFarmEpochActivityStatus" do
      optional :EpochNumber, :int64, 1
      repeated :Activities, :message, 2, "AirdropFarmActivityStatus"
    end
    add_message "GetAirdropFarmActivitySummaryStatsRequest" do
      optional :EpochNumber, :int64, 1
    end
    add_message "GetAirdropFarmActivitySummaryStatsResponse" do
      repeated :EpochActivities, :message, 1, "AirdropFarmEpochActivityStatus"
      optional :CurrentEpochNumber, :int64, 2
      optional :BotTotalPointsRatio, :message, 3, "DecimalMessage"
      optional :UserTotalPointsRatio, :message, 4, "DecimalMessage"
    end
    add_message "GetAirdropFarmRanklingListRequest" do
      optional :AccountRole, :string, 1
      optional :AccountCount, :int64, 2
      optional :EpochNumber, :int64, 3
      optional :Account, :message, 4, "AddressMessage"
    end
    add_message "GetAirdropFarmRanklingListResponse" do
      repeated :EpochActivities, :message, 1, "AirdropFarmEpochActivity"
      optional :CurrentEpochNumber, :int64, 2
    end
    add_message "CreateAirdropFarmTeamRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :Name, :string, 2
      optional :TeamType, :string, 3
    end
    add_message "CreateAirdropFarmTeamResponse" do
      optional :Captain, :message, 1, "AddressMessage"
      optional :Name, :string, 2
      optional :TeamType, :string, 3
      optional :Code, :string, 4
      optional :ErrorCode, :enum, 5, "AIRDROP_ERROR_CODE"
    end
    add_message "JoinAirdropFarmTeamRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :TeamID, :int64, 2
    end
    add_message "JoinAirdropFarmTeamResponse" do
      optional :ErrorCode, :enum, 1, "AIRDROP_ERROR_CODE"
    end
    add_message "ApproveJoinAirdropFarmTeamRequest" do
      optional :JoinAirdropFarmTeamRequestID, :int64, 1
      optional :Captain, :message, 2, "AddressMessage"
      optional :ApprovedByServer, :bool, 3
    end
    add_message "ApproveJoinAirdropFarmTeamResponse" do
      optional :ErrorCode, :enum, 1, "AIRDROP_ERROR_CODE"
    end
    add_message "GetTeamMembersRequest" do
      optional :TeamID, :int64, 1
      optional :MaskAccount, :bool, 2
      optional :Status, :string, 3
    end
    add_message "TeamMember" do
      optional :Account, :string, 1
      optional :EventPoints, :message, 2, "DecimalMessage"
      optional :TotalPoints, :message, 3, "DecimalMessage"
      optional :TotalTradeVolume, :message, 4, "DecimalMessage"
      optional :Status, :string, 5
      optional :TeamMemberID, :int64, 6
      optional :IsCaptain, :bool, 7
    end
    add_message "GetTeamMembersResponse" do
      repeated :TeamMembers, :message, 1, "TeamMember"
    end
    add_message "QuitAirdropFarmTeamRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :TeamID, :int64, 2
    end
    add_message "QuitAirdropFarmTeamResponse" do
      optional :ErrorCode, :enum, 1, "AIRDROP_ERROR_CODE"
    end
    add_message "GetAirdropFarmRanklingListForApiRequest" do
      optional :SortBy, :string, 1
      optional :Account, :message, 2, "AddressMessage"
    end
    add_message "UserRanking" do
      optional :MaskedAccount, :string, 1
      optional :Ranking, :int64, 2
      optional :DailyTradeAmount, :message, 4, "DecimalMessage"
      optional :TotalTradeAmount, :message, 5, "DecimalMessage"
      optional :DailyEventPoints, :message, 6, "DecimalMessage"
      optional :TotalEventPoints, :message, 7, "DecimalMessage"
      optional :IsMe, :bool, 9
    end
    add_message "GetAirdropFarmRanklingListForApiResponse" do
      repeated :UserRankings, :message, 1, "UserRanking"
    end
    add_message "RemoveAirdropFarmTeamMemberRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :TeamID, :int64, 2
    end
    add_message "RemoveAirdropFarmTeamMemberResponse" do
      optional :ErrorCode, :enum, 1, "AIRDROP_ERROR_CODE"
    end
    add_enum "AIRDROP_ERROR_CODE" do
      value :NO_ERROR, 0
      value :HAVE_TEAM_ERROR, 1
      value :ALREADY_JOIN_TEAM, 2
      value :TEAM_MEMBER_IS_FULL_ERROR, 3
      value :NO_TEAM_ERROR, 4
      value :INVALID_TEAM_REQUEST_ERROR, 5
      value :UNDER_REVIEW_JOIN_TEAM_ERROR, 6
    end
  end
end

module Internal
  module AirdropFarmActivityProcessor
    GetAirdropFarmActivityBriefRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAirdropFarmActivityBriefRequest").msgclass
    AirdropFarmEpochActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AirdropFarmEpochActivity").msgclass
    GetAirdropFarmActivityBriefResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAirdropFarmActivityBriefResponse").msgclass
    AirdropFarmActivityStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AirdropFarmActivityStatus").msgclass
    AirdropFarmEpochActivityStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AirdropFarmEpochActivityStatus").msgclass
    GetAirdropFarmActivitySummaryStatsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAirdropFarmActivitySummaryStatsRequest").msgclass
    GetAirdropFarmActivitySummaryStatsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAirdropFarmActivitySummaryStatsResponse").msgclass
    GetAirdropFarmRanklingListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAirdropFarmRanklingListRequest").msgclass
    GetAirdropFarmRanklingListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAirdropFarmRanklingListResponse").msgclass
    CreateAirdropFarmTeamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateAirdropFarmTeamRequest").msgclass
    CreateAirdropFarmTeamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CreateAirdropFarmTeamResponse").msgclass
    JoinAirdropFarmTeamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JoinAirdropFarmTeamRequest").msgclass
    JoinAirdropFarmTeamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JoinAirdropFarmTeamResponse").msgclass
    ApproveJoinAirdropFarmTeamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ApproveJoinAirdropFarmTeamRequest").msgclass
    ApproveJoinAirdropFarmTeamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ApproveJoinAirdropFarmTeamResponse").msgclass
    GetTeamMembersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetTeamMembersRequest").msgclass
    TeamMember = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TeamMember").msgclass
    GetTeamMembersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetTeamMembersResponse").msgclass
    QuitAirdropFarmTeamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QuitAirdropFarmTeamRequest").msgclass
    QuitAirdropFarmTeamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QuitAirdropFarmTeamResponse").msgclass
    GetAirdropFarmRanklingListForApiRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAirdropFarmRanklingListForApiRequest").msgclass
    UserRanking = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("UserRanking").msgclass
    GetAirdropFarmRanklingListForApiResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetAirdropFarmRanklingListForApiResponse").msgclass
    RemoveAirdropFarmTeamMemberRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RemoveAirdropFarmTeamMemberRequest").msgclass
    RemoveAirdropFarmTeamMemberResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RemoveAirdropFarmTeamMemberResponse").msgclass
    AIRDROP_ERROR_CODE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AIRDROP_ERROR_CODE").enummodule
  end
end
