# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/airdrop_farm_activity/server.proto for package 'Internal.AirdropFarmActivityProcessor'

require 'grpc'
require 'internal/airdrop_farm_activity/server_pb'

module Internal
  module AirdropFarmActivityProcessor
    module AirdropFarmActivity
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'AirdropFarmActivity'

        rpc :GetAirdropFarmActivityBrief, ::Internal::AirdropFarmActivityProcessor::GetAirdropFarmActivityBriefRequest, ::Internal::AirdropFarmActivityProcessor::GetAirdropFarmActivityBriefResponse
        rpc :GetAirdropFarmActivitySummaryStats, ::Internal::AirdropFarmActivityProcessor::GetAirdropFarmActivitySummaryStatsRequest, ::Internal::AirdropFarmActivityProcessor::GetAirdropFarmActivitySummaryStatsResponse
        rpc :GetAirdropFarmRanklingList, ::Internal::AirdropFarmActivityProcessor::GetAirdropFarmRanklingListRequest, ::Internal::AirdropFarmActivityProcessor::GetAirdropFarmRanklingListResponse
        rpc :CreateAirdropFarmTeam, ::Internal::AirdropFarmActivityProcessor::CreateAirdropFarmTeamRequest, ::Internal::AirdropFarmActivityProcessor::CreateAirdropFarmTeamResponse
        rpc :JoinAirdropFarmTeam, ::Internal::AirdropFarmActivityProcessor::JoinAirdropFarmTeamRequest, ::Internal::AirdropFarmActivityProcessor::JoinAirdropFarmTeamResponse
        rpc :ApproveJoinAirdropFarmTeam, ::Internal::AirdropFarmActivityProcessor::ApproveJoinAirdropFarmTeamRequest, ::Internal::AirdropFarmActivityProcessor::ApproveJoinAirdropFarmTeamResponse
        rpc :UpdateAccountsVipLevelNotification, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :GetTeamMembers, ::Internal::AirdropFarmActivityProcessor::GetTeamMembersRequest, ::Internal::AirdropFarmActivityProcessor::GetTeamMembersResponse
        rpc :QuitAirdropFarmTeam, ::Internal::AirdropFarmActivityProcessor::QuitAirdropFarmTeamRequest, ::Internal::AirdropFarmActivityProcessor::QuitAirdropFarmTeamResponse
        rpc :GetAirdropFarmRankingListForApi, ::Internal::AirdropFarmActivityProcessor::GetAirdropFarmRanklingListForApiRequest, ::Internal::AirdropFarmActivityProcessor::GetAirdropFarmRanklingListForApiResponse
        rpc :FillYesterdayUserTokensCount, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :RemoveAirdropFarmTeamMember, ::Internal::AirdropFarmActivityProcessor::RemoveAirdropFarmTeamMemberRequest, ::Internal::AirdropFarmActivityProcessor::RemoveAirdropFarmTeamMemberResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
