# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/degen/server.proto for package 'Internal.Degen'

require 'grpc'
require 'internal/degen/server_pb'

module Internal
  module Degen
    module DegenService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'DegenService'

        rpc :GetAccountAsset, ::Internal::Degen::GetAccountAssetRequest, ::Internal::Degen::GetAccountAssetResponse
        rpc :GetAccountAssets, ::Internal::Degen::GetAccountAssetsRequest, ::Internal::Degen::GetAccountAssetsResponse
        rpc :GetAccountAssetWithPositionMargin, ::Internal::Degen::GetAccountAssetWithPositionMarginRequest, ::Internal::Degen::GetAccountAssetWithPositionMarginResponse
        rpc :GetAccountAssetsWithPositionMargin, ::Internal::Degen::GetAccountAssetsWithPositionMarginRequest, ::Internal::Degen::GetAccountAssetsWithPositionMarginResponse
        rpc :GetAllAccountAssetsWithPositionMargin, ::Google::Protobuf::Empty, ::Internal::Degen::GetAccountAssetsWithPositionMarginResponse
        rpc :GetAccountState, ::Internal::Degen::GetAccountStateRequest, ::Internal::Degen::GetAccountStateResponse
        rpc :GetAccountStates, ::Internal::Degen::GetAccountStatesRequest, ::Internal::Degen::GetAccountStatesResponse
        rpc :GetAccountPosition, ::Internal::Degen::GetAccountPositionRequest, ::Internal::Degen::GetAccountPositionResponse
        rpc :GetAccountPositions, ::Internal::Degen::GetAccountPositionsRequest, ::Internal::Degen::GetAccountPositionsResponse
        rpc :GetSystemAccountInfo, ::Internal::Degen::GetSystemAccountInfoRequest, ::Internal::Degen::GetSystemAccountInfoResponse
        rpc :UpdateAccountStateCache, ::Internal::Degen::UpdateAccountStateCacheRequest, ::Internal::Degen::UpdateAccountStateCacheResponse
        rpc :GetRiskPolicy, ::Google::Protobuf::Empty, ::Internal::Degen::GetRiskPolicyResponse
        rpc :GetSystemStatus, ::Google::Protobuf::Empty, ::Internal::Degen::GetSystemStatusResponse
        rpc :GetPlatformMarketPositionSize, ::Google::Protobuf::Empty, ::Internal::Degen::GetPlatformMarketPositionSizeResponse
        rpc :SenderAccountWithdraw, ::Internal::Degen::SenderAccountWithdrawRequest, ::Internal::Degen::DegenRaftLogResponse
        rpc :ReloadRiskAccount, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :GetAccountRiskLimit, ::Internal::Degen::GetAccountRiskLimitRequest, ::Internal::Degen::GetAccountRiskLimitResponse
        rpc :ApplyDegenRaftLog, ::Internal::Degen::DegenRaftLog, ::Internal::Degen::DegenRaftLogResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
