# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/raftadmin/raftadmin.proto for package 'Internal.Raftadmin'

require 'grpc'
require 'internal/raftadmin/raftadmin_pb'

module Internal
  module Raftadmin
    module RaftAdmin
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'RaftAdmin'

        rpc :AddNonvoter, ::Internal::Raftadmin::AddNonvoterRequest, ::Internal::Raftadmin::Future
        rpc :AddVoter, ::Internal::Raftadmin::AddVoterRequest, ::Internal::Raftadmin::Future
        rpc :AppliedIndex, ::Internal::Raftadmin::AppliedIndexRequest, ::Internal::Raftadmin::AppliedIndexResponse
        rpc :ApplyLog, ::Internal::Raftadmin::ApplyLogRequest, ::Internal::Raftadmin::Future
        rpc :Barrier, ::Internal::Raftadmin::BarrierRequest, ::Internal::Raftadmin::Future
        rpc :DemoteVoter, ::Internal::Raftadmin::DemoteVoterRequest, ::Internal::Raftadmin::Future
        rpc :GetConfiguration, ::Internal::Raftadmin::GetConfigurationRequest, ::Internal::Raftadmin::GetConfigurationResponse
        rpc :LastContact, ::Internal::Raftadmin::LastContactRequest, ::Internal::Raftadmin::LastContactResponse
        rpc :LastIndex, ::Internal::Raftadmin::LastIndexRequest, ::Internal::Raftadmin::LastIndexResponse
        rpc :Leader, ::Internal::Raftadmin::LeaderRequest, ::Internal::Raftadmin::LeaderResponse
        rpc :LeadershipTransfer, ::Internal::Raftadmin::LeadershipTransferRequest, ::Internal::Raftadmin::Future
        rpc :LeadershipTransferToServer, ::Internal::Raftadmin::LeadershipTransferToServerRequest, ::Internal::Raftadmin::Future
        rpc :RemoveServer, ::Internal::Raftadmin::RemoveServerRequest, ::Internal::Raftadmin::Future
        rpc :Shutdown, ::Internal::Raftadmin::ShutdownRequest, ::Internal::Raftadmin::Future
        rpc :Snapshot, ::Internal::Raftadmin::SnapshotRequest, ::Internal::Raftadmin::Future
        rpc :State, ::Internal::Raftadmin::StateRequest, ::Internal::Raftadmin::StateResponse
        rpc :Stats, ::Internal::Raftadmin::StatsRequest, ::Internal::Raftadmin::StatsResponse
        rpc :VerifyLeader, ::Internal::Raftadmin::VerifyLeaderRequest, ::Internal::Raftadmin::Future
        rpc :Await, ::Internal::Raftadmin::Future, ::Internal::Raftadmin::AwaitResponse
        rpc :Forget, ::Internal::Raftadmin::Future, ::Internal::Raftadmin::ForgetResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
