# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/raftadmin/raftadmin.proto

require 'google/protobuf'



Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/raftadmin/raftadmin.proto", :syntax => :proto3) do
    add_message "Future" do
      optional :operation_token, :string, 1
    end
    add_message "AwaitResponse" do
      optional :error, :string, 1
      optional :index, :uint64, 2
    end
    add_message "ForgetResponse" do
    end
    add_message "AddVoterRequest" do
      optional :id, :string, 1
      optional :address, :string, 2
      optional :previous_index, :uint64, 3
    end
    add_message "AddNonvoterRequest" do
      optional :id, :string, 1
      optional :address, :string, 2
      optional :previous_index, :uint64, 3
    end
    add_message "ApplyLogRequest" do
      optional :data, :bytes, 1
      optional :extensions, :bytes, 2
    end
    add_message "AppliedIndexRequest" do
    end
    add_message "AppliedIndexResponse" do
      optional :index, :uint64, 1
    end
    add_message "BarrierRequest" do
    end
    add_message "DemoteVoterRequest" do
      optional :id, :string, 1
      optional :previous_index, :uint64, 2
    end
    add_message "GetConfigurationRequest" do
    end
    add_message "GetConfigurationResponse" do
      repeated :servers, :message, 1, "GetConfigurationResponse.Server"
    end
    add_message "GetConfigurationResponse.Server" do
      optional :suffrage, :enum, 1, "GetConfigurationResponse.Server.Suffrage"
      optional :id, :string, 2
      optional :address, :string, 3
    end
    add_enum "GetConfigurationResponse.Server.Suffrage" do
      value :VOTER, 0
      value :NONVOTER, 1
      value :STAGING, 2
    end
    add_message "LastContactRequest" do
    end
    add_message "LastContactResponse" do
      optional :unix_nano, :int64, 1
    end
    add_message "LastIndexRequest" do
    end
    add_message "LastIndexResponse" do
      optional :index, :uint64, 1
    end
    add_message "LeaderRequest" do
    end
    add_message "LeaderResponse" do
      optional :address, :string, 1
    end
    add_message "LeadershipTransferRequest" do
    end
    add_message "LeadershipTransferToServerRequest" do
      optional :id, :string, 1
      optional :address, :string, 2
    end
    add_message "RemoveServerRequest" do
      optional :id, :string, 1
      optional :previous_index, :uint64, 2
    end
    add_message "ShutdownRequest" do
    end
    add_message "SnapshotRequest" do
    end
    add_message "StateRequest" do
    end
    add_message "StateResponse" do
      optional :state, :enum, 1, "StateResponse.State"
    end
    add_enum "StateResponse.State" do
      value :FOLLOWER, 0
      value :CANDIDATE, 1
      value :LEADER, 2
      value :SHUTDOWN, 3
    end
    add_message "StatsRequest" do
    end
    add_message "StatsResponse" do
      map :stats, :string, :string, 1
    end
    add_message "VerifyLeaderRequest" do
    end
  end
end

module Internal
  module Raftadmin
    Future = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Future").msgclass
    AwaitResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AwaitResponse").msgclass
    ForgetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ForgetResponse").msgclass
    AddVoterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AddVoterRequest").msgclass
    AddNonvoterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AddNonvoterRequest").msgclass
    ApplyLogRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ApplyLogRequest").msgclass
    AppliedIndexRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AppliedIndexRequest").msgclass
    AppliedIndexResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AppliedIndexResponse").msgclass
    BarrierRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("BarrierRequest").msgclass
    DemoteVoterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DemoteVoterRequest").msgclass
    GetConfigurationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetConfigurationRequest").msgclass
    GetConfigurationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetConfigurationResponse").msgclass
    GetConfigurationResponse::Server = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetConfigurationResponse.Server").msgclass
    GetConfigurationResponse::Server::Suffrage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GetConfigurationResponse.Server.Suffrage").enummodule
    LastContactRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LastContactRequest").msgclass
    LastContactResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LastContactResponse").msgclass
    LastIndexRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LastIndexRequest").msgclass
    LastIndexResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LastIndexResponse").msgclass
    LeaderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LeaderRequest").msgclass
    LeaderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LeaderResponse").msgclass
    LeadershipTransferRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LeadershipTransferRequest").msgclass
    LeadershipTransferToServerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LeadershipTransferToServerRequest").msgclass
    RemoveServerRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("RemoveServerRequest").msgclass
    ShutdownRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ShutdownRequest").msgclass
    SnapshotRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SnapshotRequest").msgclass
    StateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StateRequest").msgclass
    StateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StateResponse").msgclass
    StateResponse::State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StateResponse.State").enummodule
    StatsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StatsRequest").msgclass
    StatsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StatsResponse").msgclass
    VerifyLeaderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("VerifyLeaderRequest").msgclass
  end
end
