# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/degen_subaccount/server.proto for package 'Internal.DegenSubaccount'

require 'grpc'
require 'internal/degen_subaccount/server_pb'

module Internal
  module DegenSubaccount
    module DegenSubaccountService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'DegenSubaccountService'

        rpc :SysDepositJusd, ::Internal::DegenSubaccount::DegenSubaccountDepositJusdRequest, ::Google::Protobuf::BoolValue
        rpc :CreateLiquidationOrder, ::Internal::DegenSubaccount::DegenSubaccountLiquidationRequest, ::Internal::DegenSubaccount::DegenSubaccountLiquidationResponse
        rpc :GetLiquidationPendingOrders, ::Internal::DegenSubaccount::DegenSubaccountLiquidationPendingOrdersRequest, ::Internal::DegenSubaccount::DegenSubaccountLiquidationPendingOrdersResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
