# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/degen_subaccount/server.proto

require 'google/protobuf'


require 'google/protobuf/wrappers_pb'
require 'internal/ext/address_pb'
require 'internal/types/order_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/degen_subaccount/server.proto", :syntax => :proto3) do
    add_message "DegenSubaccountDepositJusdRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "DegenSubaccountLiquidationRequest" do
      optional :Account, :message, 1, "AddressMessage"
      optional :MarketID, :string, 2
      optional :TakerOrder, :message, 3, "TypesOrderJSON"
      optional :TriggerTime, :int64, 4
      optional :TriggerPrice, :string, 5
      optional :TakerAccount, :message, 6, "AddressMessage"
      optional :TakerTime, :int64, 7
      optional :TakerPrice, :string, 8
      optional :GuidePrice, :string, 9
    end
    add_message "DegenSubaccountLiquidationResponse" do
      optional :Status, :string, 1
      optional :ErrorMessage, :string, 2
      optional :LiquidationOrderSource, :string, 3
    end
    add_message "DegenSubaccountLiquidationPendingOrdersRequest" do
      optional :Account, :message, 1, "AddressMessage"
    end
    add_message "DegenSubaccountLiquidationPendingOrder" do
      optional :MarketID, :string, 1
      optional :LiquidationOrderSource, :string, 2
      optional :PaperAmount, :string, 3
      optional :CreditAmount, :string, 4
    end
    add_message "DegenSubaccountLiquidationPendingOrdersResponse" do
      optional :Account, :message, 1, "AddressMessage"
      repeated :PendingOrders, :message, 2, "DegenSubaccountLiquidationPendingOrder"
    end
  end
end

module Internal
  module DegenSubaccount
    DegenSubaccountDepositJusdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenSubaccountDepositJusdRequest").msgclass
    DegenSubaccountLiquidationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenSubaccountLiquidationRequest").msgclass
    DegenSubaccountLiquidationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenSubaccountLiquidationResponse").msgclass
    DegenSubaccountLiquidationPendingOrdersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenSubaccountLiquidationPendingOrdersRequest").msgclass
    DegenSubaccountLiquidationPendingOrder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenSubaccountLiquidationPendingOrder").msgclass
    DegenSubaccountLiquidationPendingOrdersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DegenSubaccountLiquidationPendingOrdersResponse").msgclass
  end
end
