# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/errors/order.proto

require 'google/protobuf'



Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("internal/errors/order.proto", :syntax => :proto3) do
    add_message "OrderError" do
      optional :Code, :int64, 1
      optional :Message, :string, 2
      optional :InternalErrorMessage, :string, 3
    end
  end
end

module Internal
  module Errors
    OrderError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("OrderError").msgclass
  end
end
